import { BLIGHT_RADIO } from "./blight-radio.js";

export const BLIGHT_MOODS = [
  { id: "rebellious", name: "Rebellious" },
  { id: "melancholic", name: "Melancholic" },
  { id: "relaxing", name: "Relaxing" },
  { id: "brutal", name: "Brutal" },
];

export const BLIGHT_BATTLE = [
  "raving_energy",
  "rave_faster",
  "ultra_storm",
  "kick_shock",
  "go_cart",
  "show_moves",
  "harmful",
  "metalmania",
  "ready_aim",
  "severe_tire",
  "danger_storm",
  "furious_freak",
  "tyrant",
  "edm_detect",
  "voltaic",
  "exhilarate",
];

const M = "audio/blight/music/";

export const BLIGHT_LAYERS = [
  { id: "newer_wave", name: "Newer Wave", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "newer_wave.ogg" },
  { id: "neon_laser", name: "Neon Laser Horizon", category: "music", world: "blight", icon: "bolt", mood: "melancholic", file: M + "neon_laser.ogg" },
  { id: "cyborg_ninja", name: "Cyborg Ninja", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "cyborg_ninja.ogg" },
  { id: "space_fighter", name: "Space Fighter", category: "music", world: "blight", icon: "bolt", mood: "melancholic", file: M + "space_fighter.ogg" },
  { id: "reformat", name: "Reformat", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "reformat.ogg" },
  { id: "ethernight", name: "Ethernight Club", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "ethernight.ogg" },
  { id: "equatorial", name: "Equatorial Complex", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "equatorial.ogg" },
  { id: "cloud_dancer", name: "Cloud Dancer", category: "music", world: "blight", icon: "bolt", mood: "melancholic", file: M + "cloud_dancer.ogg" },
  { id: "laser_groove", name: "Laser Groove", category: "music", world: "blight", icon: "bolt", mood: "melancholic", file: M + "laser_groove.ogg" },
  { id: "digital_lemonade", name: "Digital Lemonade", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "digital_lemonade.ogg" },
  { id: "edm_detect", name: "EDM Detection", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "edm_detect.ogg" },
  { id: "laserpack", name: "Laserpack", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "laserpack.ogg" },
  { id: "raving_energy", name: "Raving Energy", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "raving_energy.ogg" },
  { id: "dance_monster", name: "Dance Monster", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "dance_monster.ogg" },
  { id: "cut_trance", name: "Cut Trance", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "cut_trance.ogg" },
  { id: "voltaic", name: "Voltaic", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "voltaic.ogg" },
  { id: "club_diver", name: "Club Diver", category: "music", world: "blight", icon: "moon", mood: "brutal", file: M + "club_diver.ogg" },
  { id: "kick_shock", name: "Kick Shock", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "kick_shock.ogg" },
  { id: "shiny_tech", name: "Shiny Tech", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "shiny_tech.ogg" },
  { id: "ultra_storm", name: "Ultra Storm", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "ultra_storm.ogg" },
  { id: "voxel_rev", name: "Voxel Revolution", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "voxel_rev.ogg" },
  { id: "brain_dance", name: "Brain Dance", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "brain_dance.ogg" },
  { id: "rave_faster", name: "Raving Energy Faster", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "rave_faster.ogg" },
  { id: "go_cart", name: "Go Cart", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "go_cart.ogg" },
  { id: "show_moves", name: "Show Your Moves", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "show_moves.ogg" },
  { id: "phat_sketch", name: "Phat Sketch", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "phat_sketch.ogg" },
  { id: "future_cha", name: "Future Cha Cha", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "future_cha.ogg" },
  { id: "harmful", name: "Harmful or Fatal", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "harmful.ogg" },
  { id: "deep_dirty", name: "Deep and Dirty", category: "music", world: "blight", icon: "moon", mood: "brutal", file: M + "deep_dirty.ogg" },
  { id: "limit_70", name: "Limit 70", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "limit_70.ogg" },
  { id: "blippy", name: "Blippy Trance", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "blippy.ogg" },
  { id: "bit_shift", name: "Bit Shift", category: "music", world: "blight", icon: "spark", mood: "brutal", file: M + "bit_shift.ogg" },
  { id: "cipher_net", name: "Cipher", category: "music", world: "blight", icon: "sneak", mood: "brutal", file: M + "cipher_net.ogg" },
  { id: "getting_done", name: "Getting it Done", category: "music", world: "blight", icon: "bolt", mood: "brutal", file: M + "getting_done.ogg" },
  { id: "space_x", name: "Space X-plorers", category: "music", world: "blight", icon: "spark", mood: "melancholic", file: M + "space_x.ogg" },
  { id: "chill_wave", name: "Chill Wave", category: "music", world: "blight", icon: "moon", mood: "relaxing", file: M + "chill_wave.ogg" },
  { id: "mellowtron", name: "Mellowtron", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "mellowtron.ogg" },
  { id: "beauty_flow", name: "Beauty Flow", category: "music", world: "blight", icon: "wave", mood: "relaxing", file: M + "beauty_flow.ogg" },
  { id: "dream_catcher", name: "Dream Catcher", category: "music", world: "blight", icon: "moon", mood: "relaxing", file: M + "dream_catcher.ogg" },
  { id: "hypnothis", name: "Hypnothis", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "hypnothis.ogg" },
  { id: "ambler", name: "Ambler", category: "music", world: "blight", icon: "path", mood: "relaxing", file: M + "ambler.ogg" },
  { id: "chillin_hard", name: "Chillin Hard", category: "music", world: "blight", icon: "moon", mood: "relaxing", file: M + "chillin_hard.ogg" },
  { id: "deliberate", name: "Deliberate Thought", category: "music", world: "blight", icon: "book", mood: "relaxing", file: M + "deliberate.ogg" },
  { id: "tranquility_net", name: "Tranquility", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "tranquility.ogg" },
  { id: "rising_tide_net", name: "Rising Tide", category: "music", world: "blight", icon: "wave", mood: "relaxing", file: M + "rising_tide.ogg" },
  { id: "metalmania", name: "Metalmania", category: "music", world: "blight", icon: "storm", mood: "rebellious", file: M + "metalmania.ogg" },
  { id: "ready_aim", name: "Ready Aim Fire", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "ready_aim.ogg" },
  { id: "twisted", name: "Twisted", category: "music", world: "blight", icon: "storm", mood: "rebellious", file: M + "twisted.ogg" },
  { id: "broken_reality", name: "Broken Reality", category: "music", world: "blight", icon: "mask", mood: "rebellious", file: M + "broken_reality.ogg" },
  { id: "severe_tire", name: "Severe Tire Damage", category: "music", world: "blight", icon: "storm", mood: "rebellious", file: M + "severe_tire.ogg" },
  { id: "exit_premises", name: "Exit the Premises", category: "music", world: "blight", icon: "sneak", mood: "rebellious", file: M + "exit_premises.ogg" },
  { id: "furious_freak", name: "Furious Freak", category: "music", world: "blight", icon: "bolt", mood: "rebellious", file: M + "furious_freak.ogg" },
  { id: "danger_storm", name: "Danger Storm", category: "music", world: "blight", icon: "storm", mood: "rebellious", file: M + "danger_storm.ogg" },
  { id: "tyrant", name: "Tyrant", category: "music", world: "blight", icon: "mask", mood: "rebellious", file: M + "tyrant.ogg" },
  { id: "exhilarate", name: "Exhilarate", category: "music", world: "blight", icon: "banner", mood: "rebellious", file: M + "exhilarate.ogg" },
  { id: "motherlode", name: "Motherlode", category: "music", world: "blight", icon: "anvil", mood: "rebellious", file: M + "motherlode.ogg" },
  { id: "hotrock", name: "Hotrock", category: "music", world: "blight", icon: "fire", mood: "rebellious", file: M + "hotrock.ogg" },
  { id: "big_rock", name: "Big Rock", category: "music", world: "blight", icon: "anvil", mood: "rebellious", file: M + "big_rock.ogg" },
  { id: "cool_rock", name: "Cool Rock", category: "music", world: "blight", icon: "fire", mood: "rebellious", file: M + "cool_rock.ogg" },
  { id: "too_cool", name: "Too Cool", category: "music", world: "blight", icon: "moon", mood: "rebellious", file: M + "too_cool.ogg" },
  { id: "retro_nasty", name: "RetroFuture Nasty", category: "music", world: "blight", icon: "spark", mood: "rebellious", file: M + "retro_nasty.ogg" },

  { id: "neon_street", name: "Strip traffic", category: "ambience", world: "blight", icon: "square", file: "audio/ambience/street.ogg", space: "out" },
  { id: "club_floor", name: "Club floor", category: "ambience", world: "blight", icon: "mug", file: "audio/ambience/crowded_pub.ogg", space: "in" },
  { id: "chrome_rain", name: "Rain on chrome", category: "ambience", world: "blight", icon: "rain", file: "audio/weather/metal_roof.ogg", space: "both" },
  { id: "undercity_bed", name: "Undercity", category: "ambience", world: "blight", icon: "sewer", file: "audio/ambience/sewers.ogg", space: "in" },
  { id: "foundry_bed", name: "Foundry", category: "ambience", world: "blight", icon: "anvil", file: "audio/ambience/forge.ogg", space: "in" },
  { id: "tunnel_bed", name: "Service tunnels", category: "ambience", world: "blight", icon: "dungeon", file: "audio/ambience/dungeon.ogg", space: "in" },
  { id: "grid_hum", name: "Grid hum", category: "ambience", world: "blight", icon: "spark", file: "audio/ambience/deep_hum.ogg", space: "both" },
  { id: "megadocks_bed", name: "Megadocks", category: "ambience", world: "blight", icon: "ship", file: "audio/ambience/harbor.ogg", space: "out" },
  { id: "vent_air", name: "Roof vents", category: "ambience", world: "blight", icon: "wind", file: "audio/weather/mountain_air.ogg", space: "out" },
  { id: "archive_bed", name: "Archive hush", category: "ambience", world: "blight", icon: "book", file: "audio/ambience/library.ogg", space: "in" },
  { id: "club_clock", name: "Lobby clock", category: "ambience", world: "blight", icon: "clock", file: "audio/ambience/clock.ogg", space: "in" },
  { id: "acid_surf", name: "Foul surf", category: "ambience", world: "blight", icon: "wave", file: "audio/ambience/shore.ogg", space: "out" },
  { id: "flooded_bed", name: "Flooded streets", category: "ambience", world: "blight", icon: "fish", file: "audio/ambience/underwater.ogg", space: "both" },
  { id: "squatter_fire", name: "Barrel fire", category: "ambience", world: "blight", icon: "fire", file: "audio/ambience/campfire.ogg", space: "out" },
  { id: "stray_dogs", name: "Stray dogs", category: "animals", world: "blight", icon: "dog", file: "audio/animals/farmyard.ogg", space: "both" },
  { id: "city_hounds", name: "Yard hounds", category: "animals", world: "blight", icon: "dog", file: "audio/animals/farmyard.ogg", space: "both" },
  ...BLIGHT_RADIO,
];

export const BLIGHT_SCENES = [
  { id: "tavern", name: "Afterhours", blurb: "A rebellious station. Bass through the floor.", icon: "mug", mood: "ember", setting: "japantown", playlist: "rebellious", layers: { club_floor: 0.42, chrome_rain: 0.28, rain: 0.18 } },
  { id: "city", name: "Neon Strip", blurb: "Riot radio over wet asphalt.", icon: "square", mood: "violet", setting: "downtown", playlist: "rebellious", layers: { neon_street: 0.5, rain: 0.22, chrome_rain: 0.16 } },
  { id: "square", name: "Night Market", blurb: "Soft synths in the steam.", icon: "market", mood: "ember", setting: "kabuki", playlist: "relaxing", layers: { neon_street: 0.36, club_floor: 0.22, rain: 0.14 } },
  { id: "camp", name: "Squatter Roof", blurb: "Melancholy over forty storeys of rain.", icon: "fire", mood: "ember", setting: "watson", playlist: "melancholic", layers: { squatter_fire: 0.5, vent_air: 0.28, neon_street: 0.16 } },
  { id: "watch", name: "Antenna Watch", blurb: "A sad station in the dishes.", icon: "mountain", mood: "slate", setting: "charter-hill", playlist: "melancholic", layers: { vent_air: 0.46, grid_hum: 0.3, wind: 0.2 } },
  { id: "crawl", name: "Undercity", blurb: "Gloom radio in the cables.", icon: "dungeon", mood: "slate", setting: "northside", playlist: "melancholic", layers: { undercity_bed: 0.52, tunnel_bed: 0.3, drips: 0.22 } },
  { id: "under", name: "Service Spine", blurb: "Brutal industrial through the pipes.", icon: "sewer", mood: "slate", setting: "northside", playlist: "brutal", layers: { undercity_bed: 0.5, grid_hum: 0.28, drips: 0.2 } },
  { id: "crypt", name: "Server Crypt", blurb: "A melancholic hymn for dead racks.", icon: "tomb", mood: "violet", setting: "city-center", playlist: "melancholic", layers: { archive_bed: 0.36, grid_hum: 0.4, drips: 0.14 } },
  { id: "storm", name: "Chrome Storm", blurb: "Brutal weather, brutal music.", icon: "storm", mood: "storm", setting: "nightcity", playlist: "brutal", layers: { downpour: 0.6, thunder: 0.7, chrome_rain: 0.34, wind: 0.3 } },
  { id: "battles", name: "Ruckus", blurb: "The brutal station. No ballads.", icon: "swords", mood: "blood", playlist: "brutal", setting: "corpo-plaza", layers: { foundry_bed: 0.28 } },
  { id: "rave-night", name: "Warehouse Rave", blurb: "Brutal rave until the floor gives up.", icon: "bolt", mood: "blood", playlist: "brutal", setting: "dogtown", layers: { club_floor: 0.36, grid_hum: 0.16 } },
  { id: "battle", name: "Corp Arena", blurb: "Brutal feeds, a cage, a crowd.", icon: "swords", mood: "blood", playlist: "brutal", setting: "corpo-plaza", layers: { foundry_bed: 0.3, neon_street: 0.16 } },
  { id: "sea", name: "Megadocks", blurb: "Melancholy horns over black water.", icon: "ship", mood: "sea", setting: "arasaka-waterfront", playlist: "melancholic", layers: { megadocks_bed: 0.5, wind: 0.22, ocean: 0.18 } },
  { id: "docks", name: "Night Slip", blurb: "Oil, rain, a sad frequency.", icon: "ship", mood: "sea", setting: "arasaka-waterfront", playlist: "melancholic", layers: { megadocks_bed: 0.48, rain: 0.22 } },
  { id: "strand", name: "Acid Shore", blurb: "Grey surf. Melancholy on the wind.", icon: "wave", mood: "sea", setting: "pacifica", playlist: "melancholic", layers: { acid_surf: 0.5, wind: 0.24, fog: 0.16 } },
  { id: "depths", name: "Drowned Blocks", blurb: "A drowned station under the silt.", icon: "fish", mood: "sea", setting: "coastview", playlist: "melancholic", layers: { flooded_bed: 0.55, grid_hum: 0.2 } },
  { id: "sanctum", name: "Chrome Shrine", blurb: "Relaxing, if you ignore the LEDs.", icon: "temple", mood: "gold", setting: "little-china", playlist: "relaxing", layers: { archive_bed: 0.32, grid_hum: 0.18 } },
  { id: "court", name: "Penthouse", blurb: "Soft radio above the toy city.", icon: "crown", mood: "gold", setting: "north-oak", playlist: "relaxing", layers: { club_clock: 0.28, grid_hum: 0.2 } },
  { id: "forest", name: "Overgrowth", blurb: "Relaxing green over dead towers.", icon: "trees", mood: "green", setting: "the-glen", playlist: "relaxing", layers: { vent_air: 0.3, wind: 0.22, rain: 0.16 } },
  { id: "mire", name: "Chem Bog", blurb: "Melancholy in the runoff.", icon: "swamp", mood: "green", setting: "arroyo", playlist: "melancholic", layers: { fog: 0.4, vent_air: 0.22 } },
  { id: "smithy", name: "Chop Shop", blurb: "Rebellious radio too loud for the grinders.", icon: "anvil", mood: "blood", setting: "arroyo", playlist: "rebellious", layers: { foundry_bed: 0.46, grid_hum: 0.16 } },
  { id: "stacks", name: "Net Archive", blurb: "Relaxing dust on dead glass.", icon: "book", mood: "gold", setting: "downtown", playlist: "relaxing", layers: { archive_bed: 0.5, club_clock: 0.16 } },
  { id: "dunes", name: "Scrap Highway", blurb: "Rebellious miles of wrecks.", icon: "dune", mood: "ember", setting: "badlands", playlist: "rebellious", layers: { vent_air: 0.3, wind: 0.26 } },
  { id: "killing-moon", name: "Tycho", blurb: "Luna under glass. Earth on the horizon. A sad station in the vacuum.", icon: "moon", mood: "slate", setting: "luna", playlist: "melancholic", layers: { grid_hum: 0.36, vent_air: 0.22, archive_bed: 0.16 } },
  { id: "earthrise", name: "Earthrise", blurb: "Regolith, mass drivers, and a blue marble that still bills you.", icon: "moon", mood: "violet", setting: "luna", playlist: "melancholic", layers: { vent_air: 0.4, grid_hum: 0.24, wind: 0.12 } },
  { id: "copernicus", name: "Copernicus", blurb: "Park caverns under a pressure dome. Soft radio. Hard air.", icon: "moon", mood: "gold", setting: "luna", playlist: "relaxing", layers: { archive_bed: 0.28, grid_hum: 0.22, club_clock: 0.12 } },
  { id: "goldwire", name: "Goldwire", blurb: "A Night City casino. Chips, smoke, and a station that never blinks.", icon: "crown", mood: "gold", setting: "casino", playlist: "relaxing", layers: { club_floor: 0.4, club_clock: 0.22, grid_hum: 0.14 } },
  { id: "high-roller", name: "High Roller Pit", blurb: "Brutal bass under gold light. Someone is already broke.", icon: "crown", mood: "blood", setting: "casino", playlist: "brutal", layers: { club_floor: 0.46, neon_street: 0.12, grid_hum: 0.16 } },
];
