const M = "audio/blight/music/";
export const BLIGHT_RADIO = [
  { id: "br_burn_the_world_waltz", name: "Burn The World Waltz", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_burn_the_world_waltz.ogg" },
  { id: "br_feral_angel_waltz", name: "Feral Angel Waltz", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_feral_angel_waltz.ogg" },
  { id: "br_summon_the_rawk", name: "Summon the Rawk", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_summon_the_rawk.ogg" },
  { id: "br_take_the_lead", name: "Take the Lead", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_take_the_lead.ogg" },
  { id: "br_motivator", name: "Motivator", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_motivator.ogg" },
  { id: "br_el_magicia", name: "El Magicia", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_el_magicia.ogg" },
  { id: "br_bet_you_can_ver_2", name: "Bet You Can ver 2", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_bet_you_can_ver_2.ogg" },
  { id: "br_welcome_to_the_show", name: "Welcome to the Show", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_welcome_to_the_show.ogg" },
  { id: "br_sax_rock_and_roll", name: "Sax, Rock, and Roll", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_sax_rock_and_roll.ogg" },
  { id: "br_bet_you_can", name: "Bet You Can", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_bet_you_can.ogg" },
  { id: "br_highlight_reel", name: "Highlight Reel", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_highlight_reel.ogg" },
  { id: "br_neolith", name: "Neolith", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_neolith.ogg" },
  { id: "br_i_feel_you", name: "I Feel You", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_i_feel_you.ogg" },
  { id: "br_pilot_error", name: "Pilot Error", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_pilot_error.ogg" },
  { id: "br_eighties_action", name: "Eighties Action", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_eighties_action.ogg" },
  { id: "br_fantasia_fantasia", name: "Fantasia Fantasia", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_fantasia_fantasia.ogg" },
  { id: "br_neo_western", name: "Neo Western", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_neo_western.ogg" },
  { id: "br_gearhead", name: "Gearhead", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_gearhead.ogg" },
  { id: "br_pulse", name: "Pulse", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_pulse.ogg" },
  { id: "br_delay_rock", name: "Delay Rock", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_delay_rock.ogg" },
  { id: "br_cool_hard_facts", name: "Cool Hard Facts", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_cool_hard_facts.ogg" },
  { id: "br_rock_hybrid", name: "Rock Hybrid", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_rock_hybrid.ogg" },
  { id: "br_iron_bacon", name: "Iron Bacon", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_iron_bacon.ogg" },
  { id: "br_what_you_want_version_2", name: "What You Want (version 2)", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_what_you_want_version_2.ogg" },
  { id: "br_clash_defiant", name: "Clash Defiant", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_clash_defiant.ogg" },
  { id: "br_what_you_want", name: "What You Want", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_what_you_want.ogg" },
  { id: "br_surf_shimmy", name: "Surf Shimmy", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_surf_shimmy.ogg" },
  { id: "br_waltz_primordial", name: "Waltz Primordial", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_waltz_primordial.ogg" },
  { id: "br_freddy_s_menagerie", name: "Freddy's Menagerie", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_freddy_s_menagerie.ogg" },
  { id: "br_riptide", name: "Riptide", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_riptide.ogg" },
  { id: "br_feelin_good", name: "Feelin Good", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_feelin_good.ogg" },
  { id: "br_funin_and_sunin", name: "Funin and Sunin", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_funin_and_sunin.ogg" },
  { id: "br_retrofuture_clean", name: "RetroFuture Clean", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_retrofuture_clean.ogg" },
  { id: "br_sock_hop", name: "Sock Hop", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_sock_hop.ogg" },
  { id: "br_rock_over_london", name: "Rock Over London", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_rock_over_london.ogg" },
  { id: "br_breakdown", name: "Breakdown", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_breakdown.ogg" },
  { id: "br_aitech", name: "Aitech", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_aitech.ogg" },
  { id: "br_raw", name: "Raw", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_raw.ogg" },
  { id: "br_malt_shop_bop", name: "Malt Shop Bop", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_malt_shop_bop.ogg" },
  { id: "br_dead_drop", name: "Dead Drop", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_dead_drop.ogg" },
  { id: "br_rock_on_chicago", name: "Rock on Chicago", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_rock_on_chicago.ogg" },
  { id: "br_wah_game_loop", name: "Wah Game Loop", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_wah_game_loop.ogg" },
  { id: "br_cognitive_dissonance", name: "Cognitive Dissonance", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_cognitive_dissonance.ogg" },
  { id: "br_consequence", name: "Consequence", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_consequence.ogg" },
  { id: "br_got_funk", name: "Got Funk", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_got_funk.ogg" },
  { id: "br_takeover_of_the_8_bit_synths", name: "Takeover of the 8-bit Synths", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_takeover_of_the_8_bit_synths.ogg" },
  { id: "br_zap_beat", name: "Zap Beat", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_zap_beat.ogg" },
  { id: "br_dentaneosuchus_hunt", name: "Dentaneosuchus Hunt", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_dentaneosuchus_hunt.ogg" },
  { id: "br_half_mystery", name: "Half Mystery", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_half_mystery.ogg" },
  { id: "br_hand_balance_redux", name: "Hand Balance Redux", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_hand_balance_redux.ogg" },
  { id: "br_morgana_rides", name: "Morgana Rides", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_morgana_rides.ogg" },
  { id: "br_surf_inspector", name: "Surf Inspector", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_surf_inspector.ogg" },
  { id: "br_realizer", name: "Realizer", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_realizer.ogg" },
  { id: "br_rising_tide_faster", name: "Rising Tide (faster)", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_rising_tide_faster.ogg" },
  { id: "br_blown_away", name: "Blown Away", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_blown_away.ogg" },
  { id: "br_thinking_out_loud", name: "Thinking Out Loud", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_thinking_out_loud.ogg" },
  { id: "br_presenterator", name: "Presenterator", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_presenterator.ogg" },
  { id: "br_river_of_io", name: "River of Io", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_river_of_io.ogg" },
  { id: "br_trips_it", name: "Trips It", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_trips_it.ogg" },
  { id: "br_industrial_cinematic", name: "Industrial Cinematic", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_industrial_cinematic.ogg" },
  { id: "br_unity", name: "Unity", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_unity.ogg" },
  { id: "br_aggressor", name: "Aggressor", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_aggressor.ogg" },
  { id: "br_captain_scurvy", name: "Captain Scurvy", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_captain_scurvy.ogg" },
  { id: "br_tikopia", name: "Tikopia", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_tikopia.ogg" },
  { id: "br_nightmare_machine", name: "Nightmare Machine", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_nightmare_machine.ogg" },
  { id: "br_malicious", name: "Malicious", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_malicious.ogg" },
  { id: "br_stompdance", name: "StompDance", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_stompdance.ogg" },
  { id: "br_just_nasty", name: "Just Nasty", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_just_nasty.ogg" },
  { id: "br_big_drumming", name: "Big Drumming", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_big_drumming.ogg" },
  { id: "br_journey_to_ascend", name: "Journey To Ascend", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_journey_to_ascend.ogg" },
  { id: "br_invariance", name: "Invariance", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_invariance.ogg" },
  { id: "br_greko_sketch", name: "Greko (Sketch)", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_greko_sketch.ogg" },
  { id: "br_i_can_feel_it_coming", name: "I Can Feel it Coming", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_i_can_feel_it_coming.ogg" },
  { id: "br_firesong", name: "Firesong", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_firesong.ogg" },
  { id: "br_naraina", name: "Naraina", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_naraina.ogg" },
  { id: "br_perigrine_grandeur", name: "Perigrine Grandeur", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_perigrine_grandeur.ogg" },
  { id: "br_super_power_cool_dude", name: "Super Power Cool Dude", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_super_power_cool_dude.ogg" },
  { id: "br_miami_nights_extended_theme", name: "Miami Nights - Extended Theme", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_miami_nights_extended_theme.ogg" },
  { id: "br_firebrand", name: "Firebrand", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_firebrand.ogg" },
  { id: "br_twisting", name: "Twisting", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_twisting.ogg" },
  { id: "br_witch_hunt", name: "Witch Hunt", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_witch_hunt.ogg" },
  { id: "br_eternal_terminal", name: "Eternal Terminal", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_eternal_terminal.ogg" },
  { id: "br_wretched_destroyer", name: "Wretched Destroyer", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_wretched_destroyer.ogg" },
  { id: "br_misuse", name: "Misuse", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_misuse.ogg" },
  { id: "br_aces_high", name: "Aces High", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_aces_high.ogg" },
  { id: "br_special_spotlight", name: "Special Spotlight", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_special_spotlight.ogg" },
  { id: "br_hiding_your_reality", name: "Hiding Your Reality", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_hiding_your_reality.ogg" },
  { id: "br_magistar", name: "Magistar", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_magistar.ogg" },
  { id: "br_nonstop", name: "Nonstop", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_nonstop.ogg" },
  { id: "br_enter_the_party", name: "Enter the Party", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_enter_the_party.ogg" },
  { id: "br_delightful_d", name: "Delightful D", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_delightful_d.ogg" },
  { id: "br_loopster", name: "Loopster", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_loopster.ogg" },
  { id: "br_overriding_concern", name: "Overriding Concern", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_overriding_concern.ogg" },
  { id: "br_pyro_flow", name: "Pyro Flow", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_pyro_flow.ogg" },
  { id: "br_shamanistic", name: "Shamanistic", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_shamanistic.ogg" },
  { id: "br_crossing_the_chasm", name: "Crossing the Chasm", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_crossing_the_chasm.ogg" },
  { id: "br_windswept", name: "Windswept", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_windswept.ogg" },
  { id: "br_ripples", name: "Ripples", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ripples.ogg" },
  { id: "br_fearless_first", name: "Fearless First", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_fearless_first.ogg" },
  { id: "br_meditation_impromptu_03", name: "Meditation Impromptu 03", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_meditation_impromptu_03.ogg" },
  { id: "br_impact_allegretto", name: "Impact Allegretto", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_impact_allegretto.ogg" },
  { id: "br_meditation_impromptu_02", name: "Meditation Impromptu 02", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_meditation_impromptu_02.ogg" },
  { id: "br_chill", name: "Chill", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_chill.ogg" },
  { id: "br_pure_attitude", name: "Pure Attitude", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_pure_attitude.ogg" },
  { id: "br_soaring", name: "Soaring", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_soaring.ogg" },
  { id: "br_with_regards", name: "With Regards", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_with_regards.ogg" },
  { id: "br_peaceful_desolation", name: "Peaceful Desolation", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_peaceful_desolation.ogg" },
  { id: "br_serene", name: "Serene", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_serene.ogg" },
  { id: "br_frozen_star", name: "Frozen Star", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_frozen_star.ogg" },
  { id: "br_inspired", name: "Inspired", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_inspired.ogg" },
  { id: "br_mountain_emperor", name: "Mountain Emperor", category: "music", world: "blight", icon: "swords", mood: "rebellious", file: M + "br_mountain_emperor.ogg" },
  { id: "br_winter_reflections", name: "Winter Reflections", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_winter_reflections.ogg" },
  { id: "br_what_is_love", name: "What Is Love", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_what_is_love.ogg" },
  { id: "br_townie_loop", name: "Townie Loop", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_townie_loop.ogg" },
  { id: "br_airport_lounge", name: "Airport Lounge", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_airport_lounge.ogg" },
  { id: "br_a_very_brady_special", name: "A Very Brady Special", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_a_very_brady_special.ogg" },
  { id: "br_airship_serenity", name: "Airship Serenity", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_airship_serenity.ogg" },
  { id: "br_blue_feather", name: "Blue Feather", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_blue_feather.ogg" },
  { id: "br_canon_in_d_for_two_harps", name: "Canon in D for Two Harps", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_canon_in_d_for_two_harps.ogg" },
  { id: "br_clean_soul", name: "Clean Soul", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_clean_soul.ogg" },
  { id: "br_canon_in_d_interstellar_mix", name: "Canon In D Interstellar Mix", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_canon_in_d_interstellar_mix.ogg" },
  { id: "br_meditation_impromptu_01", name: "Meditation Impromptu 01", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_meditation_impromptu_01.ogg" },
  { id: "br_canon_in_d_for_autoharp", name: "Canon in D for Autoharp", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_canon_in_d_for_autoharp.ogg" },
  { id: "br_devonshire_waltz_allegretto", name: "Devonshire Waltz Allegretto", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_devonshire_waltz_allegretto.ogg" },
  { id: "br_crinoline_dreams", name: "Crinoline Dreams", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_crinoline_dreams.ogg" },
  { id: "br_cold_funk", name: "Cold Funk", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_cold_funk.ogg" },
  { id: "br_mirage", name: "Mirage", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_mirage.ogg" },
  { id: "br_devonshire_waltz_andante", name: "Devonshire Waltz Andante", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_devonshire_waltz_andante.ogg" },
  { id: "br_devonshire_waltz_moderato", name: "Devonshire Waltz Moderato", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_devonshire_waltz_moderato.ogg" },
  { id: "br_farm", name: "Farm", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_farm.ogg" },
  { id: "br_disco_lounge", name: "Disco Lounge", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_disco_lounge.ogg" },
  { id: "br_fresh_air", name: "Fresh Air", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_fresh_air.ogg" },
  { id: "br_fireflies_and_stardust", name: "Fireflies and Stardust", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_fireflies_and_stardust.ogg" },
  { id: "br_grand_dark_waltz_allegro", name: "Grand Dark Waltz Allegro", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_grand_dark_waltz_allegro.ogg" },
  { id: "br_almost_bliss", name: "Almost Bliss", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_almost_bliss.ogg" },
  { id: "br_immersed", name: "Immersed", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_immersed.ogg" },
  { id: "br_joey_s_formal_waltz_unscente", name: "Joey's Formal Waltz - Unscented", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_joey_s_formal_waltz_unscente.ogg" },
  { id: "br_jellyfish_in_space", name: "Jellyfish in Space", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_jellyfish_in_space.ogg" },
  { id: "br_kalimba_relaxation_music", name: "Kalimba Relaxation Music", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_kalimba_relaxation_music.ogg" },
  { id: "br_late_night_radio", name: "Late Night Radio", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_late_night_radio.ogg" },
  { id: "br_lotus", name: "Lotus", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_lotus.ogg" },
  { id: "br_ascending_the_vale", name: "Ascending the Vale", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ascending_the_vale.ogg" },
  { id: "br_sincerely", name: "Sincerely", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_sincerely.ogg" },
  { id: "br_grand_dark_waltz_allegretto", name: "Grand Dark Waltz Allegretto", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_grand_dark_waltz_allegretto.ogg" },
  { id: "br_moonstone", name: "Moonstone", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_moonstone.ogg" },
  { id: "br_music_for_funeral_home_part_", name: "Music for Funeral Home - Part 11", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_music_for_funeral_home_part_.ogg" },
  { id: "br_ossuary_2_turn", name: "Ossuary 2 - Turn", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ossuary_2_turn.ogg" },
  { id: "br_parting_of_the_ways_part_2", name: "Parting of the Ways - Part 2", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_parting_of_the_ways_part_2.ogg" },
  { id: "br_eternal_hope", name: "Eternal Hope", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_eternal_hope.ogg" },
  { id: "br_mana_two_part_2", name: "Mana Two - Part 2", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_mana_two_part_2.ogg" },
  { id: "br_port_horizon", name: "Port Horizon", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_port_horizon.ogg" },
  { id: "br_silver_blue_light", name: "Silver Blue Light", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_silver_blue_light.ogg" },
  { id: "br_northern_glade", name: "Northern Glade", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_northern_glade.ogg" },
  { id: "br_space_1990", name: "Space 1990", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_space_1990.ogg" },
  { id: "br_ghost_story", name: "Ghost Story", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ghost_story.ogg" },
  { id: "br_string_impromptu_number_1", name: "String Impromptu Number 1", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_string_impromptu_number_1.ogg" },
  { id: "br_overheat", name: "Overheat", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_overheat.ogg" },
  { id: "br_tenebrous_brothers_carnival_", name: "Tenebrous Brothers Carnival - Mermaid", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_tenebrous_brothers_carnival_.ogg" },
  { id: "br_starting_out_waltz_allegrett", name: "Starting Out Waltz Allegretto", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_starting_out_waltz_allegrett.ogg" },
  { id: "br_eastminster", name: "Eastminster", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_eastminster.ogg" },
  { id: "br_ultralounge", name: "Ultralounge", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ultralounge.ogg" },
  { id: "br_universal", name: "Universal", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_universal.ogg" },
  { id: "br_wet_riffs", name: "Wet Riffs", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_wet_riffs.ogg" },
  { id: "br_comfortable_mystery", name: "Comfortable Mystery", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_comfortable_mystery.ogg" },
  { id: "br_thunderbird", name: "Thunderbird", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_thunderbird.ogg" },
  { id: "br_wholesome", name: "Wholesome", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_wholesome.ogg" },
  { id: "br_ossuary_5_rest", name: "Ossuary 5 - Rest", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ossuary_5_rest.ogg" },
  { id: "br_soporific", name: "Soporific", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_soporific.ogg" },
  { id: "br_mana_two_part_1", name: "Mana Two - Part 1", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_mana_two_part_1.ogg" },
  { id: "br_danse_morialta", name: "Danse Morialta", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_danse_morialta.ogg" },
  { id: "br_manor", name: "Manor", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_manor.ogg" },
  { id: "br_sunshine_version_2", name: "Sunshine (version 2)", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_sunshine_version_2.ogg" },
  { id: "br_study_and_relax", name: "Study And Relax", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_study_and_relax.ogg" },
  { id: "br_for_originz", name: "For Originz", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_for_originz.ogg" },
  { id: "br_opium", name: "Opium", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_opium.ogg" },
  { id: "br_cottages", name: "Cottages", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_cottages.ogg" },
  { id: "br_rainbows", name: "Rainbows", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_rainbows.ogg" },
  { id: "br_vibing_over_venus", name: "Vibing Over Venus", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_vibing_over_venus.ogg" },
  { id: "br_suave_standpipe", name: "Suave Standpipe", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_suave_standpipe.ogg" },
  { id: "br_cool_vibes", name: "Cool Vibes", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_cool_vibes.ogg" },
  { id: "br_night_in_venice", name: "Night in Venice", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_night_in_venice.ogg" },
  { id: "br_teller_of_the_tales", name: "Teller of the Tales", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_teller_of_the_tales.ogg" },
  { id: "br_friday_morning", name: "Friday Morning", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_friday_morning.ogg" },
  { id: "br_ether_vox", name: "Ether Vox", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_ether_vox.ogg" },
  { id: "br_smooth_lovin", name: "Smooth Lovin", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_smooth_lovin.ogg" },
  { id: "br_zigzag", name: "ZigZag", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_zigzag.ogg" },
  { id: "br_groove_grove", name: "Groove Grove", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_groove_grove.ogg" },
  { id: "br_dreamer", name: "Dreamer", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_dreamer.ogg" },
  { id: "br_bittersweet", name: "Bittersweet", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_bittersweet.ogg" },
  { id: "br_past_sadness", name: "Past Sadness", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_past_sadness.ogg" },
  { id: "br_sunshine", name: "Sunshine", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_sunshine.ogg" },
  { id: "br_impact_prelude", name: "Impact Prelude", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_impact_prelude.ogg" },
  { id: "br_calmant", name: "Calmant", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_calmant.ogg" },
  { id: "br_daybreak", name: "Daybreak", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_daybreak.ogg" },
  { id: "br_starry", name: "Starry", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_starry.ogg" },
  { id: "br_long_time_coming", name: "Long Time Coming", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_long_time_coming.ogg" },
  { id: "br_clenched_teeth", name: "Clenched Teeth", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_clenched_teeth.ogg" },
  { id: "br_porch_swing_days_slower", name: "Porch Swing Days - slower", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_porch_swing_days_slower.ogg" },
  { id: "br_ujangong_mix", name: "Ujangong Mix", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_ujangong_mix.ogg" },
  { id: "br_variation_on_egmont", name: "Variation on Egmont", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_variation_on_egmont.ogg" },
  { id: "br_exotics", name: "Exotics", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_exotics.ogg" },
  { id: "br_summer_day", name: "Summer Day", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_summer_day.ogg" },
  { id: "br_stormfront", name: "Stormfront", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_stormfront.ogg" },
  { id: "br_the_complex", name: "The Complex", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_the_complex.ogg" },
  { id: "br_dream_culture", name: "Dream Culture", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_dream_culture.ogg" },
  { id: "br_reawakening", name: "Reawakening", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_reawakening.ogg" },
  { id: "br_at_launch", name: "At Launch", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_at_launch.ogg" },
  { id: "br_minima", name: "Minima", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_minima.ogg" },
  { id: "br_black_vortex", name: "Black Vortex", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_black_vortex.ogg" },
  { id: "br_the_cannery", name: "The Cannery", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_the_cannery.ogg" },
  { id: "br_five_armies", name: "Five Armies", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_five_armies.ogg" },
  { id: "br_full_on", name: "Full On", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_full_on.ogg" },
  { id: "br_industrial_revolution", name: "Industrial Revolution", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_industrial_revolution.ogg" },
  { id: "br_movement_proposition", name: "Movement Proposition", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_movement_proposition.ogg" },
  { id: "br_facile", name: "Facile", category: "music", world: "blight", icon: "fog", mood: "relaxing", file: M + "br_facile.ogg" },
  { id: "br_mistake_the_getaway", name: "Mistake the Getaway", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_mistake_the_getaway.ogg" },
  { id: "br_failing_defense", name: "Failing Defense", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_failing_defense.ogg" },
  { id: "br_exciting_trailer", name: "Exciting Trailer", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_exciting_trailer.ogg" },
  { id: "br_exotic_battle", name: "Exotic Battle", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_exotic_battle.ogg" },
  { id: "br_dangerous", name: "Dangerous", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_dangerous.ogg" },
  { id: "br_mechanolith", name: "Mechanolith", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_mechanolith.ogg" },
  { id: "br_grave_blow", name: "Grave Blow", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_grave_blow.ogg" },
  { id: "br_in_a_heartbeat", name: "In a Heartbeat", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_in_a_heartbeat.ogg" },
  { id: "br_latin_industries", name: "Latin Industries", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_latin_industries.ogg" },
  { id: "br_pixelland", name: "Pixelland", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_pixelland.ogg" },
  { id: "br_chee_zee_lab", name: "Chee Zee Lab", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_chee_zee_lab.ogg" },
  { id: "br_noise_attack", name: "Noise Attack", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_noise_attack.ogg" },
  { id: "br_colossus", name: "Colossus", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_colossus.ogg" },
  { id: "br_the_lift", name: "The Lift", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_the_lift.ogg" },
  { id: "br_unlight", name: "Unlight", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_unlight.ogg" },
  { id: "br_robobozo", name: "Robobozo", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_robobozo.ogg" },
  { id: "br_controlled_chaos", name: "Controlled Chaos", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_controlled_chaos.ogg" },
  { id: "br_corruption", name: "Corruption", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_corruption.ogg" },
  { id: "br_danse_macabre", name: "Danse Macabre", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_danse_macabre.ogg" },
  { id: "br_final_battle_of_the_dark_wiz", name: "Final Battle of the Dark Wizards", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_final_battle_of_the_dark_wiz.ogg" },
  { id: "br_killers", name: "Killers", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_killers.ogg" },
  { id: "br_all_this", name: "All This", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_all_this.ogg" },
  { id: "br_ibn_al_noor", name: "Ibn Al-Noor", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_ibn_al_noor.ogg" },
  { id: "br_blown_away_no_percussion", name: "Blown Away - No Percussion", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_blown_away_no_percussion.ogg" },
  { id: "br_noble_race", name: "Noble Race", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_noble_race.ogg" },
  { id: "br_arcane", name: "Arcane", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_arcane.ogg" },
  { id: "br_future_gladiator", name: "Future Gladiator", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_future_gladiator.ogg" },
  { id: "br_griphop", name: "Griphop", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_griphop.ogg" },
  { id: "br_interloper", name: "Interloper", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_interloper.ogg" },
  { id: "br_organic_grunge", name: "Organic Grunge", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_organic_grunge.ogg" },
  { id: "br_undaunted", name: "Undaunted", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_undaunted.ogg" },
  { id: "br_evening_of_chaos", name: "Evening of Chaos", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_evening_of_chaos.ogg" },
  { id: "br_retrofuture_dirty", name: "RetroFuture Dirty", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_retrofuture_dirty.ogg" },
  { id: "br_hitman", name: "Hitman", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_hitman.ogg" },
  { id: "br_blue_scorpion", name: "Blue Scorpion", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_blue_scorpion.ogg" },
  { id: "br_the_descent", name: "The Descent", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_the_descent.ogg" },
  { id: "br_lagoa_v2", name: "Lagoa v2", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_lagoa_v2.ogg" },
  { id: "br_the_whip_extended_version", name: "The Whip (Extended Version)", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_the_whip_extended_version.ogg" },
  { id: "br_basic_implosion", name: "Basic Implosion", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_basic_implosion.ogg" },
  { id: "br_junkyard_tribe", name: "Junkyard Tribe", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_junkyard_tribe.ogg" },
  { id: "br_rynos_theme", name: "Rynos Theme", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_rynos_theme.ogg" },
  { id: "br_ignosi", name: "Ignosi", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_ignosi.ogg" },
  { id: "br_mta", name: "MTA", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_mta.ogg" },
  { id: "br_dark_times", name: "Dark Times", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_dark_times.ogg" },
  { id: "br_spy_groove", name: "Spy Groove", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_spy_groove.ogg" },
  { id: "br_tenebrous_brothers_carnival__2", name: "Tenebrous Brothers Carnival - Intermission", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_tenebrous_brothers_carnival__2.ogg" },
  { id: "br_darkness_is_coming", name: "Darkness is Coming", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_darkness_is_coming.ogg" },
  { id: "br_nerves", name: "Nerves", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_nerves.ogg" },
  { id: "br_cut_and_run", name: "Cut and Run", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_cut_and_run.ogg" },
  { id: "br_big_mojo", name: "Big Mojo", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_big_mojo.ogg" },
  { id: "br_impending_boom", name: "Impending Boom", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_impending_boom.ogg" },
  { id: "br_cephalopod", name: "Cephalopod", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_cephalopod.ogg" },
  { id: "br_volatile_reaction", name: "Volatile Reaction", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_volatile_reaction.ogg" },
  { id: "br_long_road_ahead", name: "Long Road Ahead", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_long_road_ahead.ogg" },
  { id: "br_rising", name: "Rising", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_rising.ogg" },
  { id: "br_chase", name: "Chase", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_chase.ogg" },
  { id: "br_go_cart_drop_mix", name: "Go Cart - Drop Mix", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_go_cart_drop_mix.ogg" },
  { id: "br_ghostpocalypse_7_master", name: "Ghostpocalypse - 7 Master", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_ghostpocalypse_7_master.ogg" },
  { id: "br_hall_of_the_mountain_king", name: "Hall of the Mountain King", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_hall_of_the_mountain_king.ogg" },
  { id: "br_rising_game", name: "Rising Game", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_rising_game.ogg" },
  { id: "br_rocket", name: "Rocket", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_rocket.ogg" },
  { id: "br_ropocolypse_2", name: "Ropocolypse 2", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_ropocolypse_2.ogg" },
  { id: "br_stoneworld_battle", name: "Stoneworld Battle", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_stoneworld_battle.ogg" },
  { id: "br_egmont_overture_finale", name: "Egmont Overture Finale", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_egmont_overture_finale.ogg" },
  { id: "br_for_the_fallen", name: "For the Fallen", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_for_the_fallen.ogg" },
  { id: "br_constance", name: "Constance", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_constance.ogg" },
  { id: "br_serpentine_trek", name: "Serpentine Trek", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_serpentine_trek.ogg" },
  { id: "br_curse_of_the_scarab", name: "Curse of the Scarab", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_curse_of_the_scarab.ogg" },
  { id: "br_militaire_electronic", name: "Militaire Electronic", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_militaire_electronic.ogg" },
  { id: "br_truth_of_the_legend", name: "Truth of the Legend", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_truth_of_the_legend.ogg" },
  { id: "br_pop_goes_the_weasel", name: "Pop Goes the Weasel", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_pop_goes_the_weasel.ogg" },
  { id: "br_feral_chase", name: "Feral Chase", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_feral_chase.ogg" },
  { id: "br_constancy_part_one", name: "Constancy Part One", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_constancy_part_one.ogg" },
  { id: "br_constancy_part_two", name: "Constancy Part Two", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_constancy_part_two.ogg" },
  { id: "br_achilles", name: "Achilles", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_achilles.ogg" },
  { id: "br_alchemists_tower", name: "Alchemists Tower", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_alchemists_tower.ogg" },
  { id: "br_psychedelic_crater", name: "Psychedelic Crater", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_psychedelic_crater.ogg" },
  { id: "br_vortex", name: "Vortex", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_vortex.ogg" },
  { id: "br_go_cart_loop_mix", name: "Go Cart - Loop Mix", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_go_cart_loop_mix.ogg" },
  { id: "br_cut_and_dry", name: "Cut and Dry", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_cut_and_dry.ogg" },
  { id: "br_machinations", name: "Machinations", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_machinations.ogg" },
  { id: "br_tectonic", name: "Tectonic", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_tectonic.ogg" },
  { id: "br_urban_gauntlet", name: "Urban Gauntlet", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_urban_gauntlet.ogg" },
  { id: "br_heavy_heart", name: "Heavy Heart", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_heavy_heart.ogg" },
  { id: "br_scp_x6x_hopes", name: "SCP-x6x (Hopes)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x6x_hopes.ogg" },
  { id: "br_rains_will_fall", name: "Rains Will Fall", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_rains_will_fall.ogg" },
  { id: "br_sad_trio", name: "Sad Trio", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_sad_trio.ogg" },
  { id: "br_wounded", name: "Wounded", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_wounded.ogg" },
  { id: "br_man_down", name: "Man Down", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_man_down.ogg" },
  { id: "br_private_reflection", name: "Private Reflection", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_private_reflection.ogg" },
  { id: "br_send_for_the_horses", name: "Send for the Horses", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_send_for_the_horses.ogg" },
  { id: "br_night_on_the_docks_sax", name: "Night on the Docks - Sax", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_night_on_the_docks_sax.ogg" },
  { id: "br_night_on_the_docks_piano", name: "Night on the Docks - Piano", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_night_on_the_docks_piano.ogg" },
  { id: "br_crusade", name: "Crusade", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_crusade.ogg" },
  { id: "br_loss", name: "Loss", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_loss.ogg" },
  { id: "br_mourning_song", name: "Mourning Song", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_mourning_song.ogg" },
  { id: "br_night_on_the_docks_trumpet", name: "Night on the Docks - Trumpet", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_night_on_the_docks_trumpet.ogg" },
  { id: "br_quinn_s_song_first_night", name: "Quinn's Song: First Night", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_quinn_s_song_first_night.ogg" },
  { id: "br_redletter", name: "Redletter", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_redletter.ogg" },
  { id: "br_scp_x5x_outer_thoughts", name: "SCP-x5x (Outer Thoughts)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x5x_outer_thoughts.ogg" },
  { id: "br_gloom_horizon", name: "Gloom Horizon", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_gloom_horizon.ogg" },
  { id: "br_quinn_s_song_a_new_man", name: "Quinn's Song: A New Man", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_quinn_s_song_a_new_man.ogg" },
  { id: "br_dark_walk", name: "Dark Walk", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_dark_walk.ogg" },
  { id: "br_thunder_dreams", name: "Thunder Dreams", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_thunder_dreams.ogg" },
  { id: "br_devastation_and_revenge", name: "Devastation and Revenge", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_devastation_and_revenge.ogg" },
  { id: "br_final_count", name: "Final Count", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_final_count.ogg" },
  { id: "br_shiny_tech_ii", name: "Shiny Tech II", category: "music", world: "blight", icon: "storm", mood: "brutal", file: M + "br_shiny_tech_ii.ogg" },
  { id: "br_dd_groove", name: "DD Groove", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_dd_groove.ogg" },
  { id: "br_hero_down", name: "Hero Down", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_hero_down.ogg" },
  { id: "br_at_rest", name: "At Rest", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_at_rest.ogg" },
  { id: "br_shadowlands_1_horizon", name: "Shadowlands 1 - Horizon", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_shadowlands_1_horizon.ogg" },
  { id: "br_distant_tension", name: "Distant Tension", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_distant_tension.ogg" },
  { id: "br_despair_and_triumph", name: "Despair and Triumph", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_despair_and_triumph.ogg" },
  { id: "br_touching_moments_four_melody", name: "Touching Moments Four - Melody", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_touching_moments_four_melody.ogg" },
  { id: "br_gypsy_shoegazer", name: "Gypsy Shoegazer", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_gypsy_shoegazer.ogg" },
  { id: "br_relent", name: "Relent", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_relent.ogg" },
  { id: "br_gypsy_shoegazer_no_voices", name: "Gypsy Shoegazer No Voices", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_gypsy_shoegazer_no_voices.ogg" },
  { id: "br_anguish", name: "Anguish", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_anguish.ogg" },
  { id: "br_moorland", name: "Moorland", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_moorland.ogg" },
  { id: "br_dark_fog", name: "Dark Fog", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_dark_fog.ogg" },
  { id: "br_lightless_dawn", name: "Lightless Dawn", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_lightless_dawn.ogg" },
  { id: "br_lost_time", name: "Lost Time", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_lost_time.ogg" },
  { id: "br_just_as_soon", name: "Just As Soon", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_just_as_soon.ogg" },
  { id: "br_phantasm", name: "Phantasm", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_phantasm.ogg" },
  { id: "br_bump_in_the_night", name: "Bump in the Night", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_bump_in_the_night.ogg" },
  { id: "br_majestic_hills", name: "Majestic Hills", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_majestic_hills.ogg" },
  { id: "br_touching_moments_three_deepe", name: "Touching Moments Three - Deeper", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_touching_moments_three_deepe.ogg" },
  { id: "br_oppressive_gloom", name: "Oppressive Gloom", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_oppressive_gloom.ogg" },
  { id: "br_long_note_three", name: "Long Note Three", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_long_note_three.ogg" },
  { id: "br_fantastic_dim_bar", name: "Fantastic Dim Bar", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_fantastic_dim_bar.ogg" },
  { id: "br_myst", name: "Myst", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_myst.ogg" },
  { id: "br_tempting_secrets", name: "Tempting Secrets", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_tempting_secrets.ogg" },
  { id: "br_intrepid", name: "Intrepid", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_intrepid.ogg" },
  { id: "br_martian_cowboy", name: "Martian Cowboy", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_martian_cowboy.ogg" },
  { id: "br_with_the_sea", name: "With the Sea", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_with_the_sea.ogg" },
  { id: "br_promises_to_keep", name: "Promises to Keep", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_promises_to_keep.ogg" },
  { id: "br_bass_walker", name: "Bass Walker", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_bass_walker.ogg" },
  { id: "br_funeral_march_for_brass", name: "Funeral March for Brass", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_funeral_march_for_brass.ogg" },
  { id: "br_death_of_kings", name: "Death of Kings", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_death_of_kings.ogg" },
  { id: "br_sunset_at_glengorm", name: "Sunset at Glengorm", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_sunset_at_glengorm.ogg" },
  { id: "br_sinfonia_number_5", name: "Sinfonia Number 5", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_sinfonia_number_5.ogg" },
  { id: "br_promising_relationship", name: "Promising Relationship", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_promising_relationship.ogg" },
  { id: "br_ghostpocalypse_4_temptress", name: "Ghostpocalypse - 4 Temptress", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_ghostpocalypse_4_temptress.ogg" },
  { id: "br_dreamlike", name: "Dreamlike", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_dreamlike.ogg" },
  { id: "br_earnest", name: "Earnest", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_earnest.ogg" },
  { id: "br_grave_matters", name: "Grave Matters", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_grave_matters.ogg" },
  { id: "br_gnarled_situation", name: "Gnarled Situation", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_gnarled_situation.ogg" },
  { id: "br_past_the_edge", name: "Past the Edge", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_past_the_edge.ogg" },
  { id: "br_time_passes", name: "Time Passes", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_time_passes.ogg" },
  { id: "br_trio_for_piano_violin_and_vi", name: "Trio for Piano Violin and Viola", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_trio_for_piano_violin_and_vi.ogg" },
  { id: "br_reign_supreme", name: "Reign Supreme", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_reign_supreme.ogg" },
  { id: "br_song_of_the_volga_boatmen", name: "Song of the Volga Boatmen", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_song_of_the_volga_boatmen.ogg" },
  { id: "br_night_vigil", name: "Night Vigil", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_night_vigil.ogg" },
  { id: "br_lone_harvest", name: "Lone Harvest", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_lone_harvest.ogg" },
  { id: "br_the_reveal", name: "The Reveal", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_the_reveal.ogg" },
  { id: "br_a_singular_perversion", name: "A Singular Perversion", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_a_singular_perversion.ogg" },
  { id: "br_plaint", name: "Plaint", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_plaint.ogg" },
  { id: "br_lasting_hope", name: "Lasting Hope", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_lasting_hope.ogg" },
  { id: "br_bent_and_broken", name: "Bent and Broken", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_bent_and_broken.ogg" },
  { id: "br_controlled_chaos_no_percussi", name: "Controlled Chaos - no percussion", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_controlled_chaos_no_percussi.ogg" },
  { id: "br_echoes_of_time", name: "Echoes of Time", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_echoes_of_time.ogg" },
  { id: "br_echoes_of_time_v2", name: "Echoes of Time v2", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_echoes_of_time_v2.ogg" },
  { id: "br_giant_wyrm", name: "Giant Wyrm", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_giant_wyrm.ogg" },
  { id: "br_ice_demon", name: "Ice Demon", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_ice_demon.ogg" },
  { id: "br_inner_sanctum", name: "Inner Sanctum", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_inner_sanctum.ogg" },
  { id: "br_land_of_the_dead", name: "Land of the Dead", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_land_of_the_dead.ogg" },
  { id: "br_ritual", name: "Ritual", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_ritual.ogg" },
  { id: "br_heart_of_the_beast", name: "Heart of the Beast", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_heart_of_the_beast.ogg" },
  { id: "br_metaphysik", name: "Metaphysik", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_metaphysik.ogg" },
  { id: "br_penumbra", name: "Penumbra", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_penumbra.ogg" },
  { id: "br_day_of_chaos", name: "Day of Chaos", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_day_of_chaos.ogg" },
  { id: "br_scp_x1x_gateway_to_hell", name: "SCP-x1x (Gateway to Hell)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x1x_gateway_to_hell.ogg" },
  { id: "br_scp_x2x_unseen_presence", name: "SCP-x2x (Unseen Presence)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x2x_unseen_presence.ogg" },
  { id: "br_return_of_lazarus", name: "Return of Lazarus", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_return_of_lazarus.ogg" },
  { id: "br_scp_x3x_i_am_not_ok", name: "SCP-x3x (I am Not OK)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x3x_i_am_not_ok.ogg" },
  { id: "br_symmetry", name: "Symmetry", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_symmetry.ogg" },
  { id: "br_scp_x4x_mind_leech", name: "SCP-x4x (Mind Leech)", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_scp_x4x_mind_leech.ogg" },
  { id: "br_the_voices", name: "The Voices", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_the_voices.ogg" },
  { id: "br_this_house", name: "This House", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_this_house.ogg" },
  { id: "br_decay", name: "Decay", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_decay.ogg" },
  { id: "br_the_hive", name: "The Hive", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_the_hive.ogg" },
  { id: "br_cryptic_sorrow", name: "Cryptic Sorrow", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_cryptic_sorrow.ogg" },
  { id: "br_digital_bark", name: "Digital Bark", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_digital_bark.ogg" },
  { id: "br_gathering_darkness", name: "Gathering Darkness", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_gathering_darkness.ogg" },
  { id: "br_the_escalation", name: "The Escalation", category: "music", world: "blight", icon: "moon", mood: "melancholic", file: M + "br_the_escalation.ogg" },
];
