import { BLIGHT_LAYERS, BLIGHT_SCENES, BLIGHT_MOODS, BLIGHT_BATTLE } from "./blight-catalog.js";
export { BLIGHT_LAYERS, BLIGHT_SCENES, BLIGHT_MOODS, BLIGHT_BATTLE };

export const CATEGORIES = [
  { id: "music", name: "Music" },
  { id: "weather", name: "Weather" },
  { id: "animals", name: "Animals" },
  { id: "ambience", name: "Ambience" },
];

export const MUSIC_MOODS = [
  { id: "merry", name: "Merry" },
  { id: "heroic", name: "Heroic" },
  { id: "battle", name: "Battle" },
  { id: "dark", name: "Dark" },
  { id: "mystery", name: "Mystery" },
  { id: "calm", name: "Calm" },
  { id: "wild", name: "Wild" },
  { id: "sea", name: "Sea" },
  { id: "sacred", name: "Sacred" },
  { id: "travel", name: "Travel" },
];

export const BATTLE_TRACKS = [
  "prelude_action",
  "rising_game",
  "battle_march",
  "clash_defiant",
  "intended_force",
  "relent",
  "stormfront",
  "crowd_hammer",
  "exotic_battle",
  "impact_prelude",
  "night_chaos",
  "volatile_reaction",
  "black_vortex",
  "dragon_wake",
  "giant_wyrm",
  "strength_titans",
  "hall_mountain",
  "future_gladiator",
  "summon_rawk",
];

export const LAYERS = [
  { id: "tavern_jig", name: "Tavern Jig", category: "music", icon: "lute", mood: "merry", file: "audio/music/tavern_jig.ogg" },
  { id: "forest_wander", name: "Forest Wander", category: "music", icon: "trees", mood: "wild", file: "audio/music/forest_wander.ogg" },
  { id: "dungeon_depths", name: "Dungeon Depths", category: "music", icon: "dungeon", mood: "dark", file: "audio/music/dungeon_depths.ogg" },
  { id: "battle_march", name: "Battle March", category: "music", icon: "swords", mood: "battle", file: "audio/music/battle_march.ogg" },
  { id: "sacred_hymn", name: "Sacred Hymn", category: "music", icon: "temple", mood: "sacred", file: "audio/music/sacred_hymn.ogg" },
  { id: "ocean_voyage", name: "Ocean Voyage", category: "music", icon: "wave", mood: "sea", file: "audio/music/ocean_voyage.ogg" },
  { id: "dark_rite", name: "Dark Rite", category: "music", icon: "moon", mood: "dark", file: "audio/music/dark_rite.ogg" },
  { id: "royal_court", name: "Royal Court", category: "music", icon: "crown", mood: "heroic", file: "audio/music/royal_court.ogg" },
  { id: "road_theme", name: "Open Road", category: "music", icon: "path", mood: "travel", file: "audio/music/road_theme.ogg" },
  { id: "elven_glade", name: "Elven Glade", category: "music", icon: "leaf", mood: "calm", file: "audio/music/elven_glade.ogg" },
  { id: "winter_march", name: "Winter March", category: "music", icon: "snow", mood: "travel", file: "audio/music/winter_march.ogg" },
  { id: "dragon_wake", name: "Dragon's Wake", category: "music", icon: "dragon", mood: "battle", file: "audio/music/dragon_wake.ogg" },
  { id: "harvest_dance", name: "Harvest Dance", category: "music", icon: "lute", mood: "merry", file: "audio/music/harvest_dance.ogg" },
  { id: "quiet_work", name: "Quiet Work", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/quiet_work.ogg" },
  { id: "wizards_tower", name: "Wizard's Tower", category: "music", icon: "wizard", mood: "mystery", file: "audio/music/wizards_tower.ogg" },
  { id: "oppressive_gloom", name: "Oppressive Gloom", category: "music", icon: "moon", mood: "dark", file: "audio/music/oppressive_gloom.ogg" },
  { id: "stormfront", name: "Stormfront", category: "music", icon: "storm", mood: "battle", file: "audio/music/stormfront.ogg" },
  { id: "hidden_past", name: "Hidden Past", category: "music", icon: "path", mood: "mystery", file: "audio/music/hidden_past.ogg" },
  { id: "heroic_age", name: "Heroic Age", category: "music", icon: "banner", mood: "heroic", file: "audio/music/heroic_age.ogg" },
  { id: "goblin_road", name: "Goblin Road", category: "music", icon: "mask", mood: "merry", file: "audio/music/goblin_road.ogg" },
  { id: "village_fair", name: "Village Fair", category: "music", icon: "farm", mood: "merry", file: "audio/music/village_fair.ogg" },
  { id: "the_descent", name: "The Descent", category: "music", icon: "dungeon", mood: "dark", file: "audio/music/the_descent.ogg" },
  { id: "the_pyre", name: "The Pyre", category: "music", icon: "fire", mood: "dark", file: "audio/music/the_pyre.ogg" },
  { id: "clash_defiant", name: "Clash Defiant", category: "music", icon: "swords", mood: "battle", file: "audio/music/clash_defiant.ogg" },
  { id: "morgana", name: "Morgana Rides", category: "music", icon: "horse", mood: "travel", file: "audio/music/morgana.ogg" },
  { id: "lost_time", name: "Lost Time", category: "music", icon: "path", mood: "mystery", file: "audio/music/lost_time.ogg" },
  { id: "crusade", name: "Crusade", category: "music", icon: "banner", mood: "heroic", file: "audio/music/crusade.ogg" },
  { id: "darkest_child", name: "Darkest Child", category: "music", icon: "moon", mood: "dark", file: "audio/music/darkest_child.ogg" },
  { id: "ghost_story", name: "Ghost Story", category: "music", icon: "ghost", mood: "dark", file: "audio/music/ghost_story.ogg" },
  { id: "maestro", name: "One-Eyed Maestro", category: "music", icon: "lute", mood: "merry", file: "audio/music/maestro.ogg" },
  { id: "lord_land", name: "Lord of the Land", category: "music", icon: "crown", mood: "heroic", file: "audio/music/lord_land.ogg" },
  { id: "achaidh", name: "Achaidh Cheide", category: "music", icon: "lute", mood: "merry", file: "audio/music/achaidh.ogg" },
  { id: "call_adventure", name: "Call to Adventure", category: "music", icon: "banner", mood: "heroic", file: "audio/music/call_adventure.ogg" },
  { id: "black_vortex", name: "Black Vortex", category: "music", icon: "swords", mood: "battle", file: "audio/music/black_vortex.ogg" },
  { id: "mystery", name: "Comfortable Mystery", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/mystery.ogg" },
  { id: "ossuary", name: "Ossuary Air", category: "music", icon: "tomb", mood: "dark", file: "audio/music/ossuary.ogg" },
  { id: "feral_chase", name: "Feral Chase", category: "music", icon: "wolf", mood: "wild", file: "audio/music/feral_chase.ogg" },
  { id: "at_rest", name: "At Rest", category: "music", icon: "fire", mood: "calm", file: "audio/music/at_rest.ogg" },
  { id: "scarab", name: "Curse of the Scarab", category: "music", icon: "dune", mood: "mystery", file: "audio/music/scarab.ogg" },
  { id: "interloper", name: "Interloper", category: "music", icon: "moon", mood: "mystery", file: "audio/music/interloper.ogg" },
  { id: "pippin", name: "Pippin's Tune", category: "music", icon: "lute", mood: "merry", file: "audio/music/pippin.ogg" },
  { id: "darkling", name: "Darkling", category: "music", icon: "ghost", mood: "dark", file: "audio/music/darkling.ogg" },
  { id: "moorland", name: "Moorland", category: "music", icon: "fog", mood: "wild", file: "audio/music/moorland.ogg" },
  { id: "ritual_song", name: "Ritual", category: "music", icon: "spark", mood: "dark", file: "audio/music/ritual_song.ogg" },
  { id: "blue_feather", name: "Blue Feather", category: "music", icon: "leaf", mood: "calm", file: "audio/music/blue_feather.ogg" },
  { id: "chamber", name: "The Chamber", category: "music", icon: "dungeon", mood: "mystery", file: "audio/music/chamber.ogg" },
  { id: "water_prelude", name: "Water Prelude", category: "music", icon: "wave", mood: "sea", file: "audio/music/water_prelude.ogg" },
  { id: "floating_cities", name: "Floating Cities", category: "music", icon: "fish", mood: "sea", file: "audio/music/floating_cities.ogg" },
  { id: "with_the_sea", name: "With the Sea", category: "music", icon: "wave", mood: "sea", file: "audio/music/with_the_sea.ogg" },
  { id: "shores_avalon", name: "Shores of Avalon", category: "music", icon: "wave", mood: "sea", file: "audio/music/shores_avalon.ogg" },
  { id: "crowd_hammer", name: "Crowd Hammer", category: "music", icon: "anvil", mood: "battle", file: "audio/music/crowd_hammer.ogg" },
  { id: "exotic_battle", name: "Exotic Battle", category: "music", icon: "swords", mood: "battle", file: "audio/music/exotic_battle.ogg" },
  { id: "future_gladiator", name: "Future Gladiator", category: "music", icon: "swords", mood: "battle", file: "audio/music/future_gladiator.ogg" },
  { id: "giant_wyrm", name: "Giant Wyrm", category: "music", icon: "dragon", mood: "battle", file: "audio/music/giant_wyrm.ogg" },
  { id: "hall_mountain", name: "Hall of the Mountain King", category: "music", icon: "mountain", mood: "battle", file: "audio/music/hall_mountain.ogg" },
  { id: "impact_prelude", name: "Impact Prelude", category: "music", icon: "storm", mood: "battle", file: "audio/music/impact_prelude.ogg" },
  { id: "intended_force", name: "Intended Force", category: "music", icon: "swords", mood: "battle", file: "audio/music/intended_force.ogg" },
  { id: "night_chaos", name: "Night of Chaos", category: "music", icon: "storm", mood: "battle", file: "audio/music/night_chaos.ogg" },
  { id: "prelude_action", name: "Prelude and Action", category: "music", icon: "swords", mood: "battle", file: "audio/music/prelude_action.ogg" },
  { id: "relent", name: "Relent", category: "music", icon: "swords", mood: "battle", file: "audio/music/relent.ogg" },
  { id: "rising_game", name: "Rising Game", category: "music", icon: "swords", mood: "battle", file: "audio/music/rising_game.ogg" },
  { id: "strength_titans", name: "Strength of the Titans", category: "music", icon: "swords", mood: "battle", file: "audio/music/strength_titans.ogg" },
  { id: "summon_rawk", name: "Summon the Rawk", category: "music", icon: "storm", mood: "battle", file: "audio/music/summon_rawk.ogg" },
  { id: "volatile_reaction", name: "Volatile Reaction", category: "music", icon: "storm", mood: "battle", file: "audio/music/volatile_reaction.ogg" },
  { id: "air_prelude", name: "Air Prelude", category: "music", icon: "wind", mood: "calm", file: "audio/music/air_prelude.ogg" },
  { id: "almost_in_f", name: "Almost in F", category: "music", icon: "lute", mood: "calm", file: "audio/music/almost_in_f.ogg" },
  { id: "bittersweet", name: "Bittersweet", category: "music", icon: "leaf", mood: "calm", file: "audio/music/bittersweet.ogg" },
  { id: "daybreak", name: "Daybreak", category: "music", icon: "dawn", mood: "calm", file: "audio/music/daybreak.ogg" },
  { id: "dream_culture", name: "Dream Culture", category: "music", icon: "spark", mood: "calm", file: "audio/music/dream_culture.ogg" },
  { id: "dreamy_flashback", name: "Dreamy Flashback", category: "music", icon: "spark", mood: "calm", file: "audio/music/dreamy_flashback.ogg" },
  { id: "fluidscape", name: "Fluidscape", category: "music", icon: "wave", mood: "calm", file: "audio/music/fluidscape.ogg" },
  { id: "garden_music", name: "Garden Music", category: "music", icon: "leaf", mood: "calm", file: "audio/music/garden_music.ogg" },
  { id: "gymnopedie", name: "Gymnopedie", category: "music", icon: "lute", mood: "calm", file: "audio/music/gymnopedie.ogg" },
  { id: "heart_nowhere", name: "Heart of Nowhere", category: "music", icon: "path", mood: "calm", file: "audio/music/heart_nowhere.ogg" },
  { id: "heartbreaking", name: "Heartbreaking", category: "music", icon: "lute", mood: "calm", file: "audio/music/heartbreaking.ogg" },
  { id: "ice_flow", name: "Ice Flow", category: "music", icon: "snow", mood: "calm", file: "audio/music/ice_flow.ogg" },
  { id: "long_note_four", name: "Long Note Four", category: "music", icon: "fog", mood: "calm", file: "audio/music/long_note_four.ogg" },
  { id: "luminous_rain", name: "Luminous Rain", category: "music", icon: "rain", mood: "calm", file: "audio/music/luminous_rain.ogg" },
  { id: "meditation_01", name: "Meditation", category: "music", icon: "leaf", mood: "calm", file: "audio/music/meditation_01.ogg" },
  { id: "minima", name: "Minima", category: "music", icon: "fog", mood: "calm", file: "audio/music/minima.ogg" },
  { id: "nightdreams", name: "Nightdreams", category: "music", icon: "moon", mood: "calm", file: "audio/music/nightdreams.ogg" },
  { id: "peaceful_desolation", name: "Peaceful Desolation", category: "music", icon: "fog", mood: "calm", file: "audio/music/peaceful_desolation.ogg" },
  { id: "plaint", name: "Plaint", category: "music", icon: "lute", mood: "calm", file: "audio/music/plaint.ogg" },
  { id: "private_reflection", name: "Private Reflection", category: "music", icon: "book", mood: "calm", file: "audio/music/private_reflection.ogg" },
  { id: "river_flute", name: "River Flute", category: "music", icon: "river", mood: "calm", file: "audio/music/river_flute.ogg" },
  { id: "sad_trio", name: "Sad Trio", category: "music", icon: "lute", mood: "calm", file: "audio/music/sad_trio.ogg" },
  { id: "string_impromptu", name: "String Impromptu", category: "music", icon: "lute", mood: "calm", file: "audio/music/string_impromptu.ogg" },
  { id: "snow_queen", name: "The Snow Queen", category: "music", icon: "snow", mood: "calm", file: "audio/music/snow_queen.ogg" },
  { id: "unpromised", name: "Unpromised", category: "music", icon: "fog", mood: "calm", file: "audio/music/unpromised.ogg" },
  { id: "wounded", name: "Wounded", category: "music", icon: "moon", mood: "calm", file: "audio/music/wounded.ogg" },
  { id: "classic_horror", name: "Classic Horror", category: "music", icon: "ghost", mood: "dark", file: "audio/music/classic_horror.ogg" },
  { id: "danse_macabre", name: "Danse Macabre", category: "music", icon: "ghost", mood: "dark", file: "audio/music/danse_macabre.ogg" },
  { id: "dark_walk", name: "Dark Walk", category: "music", icon: "moon", mood: "dark", file: "audio/music/dark_walk.ogg" },
  { id: "decline", name: "Decline", category: "music", icon: "tomb", mood: "dark", file: "audio/music/decline.ogg" },
  { id: "gathering_darkness", name: "Gathering Darkness", category: "music", icon: "moon", mood: "dark", file: "audio/music/gathering_darkness.ogg" },
  { id: "ghost_processional", name: "Ghost Processional", category: "music", icon: "ghost", mood: "dark", file: "audio/music/ghost_processional.ogg" },
  { id: "ghostpocalypse", name: "Ghostpocalypse", category: "music", icon: "ghost", mood: "dark", file: "audio/music/ghostpocalypse.ogg" },
  { id: "heavy_interlude", name: "Heavy Interlude", category: "music", icon: "dungeon", mood: "dark", file: "audio/music/heavy_interlude.ogg" },
  { id: "hero_down", name: "Hero Down", category: "music", icon: "banner", mood: "dark", file: "audio/music/hero_down.ogg" },
  { id: "lightless_dawn", name: "Lightless Dawn", category: "music", icon: "moon", mood: "dark", file: "audio/music/lightless_dawn.ogg" },
  { id: "malicious", name: "Malicious", category: "music", icon: "mask", mood: "dark", file: "audio/music/malicious.ogg" },
  { id: "ossuary_rest", name: "Ossuary Rest", category: "music", icon: "tomb", mood: "dark", file: "audio/music/ossuary_rest.ogg" },
  { id: "ossuary_turn", name: "Ossuary Turn", category: "music", icon: "tomb", mood: "dark", file: "audio/music/ossuary_turn.ogg" },
  { id: "supernatural", name: "Supernatural", category: "music", icon: "spark", mood: "dark", file: "audio/music/supernatural.ogg" },
  { id: "unlight", name: "Unlight", category: "music", icon: "moon", mood: "dark", file: "audio/music/unlight.ogg" },
  { id: "unseen_horrors", name: "Unseen Horrors", category: "music", icon: "ghost", mood: "dark", file: "audio/music/unseen_horrors.ogg" },
  { id: "destiny_day", name: "Destiny Day", category: "music", icon: "sun", mood: "heroic", file: "audio/music/destiny_day.ogg" },
  { id: "for_originz", name: "For Originz", category: "music", icon: "banner", mood: "heroic", file: "audio/music/for_originz.ogg" },
  { id: "how_it_begins", name: "How it Begins", category: "music", icon: "banner", mood: "heroic", file: "audio/music/how_it_begins.ogg" },
  { id: "inspired", name: "Inspired", category: "music", icon: "banner", mood: "heroic", file: "audio/music/inspired.ogg" },
  { id: "lasting_hope", name: "Lasting Hope", category: "music", icon: "banner", mood: "heroic", file: "audio/music/lasting_hope.ogg" },
  { id: "royal_coupling", name: "Royal Coupling", category: "music", icon: "crown", mood: "heroic", file: "audio/music/royal_coupling.ogg" },
  { id: "thunderbird", name: "Thunderbird", category: "music", icon: "eagle", mood: "heroic", file: "audio/music/thunderbird.ogg" },
  { id: "truth_legend", name: "Truth of the Legend", category: "music", icon: "crown", mood: "heroic", file: "audio/music/truth_legend.ogg" },
  { id: "undaunted", name: "Undaunted", category: "music", icon: "banner", mood: "heroic", file: "audio/music/undaunted.ogg" },
  { id: "minstrel_dance", name: "Dances and Dames", category: "music", icon: "lute", mood: "merry", file: "audio/music/minstrel_dance.ogg" },
  { id: "fluffing_duck", name: "Fluffing a Duck", category: "music", icon: "bird", mood: "merry", file: "audio/music/fluffing_duck.ogg" },
  { id: "happy_alley", name: "Happy Alley", category: "music", icon: "farm", mood: "merry", file: "audio/music/happy_alley.ogg" },
  { id: "master_feast", name: "Master of the Feast", category: "music", icon: "lute", mood: "merry", file: "audio/music/master_feast.ogg" },
  { id: "run_amok", name: "Run Amok", category: "music", icon: "lute", mood: "merry", file: "audio/music/run_amok.ogg" },
  { id: "super_polka", name: "Super Polka", category: "music", icon: "lute", mood: "merry", file: "audio/music/super_polka.ogg" },
  { id: "village_consort", name: "Village Consort", category: "music", icon: "farm", mood: "merry", file: "audio/music/village_consort.ogg" },
  { id: "wholesome", name: "Wholesome", category: "music", icon: "farm", mood: "merry", file: "audio/music/wholesome.ogg" },
  { id: "anamalie", name: "Anamalie", category: "music", icon: "fog", mood: "mystery", file: "audio/music/anamalie.ogg" },
  { id: "colorless_aura", name: "Colorless Aura", category: "music", icon: "fog", mood: "mystery", file: "audio/music/colorless_aura.ogg" },
  { id: "mystery_2", name: "Comfortable Mystery II", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/mystery_2.ogg" },
  { id: "crypto", name: "Crypto", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/crypto.ogg" },
  { id: "deep_haze", name: "Deep Haze", category: "music", icon: "fog", mood: "mystery", file: "audio/music/deep_haze.ogg" },
  { id: "deliberate_thought", name: "Deliberate Thought", category: "music", icon: "book", mood: "mystery", file: "audio/music/deliberate_thought.ogg" },
  { id: "echoes_time", name: "Echoes of Time", category: "music", icon: "clock", mood: "mystery", file: "audio/music/echoes_time.ogg" },
  { id: "ether_vox", name: "Ether Vox", category: "music", icon: "wizard", mood: "mystery", file: "audio/music/ether_vox.ogg" },
  { id: "frozen_star", name: "Frozen Star", category: "music", icon: "snow", mood: "mystery", file: "audio/music/frozen_star.ogg" },
  { id: "hidden_agenda", name: "Hidden Agenda", category: "music", icon: "mask", mood: "mystery", file: "audio/music/hidden_agenda.ogg" },
  { id: "hiding_reality", name: "Hiding Your Reality", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/hiding_reality.ogg" },
  { id: "hitman", name: "Hitman", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/hitman.ogg" },
  { id: "magistar", name: "Magistar", category: "music", icon: "wizard", mood: "mystery", file: "audio/music/magistar.ogg" },
  { id: "mystic_force", name: "Mystic Force", category: "music", icon: "wizard", mood: "mystery", file: "audio/music/mystic_force.ogg" },
  { id: "past_the_edge", name: "Past the Edge", category: "music", icon: "path", mood: "mystery", file: "audio/music/past_the_edge.ogg" },
  { id: "spy_glass", name: "Spy Glass", category: "music", icon: "sneak", mood: "mystery", file: "audio/music/spy_glass.ogg" },
  { id: "tempting_secrets", name: "Tempting Secrets", category: "music", icon: "mask", mood: "mystery", file: "audio/music/tempting_secrets.ogg" },
  { id: "the_complex", name: "The Complex", category: "music", icon: "dungeon", mood: "mystery", file: "audio/music/the_complex.ogg" },
  { id: "other_side", name: "The Other Side of the Door", category: "music", icon: "dungeon", mood: "mystery", file: "audio/music/other_side.ogg" },
  { id: "this_house", name: "This House", category: "music", icon: "dungeon", mood: "mystery", file: "audio/music/this_house.ogg" },
  { id: "vanishing", name: "Vanishing", category: "music", icon: "fog", mood: "mystery", file: "audio/music/vanishing.ogg" },
  { id: "agnus_dei", name: "Agnus Dei", category: "music", icon: "bell", mood: "sacred", file: "audio/music/agnus_dei.ogg" },
  { id: "angevin_b", name: "Angevin B", category: "music", icon: "temple", mood: "sacred", file: "audio/music/angevin_b.ogg" },
  { id: "rite_of_passage", name: "Rite of Passage", category: "music", icon: "spark", mood: "sacred", file: "audio/music/rite_of_passage.ogg" },
  { id: "silver_flame", name: "Silver Flame", category: "music", icon: "fire", mood: "sacred", file: "audio/music/silver_flame.ogg" },
  { id: "virtutes_instrumenti", name: "Virtutes Instrumenti", category: "music", icon: "temple", mood: "sacred", file: "audio/music/virtutes_instrumenti.ogg" },
  { id: "virtutes_vocis", name: "Virtutes Vocis", category: "music", icon: "temple", mood: "sacred", file: "audio/music/virtutes_vocis.ogg" },
  { id: "immersed", name: "Immersed", category: "music", icon: "fish", mood: "sea", file: "audio/music/immersed.ogg" },
  { id: "acralate", name: "Accralate", category: "music", icon: "path", mood: "travel", file: "audio/music/acralate.ogg" },
  { id: "arid_foothills", name: "Arid Foothills", category: "music", icon: "dune", mood: "travel", file: "audio/music/arid_foothills.ogg" },
  { id: "bit_quest", name: "Bit Quest", category: "music", icon: "path", mood: "travel", file: "audio/music/bit_quest.ogg" },
  { id: "crossing_chasm", name: "Crossing the Chasm", category: "music", icon: "mountain", mood: "travel", file: "audio/music/crossing_chasm.ogg" },
  { id: "desert_city", name: "Desert City", category: "music", icon: "dune", mood: "travel", file: "audio/music/desert_city.ogg" },
  { id: "finding_movement", name: "Finding Movement", category: "music", icon: "path", mood: "travel", file: "audio/music/finding_movement.ogg" },
  { id: "jalandhar", name: "Jalandhar", category: "music", icon: "path", mood: "travel", file: "audio/music/jalandhar.ogg" },
  { id: "lone_harvest", name: "Lone Harvest", category: "music", icon: "farm", mood: "travel", file: "audio/music/lone_harvest.ogg" },
  { id: "lost_frontier", name: "Lost Frontier", category: "music", icon: "path", mood: "travel", file: "audio/music/lost_frontier.ogg" },
  { id: "nowhere_land", name: "Nowhere Land", category: "music", icon: "fog", mood: "travel", file: "audio/music/nowhere_land.ogg" },
  { id: "on_my_way", name: "On My Way", category: "music", icon: "path", mood: "travel", file: "audio/music/on_my_way.ogg" },
  { id: "overworld", name: "Overworld", category: "music", icon: "path", mood: "travel", file: "audio/music/overworld.ogg" },
  { id: "tabuk", name: "Tabuk", category: "music", icon: "dune", mood: "travel", file: "audio/music/tabuk.ogg" },
  { id: "take_a_chance", name: "Take a Chance", category: "music", icon: "path", mood: "travel", file: "audio/music/take_a_chance.ogg" },
  { id: "the_builder", name: "The Builder", category: "music", icon: "anvil", mood: "travel", file: "audio/music/the_builder.ogg" },
  { id: "to_the_ends", name: "To the Ends", category: "music", icon: "path", mood: "travel", file: "audio/music/to_the_ends.ogg" },
  { id: "wagon_wheel", name: "Wagon Wheel", category: "music", icon: "horse", mood: "travel", file: "audio/music/wagon_wheel.ogg" },
  { id: "earth_prelude", name: "Earth Prelude", category: "music", icon: "mountain", mood: "wild", file: "audio/music/earth_prelude.ogg" },
  { id: "firesong", name: "Firesong", category: "music", icon: "fire", mood: "wild", file: "audio/music/firesong.ogg" },
  { id: "river_fire", name: "River Fire", category: "music", icon: "fire", mood: "wild", file: "audio/music/river_fire.ogg" },

  { id: "rain", name: "Rain", category: "weather", icon: "rain", file: "audio/weather/rain.ogg" },
  { id: "downpour", name: "Downpour", category: "weather", icon: "storm", file: "audio/weather/downpour.ogg" },
  { id: "wind", name: "Wind", category: "weather", icon: "wind", file: "audio/weather/wind.ogg" },
  { id: "blizzard", name: "Blizzard", category: "weather", icon: "snow", file: "audio/weather/blizzard.ogg" },
  { id: "distant_storm", name: "Distant Storm", category: "weather", icon: "cloud", file: "audio/weather/distant_storm.ogg" },
  {
    id: "thunder",
    name: "Thunder",
    category: "weather",
    icon: "bolt",
    type: "scatter",
    files: [
      "audio/oneshots/thunder_1.ogg",
      "audio/oneshots/thunder_2.ogg",
      "audio/oneshots/thunder_3.ogg",
      "audio/oneshots/thunder_4.ogg",
      "audio/oneshots/thunder_5.ogg",
      "audio/oneshots/thunder_6.ogg",
    ],
    minGap: 6,
    maxGap: 16,
  },
  { id: "drizzle", name: "Drizzle", category: "weather", icon: "drop", file: "audio/weather/drizzle.ogg" },
  { id: "hail", name: "Hail", category: "weather", icon: "hail", file: "audio/weather/hail.ogg" },
  { id: "fog", name: "Fog", category: "weather", icon: "fog", file: "audio/weather/fog.ogg" },
  { id: "roof_rain", name: "Rain on the Roof", category: "weather", icon: "roof", file: "audio/weather/roof_rain.ogg" },
  { id: "rumble", name: "Thunder Rumble", category: "weather", icon: "rumble", file: "audio/weather/rumble.ogg" },
  { id: "winter_wind", name: "Winter Wind", category: "weather", icon: "snow", file: "audio/weather/winter_wind.ogg" },
  { id: "jungle_rain", name: "Jungle Rain", category: "weather", icon: "rain", file: "audio/weather/jungle_rain.ogg" },
  { id: "canopy_wind", name: "Canopy Wind", category: "weather", icon: "leaf", file: "audio/weather/canopy_wind.ogg" },
  { id: "mountain_air", name: "Mountain Air", category: "weather", icon: "mountain", file: "audio/weather/mountain_air.ogg" },
  { id: "light_rain", name: "Light Rain", category: "weather", icon: "drop", file: "audio/weather/light_rain.ogg" },
  { id: "forest_rain", name: "Forest Rain", category: "weather", icon: "trees", file: "audio/weather/forest_rain.ogg" },
  { id: "metal_roof", name: "Rain on Metal", category: "weather", icon: "roof", file: "audio/weather/metal_roof.ogg" },
  { id: "night_rain", name: "Night Rain", category: "weather", icon: "moon", file: "audio/weather/night_rain.ogg" },
  { id: "gale", name: "Gale", category: "weather", icon: "wind", file: "audio/weather/gale.ogg" },
  { id: "breeze", name: "Breeze", category: "weather", icon: "leaf", file: "audio/weather/breeze.ogg" },
  { id: "howling", name: "Howling Wind", category: "weather", icon: "wind", file: "audio/weather/howling.ogg" },
  { id: "storm_wind", name: "Storm Wind", category: "weather", icon: "storm", file: "audio/weather/storm_wind.ogg" },
  { id: "evil_storm", name: "Evil Storm", category: "weather", icon: "bolt", file: "audio/weather/evil_storm.ogg" },
  { id: "forest_storm", name: "Forest Storm", category: "weather", icon: "trees", file: "audio/weather/forest_storm.ogg" },
  { id: "thunder_rain", name: "Rain and Thunder", category: "weather", icon: "storm", file: "audio/weather/thunder_rain.ogg" },
  { id: "heavy_rain", name: "Heavy Rain", category: "weather", icon: "rain", file: "audio/weather/heavy_rain.ogg" },

  { id: "songbirds", name: "Songbirds", category: "animals", icon: "bird", file: "audio/animals/songbirds.ogg" },
  {
    id: "wolves",
    name: "Wolves",
    category: "animals",
    icon: "wolf",
    type: "scatter",
    files: ["audio/oneshots/wolf_1.ogg", "audio/oneshots/wolf_2.ogg", "audio/oneshots/wolf_3.ogg"],
    minGap: 10,
    maxGap: 22,
  },
  {
    id: "owls",
    name: "Owls",
    category: "animals",
    icon: "owl",
    type: "scatter",
    files: ["audio/oneshots/owl_1.ogg", "audio/oneshots/owl_2.ogg"],
    minGap: 8,
    maxGap: 18,
  },
  {
    id: "ravens",
    name: "Ravens",
    category: "animals",
    icon: "raven",
    type: "scatter",
    files: ["audio/oneshots/raven_1.ogg", "audio/oneshots/raven_2.ogg", "audio/oneshots/raven_3.ogg"],
    minGap: 6,
    maxGap: 16,
  },
  { id: "horses", name: "Horses", category: "animals", icon: "horse", file: "audio/animals/horses.ogg" },
  { id: "crickets", name: "Crickets", category: "animals", icon: "bug", file: "audio/animals/crickets.ogg" },
  { id: "frogs", name: "Frogs", category: "animals", icon: "frog", file: "audio/animals/frogs.ogg" },
  {
    id: "gulls",
    name: "Gulls",
    category: "animals",
    icon: "gull",
    type: "scatter",
    files: ["audio/oneshots/gull_1.ogg", "audio/oneshots/gull_2.ogg"],
    minGap: 5,
    maxGap: 14,
  },
  { id: "bats", name: "Night insects", category: "animals", icon: "bug", file: "audio/animals/bats.ogg" },
  {
    id: "cats",
    name: "Cats",
    category: "animals",
    icon: "cat",
    type: "scatter",
    files: ["audio/oneshots/cat_1.ogg", "audio/oneshots/cat_2.ogg", "audio/oneshots/cat_3.ogg"],
    minGap: 8,
    maxGap: 18,
  },
  {
    id: "hounds",
    name: "Hounds",
    category: "animals",
    icon: "dog",
    type: "scatter",
    files: ["audio/oneshots/dog_1.ogg", "audio/oneshots/dog_2.ogg", "audio/oneshots/dog_3.ogg", "audio/oneshots/growl_1.ogg"],
    minGap: 7,
    maxGap: 16,
  },
  {
    id: "rooster",
    name: "Rooster",
    category: "animals",
    icon: "rooster",
    type: "scatter",
    files: ["audio/oneshots/rooster_1.ogg", "audio/oneshots/rooster_2.ogg"],
    minGap: 10,
    maxGap: 22,
  },
  {
    id: "eagle",
    name: "Eagle",
    category: "animals",
    icon: "eagle",
    type: "scatter",
    files: ["audio/oneshots/eagle_1.ogg", "audio/oneshots/hawk_1.ogg", "audio/oneshots/hawk_2.ogg"],
    minGap: 9,
    maxGap: 20,
  },
  { id: "bees", name: "Bees", category: "animals", icon: "bee", file: "audio/animals/bees.ogg" },
  { id: "flies", name: "Flies", category: "animals", icon: "fly", file: "audio/animals/flies.ogg" },
  {
    id: "cattle",
    name: "Cattle",
    category: "animals",
    icon: "cow",
    type: "scatter",
    files: ["audio/oneshots/cow_1.ogg", "audio/oneshots/cow_2.ogg"],
    minGap: 8,
    maxGap: 18,
  },
  {
    id: "fox",
    name: "Fox",
    category: "animals",
    icon: "fox",
    type: "scatter",
    files: ["audio/oneshots/fox_1.ogg"],
    minGap: 10,
    maxGap: 22,
  },
  { id: "farmyard", name: "Farmyard", category: "animals", icon: "farm", file: "audio/animals/farmyard.ogg" },
  { id: "purring", name: "Purring", category: "animals", icon: "cat", file: "audio/animals/purring.ogg" },
  {
    id: "donkeys",
    name: "Donkeys",
    category: "animals",
    icon: "donkey",
    type: "scatter",
    files: ["audio/oneshots/donkey_1.ogg"],
    minGap: 9,
    maxGap: 20,
  },
  {
    id: "horse_calls",
    name: "Horse Calls",
    category: "animals",
    icon: "horse",
    type: "scatter",
    files: ["audio/oneshots/neigh_1.ogg", "audio/oneshots/neigh_2.ogg"],
    minGap: 8,
    maxGap: 18,
  },
  { id: "morning_birds", name: "Morning Birds", category: "animals", icon: "bird", file: "audio/animals/morning_birds.ogg" },
  { id: "jungle_birds", name: "Jungle Birds", category: "animals", icon: "jungle", file: "audio/animals/jungle_birds.ogg" },
  { id: "river_birds", name: "River Birds", category: "animals", icon: "bird", file: "audio/animals/river_birds.ogg" },
  { id: "forest_birds", name: "Forest Birds", category: "animals", icon: "trees", file: "audio/animals/forest_birds.ogg" },
  { id: "chickens", name: "Chickens", category: "animals", icon: "chicken", file: "audio/animals/chickens.ogg" },
  { id: "owl_woods", name: "Owls in the Woods", category: "animals", icon: "owl", file: "audio/animals/owl_woods.ogg" },
  { id: "cicadas", name: "Cicadas", category: "animals", icon: "bug", file: "audio/animals/cicadas.ogg" },
  { id: "gallop", name: "Gallop", category: "animals", icon: "horse", file: "audio/animals/gallop.ogg" },
  { id: "swamp_bugs", name: "Swamp Chorus", category: "animals", icon: "frog", file: "audio/animals/swamp_bugs.ogg" },
  {
    id: "geese",
    name: "Geese",
    category: "animals",
    icon: "goose",
    type: "scatter",
    files: ["audio/oneshots/goose_1.ogg"],
    minGap: 7,
    maxGap: 16,
  },
  {
    id: "goats",
    name: "Goats",
    category: "animals",
    icon: "goat",
    type: "scatter",
    files: ["audio/oneshots/goat_1.ogg", "audio/oneshots/goat_2.ogg"],
    minGap: 8,
    maxGap: 18,
  },
  {
    id: "dragon_roar",
    name: "Dragon Roar",
    category: "animals",
    icon: "dragon",
    type: "scatter",
    files: ["audio/oneshots/dragon_1.ogg"],
    minGap: 12,
    maxGap: 26,
  },
  {
    id: "beast",
    name: "Beast",
    category: "animals",
    icon: "wolf",
    type: "scatter",
    files: ["audio/oneshots/beast_1.ogg", "audio/oneshots/beast_2.ogg"],
    minGap: 10,
    maxGap: 22,
  },

  { id: "campfire", name: "Campfire", category: "ambience", icon: "fire", file: "audio/ambience/campfire.ogg" },
  { id: "tavern_hall", name: "Tavern Hall", category: "ambience", icon: "mug", file: "audio/ambience/tavern_hall.ogg" },
  { id: "market", name: "Marketplace", category: "ambience", icon: "market", file: "audio/ambience/market.ogg" },
  { id: "dungeon", name: "Dungeon", category: "ambience", icon: "dungeon", file: "audio/ambience/dungeon.ogg" },
  { id: "cavern", name: "Cavern", category: "ambience", icon: "cave", file: "audio/ambience/cavern.ogg" },
  { id: "ocean", name: "Ocean", category: "ambience", icon: "wave", file: "audio/ambience/ocean.ogg" },
  { id: "river", name: "River", category: "ambience", icon: "river", file: "audio/ambience/river.ogg" },
  { id: "waterfall", name: "Waterfall", category: "ambience", icon: "waterfall", file: "audio/ambience/waterfall.ogg" },
  { id: "swamp", name: "Swamp", category: "ambience", icon: "swamp", file: "audio/ambience/swamp.ogg" },
  { id: "graveyard", name: "Graveyard", category: "ambience", icon: "tomb", file: "audio/ambience/graveyard.ogg" },
  { id: "magic", name: "Arcane Hum", category: "ambience", icon: "spark", file: "audio/ambience/magic.ogg" },
  { id: "forge", name: "Forge", category: "ambience", icon: "anvil", file: "audio/ambience/forge.ogg" },
  { id: "ship", name: "Ship", category: "ambience", icon: "ship", file: "audio/ambience/ship.ogg" },
  { id: "desert", name: "Desert", category: "ambience", icon: "dune", file: "audio/ambience/desert.ogg" },
  { id: "lava", name: "Lava", category: "ambience", icon: "lava", file: "audio/ambience/lava.ogg" },
  { id: "war_camp", name: "War Camp", category: "ambience", icon: "banner", file: "audio/ambience/war_camp.ogg" },
  { id: "temple", name: "Temple", category: "ambience", icon: "temple", file: "audio/ambience/temple.ogg" },
  { id: "torch", name: "Torch", category: "ambience", icon: "torch", file: "audio/ambience/torch.ogg" },
  { id: "night_woods", name: "Night Woods", category: "ambience", icon: "moon", file: "audio/ambience/night_woods.ogg" },
  { id: "jungle", name: "Jungle", category: "ambience", icon: "jungle", file: "audio/ambience/jungle.ogg" },
  { id: "town_square", name: "Town Square", category: "ambience", icon: "square", file: "audio/ambience/town_square.ogg" },
  { id: "surf", name: "Surf", category: "ambience", icon: "wave", file: "audio/ambience/surf.ogg" },
  { id: "cascade", name: "Cascade", category: "ambience", icon: "waterfall", file: "audio/ambience/cascade.ogg" },
  { id: "fireplace", name: "Fireplace", category: "ambience", icon: "fire", file: "audio/ambience/fireplace.ogg" },
  { id: "sewers", name: "Sewers", category: "ambience", icon: "sewer", file: "audio/ambience/sewers.ogg" },
  { id: "kitchen", name: "Inn Kitchen", category: "ambience", icon: "kitchen", file: "audio/ambience/kitchen.ogg" },
  { id: "library", name: "Library", category: "ambience", icon: "book", file: "audio/ambience/library.ogg" },
  { id: "drips", name: "Stone Drips", category: "ambience", icon: "drip", file: "audio/ambience/drips.ogg" },
  { id: "night_forest", name: "Forest Night", category: "ambience", icon: "moon", file: "audio/ambience/night_forest.ogg" },
  { id: "scary_woods", name: "Scary Woods", category: "ambience", icon: "ghost", file: "audio/ambience/scary_woods.ogg" },
  { id: "tomb", name: "Tomb", category: "ambience", icon: "tomb", file: "audio/ambience/tomb.ogg" },
  { id: "crowded_pub", name: "Crowded Pub", category: "ambience", icon: "mug", file: "audio/ambience/crowded_pub.ogg" },
  { id: "street", name: "Street", category: "ambience", icon: "square", file: "audio/ambience/street.ogg" },
  { id: "fair", name: "Fairground", category: "ambience", icon: "lute", file: "audio/ambience/fair.ogg" },
  { id: "church_bells", name: "Church Bells", category: "ambience", icon: "bell", file: "audio/ambience/church_bells.ogg" },
  { id: "clock", name: "Old Clock", category: "ambience", icon: "clock", file: "audio/ambience/clock.ogg" },
  { id: "big_fire", name: "Great Fire", category: "ambience", icon: "fire", file: "audio/ambience/big_fire.ogg" },
  { id: "desert_night", name: "Desert Night", category: "ambience", icon: "dune", file: "audio/ambience/desert_night.ogg" },
  { id: "harbor", name: "Harbor", category: "ambience", icon: "ship", file: "audio/ambience/harbor.ogg" },
  { id: "stormy_waves", name: "Stormy Waves", category: "ambience", icon: "wave", file: "audio/ambience/stormy_waves.ogg" },
  { id: "european_forest", name: "Old Forest", category: "ambience", icon: "trees", file: "audio/ambience/european_forest.ogg" },
  { id: "garden", name: "Garden", category: "ambience", icon: "leaf", file: "audio/ambience/garden.ogg" },
  { id: "barn", name: "Barn", category: "ambience", icon: "farm", file: "audio/ambience/barn.ogg" },
  { id: "pond", name: "Pond", category: "ambience", icon: "frog", file: "audio/ambience/pond.ogg" },
  { id: "horror", name: "Horror", category: "ambience", icon: "ghost", file: "audio/ambience/horror.ogg" },
  { id: "twilight_jungle", name: "Twilight Jungle", category: "ambience", icon: "jungle", file: "audio/ambience/twilight_jungle.ogg" },
  { id: "rainforest", name: "Rainforest", category: "ambience", icon: "rain", file: "audio/ambience/rainforest.ogg" },
  { id: "campfire_wind", name: "Camp in the Wind", category: "ambience", icon: "fire", file: "audio/ambience/campfire_wind.ogg" },
  { id: "leaves", name: "Dry Leaves", category: "ambience", icon: "leaf", file: "audio/ambience/leaves.ogg" },
  { id: "river_dawn", name: "River at Dawn", category: "ambience", icon: "river", file: "audio/ambience/river_dawn.ogg" },
  { id: "waterfall_woods", name: "Woodland Falls", category: "ambience", icon: "waterfall", file: "audio/ambience/waterfall_woods.ogg" },
  { id: "beach", name: "Beach", category: "ambience", icon: "wave", file: "audio/ambience/beach.ogg" },
  { id: "shore", name: "Shore", category: "ambience", icon: "wave", file: "audio/ambience/shore.ogg" },
  { id: "sea_wind", name: "Sea Wind", category: "weather", icon: "wind", file: "audio/ambience/sea_wind.ogg" },
  { id: "shore_birds", name: "Shore Birds", category: "animals", icon: "gull", file: "audio/ambience/shore_birds.ogg" },
  { id: "underwater", name: "Underwater", category: "ambience", icon: "fish", file: "audio/ambience/underwater.ogg" },
  { id: "diving", name: "Diving", category: "ambience", icon: "drop", file: "audio/ambience/diving.ogg" },
  { id: "deep_hum", name: "Deep Hum", category: "ambience", icon: "fish", file: "audio/ambience/deep_hum.ogg" },
  { id: "sinking", name: "The Deep", category: "ambience", icon: "wave", file: "audio/ambience/sinking.ogg" },
  {
    id: "bubbles",
    name: "Bubbles",
    category: "ambience",
    icon: "drop",
    type: "scatter",
    files: ["audio/oneshots/bubble_1.ogg", "audio/oneshots/bubble_2.ogg", "audio/oneshots/bubble_3.ogg"],
    minGap: 2,
    maxGap: 7,
  },
  {
    id: "splash",
    name: "Splash",
    category: "ambience",
    icon: "wave",
    type: "scatter",
    files: ["audio/oneshots/splash_1.ogg", "audio/oneshots/splash_2.ogg"],
    minGap: 6,
    maxGap: 16,
  },
];

export const SCENES = [
  {
    id: "tavern",
    name: "Quiet Tavern",
    blurb: "Firelight, low talk, rain on the shutters.",
    icon: "mug",
    mood: "ember",
    layers: { tavern_jig: 0.48, tavern_hall: 0.4, campfire: 0.34, rain: 0.2 },
  },
  {
    id: "forest",
    name: "Deep Forest",
    blurb: "Birdsong, a river, wind in the canopy.",
    icon: "trees",
    mood: "green",
    layers: { forest_wander: 0.42, songbirds: 0.48, river: 0.28, wind: 0.18 },
  },
  {
    id: "camp",
    name: "Night Camp",
    blurb: "Embers, crickets, an owl beyond the trees.",
    icon: "fire",
    mood: "ember",
    layers: { campfire: 0.52, crickets: 0.38, owls: 0.44, wind: 0.16, road_theme: 0.26 },
  },
  {
    id: "crawl",
    name: "Dungeon Crawl",
    blurb: "Drips, torch hiss, something in the dark.",
    icon: "dungeon",
    mood: "slate",
    layers: { dungeon_depths: 0.46, dungeon: 0.5, torch: 0.32, bats: 0.26 },
  },
  {
    id: "storm",
    name: "Raging Storm",
    blurb: "Rain like nails. Thunder close enough to feel.",
    icon: "storm",
    mood: "storm",
    layers: { downpour: 0.62, thunder: 0.72, wind: 0.4, distant_storm: 0.3 },
  },
  {
    id: "battles",
    name: "Battles",
    blurb: "The whole war. Every fight track, drums and steel.",
    icon: "swords",
    mood: "blood",
    playlist: "battle",
    layers: { war_camp: 0.34, battle_march: 0.56 },
  },
  {
    id: "battle",
    name: "Open Battle",
    blurb: "Drums, steel, the camp behind the line.",
    icon: "swords",
    mood: "blood",
    layers: { battle_march: 0.58, war_camp: 0.36 },
  },
  {
    id: "sea",
    name: "Open Sea",
    blurb: "Swell, creaking timber, gulls off the bow.",
    icon: "ship",
    mood: "sea",
    layers: { ocean: 0.5, ship: 0.36, wind: 0.24, ocean_voyage: 0.38, gulls: 0.32 },
  },
  {
    id: "sanctum",
    name: "Sacred Hall",
    blurb: "Stone, incense, a hymn that does not end.",
    icon: "temple",
    mood: "gold",
    layers: { sacred_hymn: 0.5, temple: 0.36, magic: 0.2 },
  },
  {
    id: "crypt",
    name: "Crypt",
    blurb: "A rite below the earth. Do not linger.",
    icon: "tomb",
    mood: "violet",
    layers: { dark_rite: 0.42, cavern: 0.46, graveyard: 0.34, bats: 0.22 },
  },
  {
    id: "city",
    name: "City Streets",
    blurb: "Hawkers, hammers, ravens on the eaves.",
    icon: "market",
    mood: "ember",
    layers: { market: 0.46, ravens: 0.3, forge: 0.16, road_theme: 0.26 },
  },
  {
    id: "mire",
    name: "Haunted Swamp",
    blurb: "Frogs, wet earth, a tune you should not hum.",
    icon: "swamp",
    mood: "green",
    layers: { swamp: 0.5, frogs: 0.4, rain: 0.22, dark_rite: 0.26 },
  },
  {
    id: "court",
    name: "Royal Court",
    blurb: "Polite voices. Dangerous smiles.",
    icon: "crown",
    mood: "gold",
    layers: { royal_court: 0.52, tavern_hall: 0.16 },
  },
  {
    id: "lair",
    name: "Dragon's Lair",
    blurb: "Heat in the stone. Something vast is breathing.",
    icon: "dragon",
    mood: "blood",
    layers: { dragon_wake: 0.48, lava: 0.42, cavern: 0.28 },
  },
  {
    id: "winter",
    name: "Winter Pass",
    blurb: "White wind, wolves on the ridge.",
    icon: "snow",
    mood: "ice",
    layers: { blizzard: 0.5, wind: 0.32, winter_march: 0.4, wolves: 0.38 },
  },
  {
    id: "glade",
    name: "Elven Glade",
    blurb: "Harp-light, birds, a river like glass.",
    icon: "leaf",
    mood: "green",
    layers: { elven_glade: 0.5, songbirds: 0.38, river: 0.22, magic: 0.14 },
  },
  {
    id: "thieves",
    name: "Thieves' Den",
    blurb: "Low talk, a torch, secrets in the wet stone.",
    icon: "mask",
    mood: "slate",
    layers: { dungeon: 0.32, tavern_hall: 0.28, torch: 0.28, dark_rite: 0.22 },
  },
  {
    id: "caravan",
    name: "Desert Caravan",
    blurb: "Sand, hooves, a long road south.",
    icon: "dune",
    mood: "ember",
    layers: { desert: 0.46, horses: 0.36, wind: 0.22, road_theme: 0.3 },
  },
  {
    id: "smithy",
    name: "The Forge",
    blurb: "Hammer, bellows, a mug at the anvil.",
    icon: "anvil",
    mood: "ember",
    layers: { forge: 0.5, campfire: 0.22, tavern_hall: 0.18 },
  },
  {
    id: "shrine",
    name: "Waterfall Shrine",
    blurb: "White water and a quiet hymn.",
    icon: "waterfall",
    mood: "sea",
    layers: { waterfall: 0.46, sacred_hymn: 0.28, songbirds: 0.22, river: 0.18 },
  },
  {
    id: "watch",
    name: "Midnight Watch",
    blurb: "The last torch. The world holding its breath.",
    icon: "moon",
    mood: "violet",
    layers: { crickets: 0.4, owls: 0.38, torch: 0.28, wind: 0.18, distant_storm: 0.14 },
  },
  {
    id: "festival",
    name: "Harvest Festival",
    blurb: "Pipes, crowd, a mug that never empties.",
    icon: "lute",
    mood: "ember",
    layers: { harvest_dance: 0.5, tavern_hall: 0.34, market: 0.22, cats: 0.22 },
  },
  {
    id: "moor",
    name: "Foggy Moor",
    blurb: "White air, a fox, something watching.",
    icon: "fog",
    mood: "ice",
    layers: { fog: 0.55, oppressive_gloom: 0.38, ravens: 0.28, winter_wind: 0.22, fox: 0.3 },
  },
  {
    id: "tower",
    name: "Wizard's Tower",
    blurb: "Rain on old stone. The air tastes of ozone.",
    icon: "wizard",
    mood: "violet",
    layers: { wizards_tower: 0.5, magic: 0.32, rain: 0.22, rumble: 0.16 },
  },
  {
    id: "village",
    name: "Village Dawn",
    blurb: "A rooster, cattle, the first cart on the road.",
    icon: "farm",
    mood: "green",
    layers: { farmyard: 0.4, rooster: 0.45, cattle: 0.32, songbirds: 0.28, road_theme: 0.22 },
  },
  {
    id: "hailstorm",
    name: "Hailstorm",
    blurb: "Ice on the roof. The horses hate it.",
    icon: "hail",
    mood: "storm",
    layers: { hail: 0.55, roof_rain: 0.4, wind: 0.3, stormfront: 0.34, thunder: 0.4 },
  },
  {
    id: "stealth",
    name: "Quiet Streets",
    blurb: "Soft shoes, a hound two alleys over.",
    icon: "sneak",
    mood: "slate",
    layers: { quiet_work: 0.48, dungeon: 0.22, torch: 0.2, hounds: 0.28, cats: 0.2 },
  },
  {
    id: "eyrie",
    name: "Mountain Eyrie",
    blurb: "Wind, an eagle, a hymn for the climb.",
    icon: "eagle",
    mood: "ice",
    layers: { heroic_age: 0.46, wind: 0.34, eagle: 0.4, winter_wind: 0.2 },
  },
  {
    id: "goblin",
    name: "Goblin Market",
    blurb: "Wrong pipes. Bright stalls. Do not eat the fruit.",
    icon: "mask",
    mood: "ember",
    layers: { goblin_road: 0.5, market: 0.32, flies: 0.22, bees: 0.16 },
  },
  {
    id: "woods-night",
    name: "Night Woods",
    blurb: "Owls, insects, a path you cannot see.",
    icon: "moon",
    mood: "violet",
    layers: { night_woods: 0.5, owls: 0.4, crickets: 0.32, hidden_past: 0.28, wind: 0.16 },
  },
  {
    id: "wilds",
    name: "Deep Jungle",
    blurb: "Rain in the canopy. Something large moves.",
    icon: "jungle",
    mood: "green",
    layers: { jungle: 0.5, jungle_rain: 0.34, canopy_wind: 0.22, frogs: 0.28, the_descent: 0.26 },
  },
  {
    id: "docks",
    name: "The Docks",
    blurb: "Surf, gulls, a hull that never stops complaining.",
    icon: "ship",
    mood: "sea",
    layers: { surf: 0.48, ship: 0.36, gulls: 0.38, ocean_voyage: 0.3, wind: 0.18 },
  },
  {
    id: "square",
    name: "Town Square",
    blurb: "Hawkers, a piper, the smell of bread.",
    icon: "square",
    mood: "ember",
    layers: { town_square: 0.48, village_fair: 0.42, market: 0.22, hounds: 0.18 },
  },
  {
    id: "under",
    name: "The Sewers",
    blurb: "Drips, a river that should not be there.",
    icon: "sewer",
    mood: "slate",
    layers: { sewers: 0.55, drips: 0.4, the_descent: 0.34, flies: 0.22 },
  },
  {
    id: "stacks",
    name: "The Library",
    blurb: "Dust, a fire, pages that turn themselves.",
    icon: "book",
    mood: "gold",
    layers: { library: 0.5, fireplace: 0.28, lost_time: 0.4, rain: 0.14 },
  },
  {
    id: "hearthside",
    name: "Inn Kitchen",
    blurb: "Pots, a cat, the hearth behind the bar.",
    icon: "kitchen",
    mood: "ember",
    layers: { kitchen: 0.5, fireplace: 0.3, purring: 0.28, cats: 0.24, maestro: 0.22 },
  },
  {
    id: "ghosts",
    name: "Haunted Keep",
    blurb: "A story no one should finish.",
    icon: "ghost",
    mood: "violet",
    layers: { ghost_story: 0.5, cavern: 0.32, drips: 0.22, bats: 0.2 },
  },
  {
    id: "pyre",
    name: "The Pyre",
    blurb: "Heat, a crowd that will not look away.",
    icon: "fire",
    mood: "blood",
    layers: { the_pyre: 0.52, war_camp: 0.28, fireplace: 0.24, wind: 0.16 },
  },
  {
    id: "ride",
    name: "Night Ride",
    blurb: "Hooves, a witch-wind, no moon.",
    icon: "horse",
    mood: "violet",
    layers: { morgana: 0.5, horses: 0.4, horse_calls: 0.3, wind: 0.26, canopy_wind: 0.16 },
  },
  {
    id: "warroad",
    name: "War Road",
    blurb: "Banners, dust, a song for the march.",
    icon: "banner",
    mood: "blood",
    layers: { crusade: 0.48, clash_defiant: 0.28, horses: 0.26, war_camp: 0.2 },
  },
  {
    id: "drizzle-lane",
    name: "Soft Rain",
    blurb: "A light fall on the shutters. The inn still breathes.",
    icon: "drop",
    mood: "sea",
    layers: { light_rain: 0.5, pippin: 0.36, tavern_hall: 0.22, fireplace: 0.2 },
  },
  {
    id: "wet-woods",
    name: "Rain in the Woods",
    blurb: "Canopy drip, birds that will not leave.",
    icon: "trees",
    mood: "green",
    layers: { forest_rain: 0.5, forest_birds: 0.36, european_forest: 0.28, forest_wander: 0.3 },
  },
  {
    id: "windwall",
    name: "The Gale",
    blurb: "The wind has opinions. The shutters agree.",
    icon: "wind",
    mood: "storm",
    layers: { gale: 0.52, howling: 0.34, storm_wind: 0.28, stormfront: 0.3 },
  },
  {
    id: "dawn",
    name: "Dawn Chorus",
    blurb: "The garden first. Then the road.",
    icon: "bird",
    mood: "green",
    layers: { morning_birds: 0.5, garden: 0.32, rooster: 0.28, achaidh: 0.3, songbirds: 0.18 },
  },
  {
    id: "barnyard",
    name: "The Barn",
    blurb: "Hens, goats, a cow that will not be rushed.",
    icon: "farm",
    mood: "ember",
    layers: { barn: 0.48, chickens: 0.36, goats: 0.32, cattle: 0.24, farmyard: 0.2 },
  },
  {
    id: "hunt",
    name: "The Hunt",
    blurb: "Hooves, a horn, something running.",
    icon: "horse",
    mood: "blood",
    layers: { feral_chase: 0.52, gallop: 0.4, forest_birds: 0.22, wind: 0.16, horse_calls: 0.22 },
  },
  {
    id: "beasthouse",
    name: "The Beast",
    blurb: "Stone, heat, a roar that is not weather.",
    icon: "dragon",
    mood: "blood",
    layers: { black_vortex: 0.46, dragon_roar: 0.5, beast: 0.38, cavern: 0.28, lava: 0.18 },
  },
  {
    id: "bells",
    name: "Sunday Bells",
    blurb: "The tower calling. Dust in the nave.",
    icon: "bell",
    mood: "gold",
    layers: { church_bells: 0.48, sacred_hymn: 0.36, temple: 0.28, garden: 0.16 },
  },
  {
    id: "clocktower",
    name: "Clocktower",
    blurb: "Rain on the mechanism. Time is not a friend.",
    icon: "clock",
    mood: "slate",
    layers: { clock: 0.46, mystery: 0.4, rain: 0.22, drips: 0.18 },
  },
  {
    id: "packed",
    name: "Packed Pub",
    blurb: "Too many voices. The jig is winning.",
    icon: "mug",
    mood: "ember",
    layers: { crowded_pub: 0.5, pippin: 0.38, tavern_jig: 0.22, cats: 0.16 },
  },
  {
    id: "leeward",
    name: "Harbor Storm",
    blurb: "Waves against the quay. Stay off the water.",
    icon: "ship",
    mood: "storm",
    layers: { stormy_waves: 0.5, harbor: 0.34, gale: 0.28, ocean_voyage: 0.26, gulls: 0.22 },
  },
  {
    id: "catacombs",
    name: "Catacombs",
    blurb: "Air that has been held a long time.",
    icon: "tomb",
    mood: "violet",
    layers: { ossuary: 0.48, tomb: 0.4, drips: 0.26, bats: 0.2, chamber: 0.22 },
  },
  {
    id: "lily",
    name: "Lily Pond",
    blurb: "Frogs, a harp, the last of the light.",
    icon: "frog",
    mood: "green",
    layers: { pond: 0.48, frogs: 0.32, blue_feather: 0.36, river_birds: 0.24 },
  },
  {
    id: "autumn",
    name: "Autumn Path",
    blurb: "Leaves underfoot. A breeze that knows the way.",
    icon: "leaf",
    mood: "ember",
    layers: { leaves: 0.46, breeze: 0.32, european_forest: 0.28, forest_wander: 0.3 },
  },
  {
    id: "scare",
    name: "Something in the Trees",
    blurb: "Do not answer whatever is calling.",
    icon: "ghost",
    mood: "violet",
    layers: { scary_woods: 0.5, darkling: 0.38, wolves: 0.32, owls: 0.24, wind: 0.16 },
  },
  {
    id: "dunes",
    name: "Desert Night",
    blurb: "Sand, a curse, no moon worth mentioning.",
    icon: "dune",
    mood: "ember",
    layers: { desert_night: 0.5, scarab: 0.4, wind: 0.22, crickets: 0.18 },
  },
  {
    id: "fairground",
    name: "The Fair",
    blurb: "Pipes, a crowd, geese that will not be herded.",
    icon: "lute",
    mood: "ember",
    layers: { fair: 0.48, village_fair: 0.4, geese: 0.28, market: 0.18 },
  },
  {
    id: "canopy-storm",
    name: "Rainforest",
    blurb: "Thunder under the green roof.",
    icon: "jungle",
    mood: "green",
    layers: { rainforest: 0.48, jungle_birds: 0.34, twilight_jungle: 0.26, forest_storm: 0.28, the_descent: 0.2 },
  },
  {
    id: "firehall",
    name: "Great Hall Fire",
    blurb: "A fire meant to be seen from the road.",
    icon: "fire",
    mood: "ember",
    layers: { big_fire: 0.5, lord_land: 0.38, tavern_hall: 0.22, church_bells: 0.12 },
  },
  {
    id: "chase",
    name: "Night Chase",
    blurb: "Hooves, a storm, no time for the hymn.",
    icon: "horse",
    mood: "blood",
    layers: { feral_chase: 0.5, gallop: 0.36, gale: 0.26, thunder: 0.28, horse_calls: 0.2 },
  },
  {
    id: "rest",
    name: "At Rest",
    blurb: "The fire. The wind. Nothing hunting you. Yet.",
    icon: "fire",
    mood: "gold",
    layers: { at_rest: 0.48, campfire_wind: 0.36, crickets: 0.24, owl_woods: 0.22 },
  },
  {
    id: "mystery-hall",
    name: "Quiet Inquiry",
    blurb: "A clock, a corridor, a secret with manners.",
    icon: "sneak",
    mood: "slate",
    layers: { mystery: 0.5, clock: 0.28, library: 0.26, rain: 0.16 },
  },
  {
    id: "rite",
    name: "The Rite",
    blurb: "A song that should have stayed in the book.",
    icon: "spark",
    mood: "violet",
    layers: { ritual_song: 0.5, horror: 0.32, magic: 0.24, drips: 0.18 },
  },
  {
    id: "chamber-walk",
    name: "The Chamber",
    blurb: "Stone that remembers every name.",
    icon: "dungeon",
    mood: "slate",
    layers: { chamber: 0.48, dungeon: 0.36, torch: 0.24, interloper: 0.22 },
  },
  {
    id: "heath",
    name: "The Heath",
    blurb: "Open land, a low sky, a fox you will not catch.",
    icon: "fog",
    mood: "ice",
    layers: { moorland: 0.5, fog: 0.32, breeze: 0.24, fox: 0.26, ravens: 0.18 },
  },
  {
    id: "call",
    name: "Call to Adventure",
    blurb: "The road is done waiting.",
    icon: "banner",
    mood: "gold",
    layers: { call_adventure: 0.52, wind: 0.2, horses: 0.24, mountain_air: 0.18 },
  },
  {
    id: "threshold",
    name: "The Threshold",
    blurb: "Something is already in the house.",
    icon: "ghost",
    mood: "violet",
    layers: { interloper: 0.5, horror: 0.3, torch: 0.22, rain: 0.16, cats: 0.14 },
  },
  {
    id: "strand",
    name: "The Strand",
    blurb: "Surf, gulls, a wind that never inland.",
    icon: "wave",
    mood: "sea",
    layers: { with_the_sea: 0.42, beach: 0.5, shore_birds: 0.32, gulls: 0.28, sea_wind: 0.18 },
  },
  {
    id: "night-shore",
    name: "Moonlit Shore",
    blurb: "The tide, a piano, no fire on the sand.",
    icon: "moon",
    mood: "sea",
    layers: { shores_avalon: 0.46, shore: 0.42, sea_wind: 0.22, crickets: 0.16 },
  },
  {
    id: "depths",
    name: "Below the Waves",
    blurb: "Pressure. Bubbles. A hymn that does not carry.",
    icon: "fish",
    mood: "sea",
    layers: { water_prelude: 0.5, underwater: 0.48, bubbles: 0.36, diving: 0.22 },
  },
  {
    id: "wreck",
    name: "The Wreck",
    blurb: "A city that learned to drown.",
    icon: "ship",
    mood: "violet",
    layers: { floating_cities: 0.5, sinking: 0.4, deep_hum: 0.28, bubbles: 0.3, drips: 0.14 },
  },
];

export const SCENE_ALIASES = {
  dungeon: "crawl",
  temple: "sanctum",
  swamp: "mire",
  desert: "caravan",
  forge: "smithy",
};

export function worldOf() {
  return document.documentElement?.dataset?.theme === "blight" ? "blight" : "hearthsong";
}

export function liveMoods() {
  return worldOf() === "blight" ? BLIGHT_MOODS : MUSIC_MOODS;
}

export function liveScenes() {
  return worldOf() === "blight" ? BLIGHT_SCENES : SCENES;
}

function layerWorld(layer) {
  if (layer?.world) return layer.world;
  if (layer?.category === "weather") return "both";
  return "hearthsong";
}

export function liveLayers() {
  const w = worldOf();
  if (w === "blight") {
    return [
      ...LAYERS.filter((l) => layerWorld(l) === "both" || (l.custom && layerWorld(l) === "blight")),
      ...BLIGHT_LAYERS,
    ];
  }
  return LAYERS.filter((l) => layerWorld(l) !== "blight");
}

export function sceneById(id) {
  const resolved = SCENE_ALIASES[id] || id;
  return liveScenes().find((s) => s.id === resolved) || SCENES.find((s) => s.id === resolved) || BLIGHT_SCENES.find((s) => s.id === resolved);
}

export function layerById(id) {
  return LAYERS.find((l) => l.id === id) || BLIGHT_LAYERS.find((l) => l.id === id);
}

export function tracksForMood(mood) {
  const have = liveLayers().filter((l) => l.category === "music" && l.mood === mood).map((l) => l.id);
  const haveSet = new Set(have);
  const preferred = worldOf() === "blight"
    ? []
    : mood === "battle" ? BATTLE_TRACKS : [];
  const ordered = preferred.filter((id) => haveSet.has(id));
  for (const id of have) {
    if (!ordered.includes(id)) ordered.push(id);
  }
  return ordered;
}

export function allAudioUrls() {
  const urls = new Set();
  for (const layer of [...LAYERS, ...BLIGHT_LAYERS]) {
    if (layer.file) urls.add(layer.file);
    if (layer.files) layer.files.forEach((u) => urls.add(u));
  }
  return [...urls];
}
