#!/usr/bin/env python3
"""Baldur's Gate / Sword Coast gods. Original table dossiers. Not book copy."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path("/home/steelworth/projects/blightnet")
OUT = ROOT / "data" / "gods.json"

# pantheon, id, name, aka, align, domains, symbol, rank, look, blurb, text, worship, hooks
GODS = [
    (
        "baldur", "auril", "Auril", "Frostmaiden, Icedawn, the Cold Goddess",
        "neutral evil", "Tempest, Nature", "A six-pointed snowflake, or a white diamond on ice-blue",
        "lesser",
        "A pale woman in a high-collared cloak of white fur and rime, crown of icicles, lips blue, eyes like winter water. Fully clothed. A frozen harbor behind her.",
        "Winter that does not leave when the calendar says it should. Beauty that bites.",
        "Auril is the reason a Sword Coast winter feels personal. She is not a storm you wait out. She is the decision that the harvest failed and the pass stays shut.\n\nClerics of Auril keep cold the way other priests keep a flame. They bless ice over a lock. They ask a price for thaw. In Baldur's Gate she is a dockside superstition: do not mock the frost on the rigging. In the north she is a state.\n\nAt the table she is leverage. A party that burns her shrine for warmth has made an enemy of the next cold snap. A party that leaves an offering of unmelted ice at a crossroads may find the wolves walking around them.",
        "Leave something that will not thaw. Speak little. Do not light a fire in her sight unless you are ready to pay for it.",
        ["The Rivington wells froze in Tarsakh. A white-cloaked priestess will thaw one — if the party fetches a heart of true ice from the Coast Way.", "A ship is locked in the harbor by a sheet that will not break. The crew is eating the cargo. Auril wants a name spoken on the ice."],
    ),
    (
        "baldur", "bahamut", "Bahamut", "The Platinum Dragon, King of the Good Dragons, Grandfather of Dragons",
        "lawful good", "War, Life", "A rising platinum dragon, or a star over a shield",
        "greater",
        "A noble elder in silver-white plate with a draconic helm under one arm, platinum cloak, calm eyes. Behind him the suggestion of vast wings, not a full beast-shot. Clothed, kingly.",
        "Justice with patience, and a temper he spends like a hoard.",
        "Bahamut does not rule a street. He rules the idea that power should be used on behalf of people who cannot hoard it. Paladins who keep him are rare on the Sword Coast and conspicuous when they arrive.\n\nHe opposes Tiamat as a matter of family and of law. A cleric of Bahamut will not start a tavern brawl. They will finish one if a child is in it.\n\nAt the table he is a high bar. His signs are small: a platinum scale left on a pillow, a dream of flying over a city that is on fire and choosing which roof to land on. He does not want a cult. He wants the work done.",
        "Kneel only to swear. Then stand up and keep the oath. Gold given to the poor counts. Gold given to a statue does not.",
        ["A platinum scale was found in a Lower City well. Three churches claim it. Something in the sewers is hunting the claimants.", "A young metallic dragon is hiding in a warehouse as a man. Tiamat's cult has the address. Bahamut wants the man walked out, not displayed."],
    ),
    (
        "baldur", "bane", "Bane", "The Black Lord, Lord of Darkness, the Strife",
        "lawful evil", "War, Trickery", "A black gauntleted fist, or a green-black sunburst on iron",
        "greater",
        "A tall tyrant in black plate chased with green, visor up on a hard face, one gauntlet raised as if the room already belongs to him. No gore. A hall of banners behind.",
        "Order as a boot. Fear as administration.",
        "Bane is one of the Dead Three, and the one who still thinks like a general. He does not want chaos. He wants a chain of command with himself at the top and everyone else grateful they were allowed a rank.\n\nIn Baldur's Gate his people do not always wear a fist. They wear a badge, a contract, a quiet monopoly. Banites prefer a city that already has laws. They just want to own the laws.\n\nA cleric of Bane at the table is a problem you can negotiate with, which is worse. They keep their word the way a siege keeps a timetable.",
        "Kneel. Mean it. Bring him a victory, not a prayer. He has enough prayers.",
        ["A Fist captain has started quoting a black book in briefings. The book is new. The fist on the cover is not.", "A Banite cell is offering to 'stabilize' the Outer City after a gang war. Their price is a seat on the next council."],
    ),
    (
        "baldur", "beshaba", "Beshaba", "Maid of Misfortune, Lady Doom, the Black Bess",
        "chaotic evil", "Trickery, Tempest", "A rack of antlers on black, or a red field of disaster",
        "greater",
        "A sharp-smiling woman with a wild dark mane, small horns, mauve-and-black gown, a broken coin in one hand. Fully clothed. Dice and spilled wine at her feet, not blood.",
        "Luck's cruel sister. She arrives when you say it cannot get worse.",
        "Beshaba is Tymora's opposite and will not let anyone forget it. Where Tymora winks, Beshaba trips the stool. Sailors on the Chionthar spit if her name is said aboard.\n\nHer clerics do not heal. They arrange. A rope frays. A watchman looks left. A 'lucky' charm is hers if it was never paid for.\n\nAt the table she is a timer. If the party boasts, she is listening. If they leave an offering of spilt wine and a broken tool at a crossroads, she may torment someone else tonight.",
        "Do not toast luck in her hearing. Leave a little disaster on purpose so she does not invent a large one.",
        ["Every lockpick in the party has snapped in the same week. A mauve ribbon was tied to the last one.", "A gambling house in the Lower City has had three 'impossible' losing streaks. The dealer wears antler pins."],
    ),
    (
        "baldur", "bhaal", "Bhaal", "Lord of Murder, the Dread Lord, Faerûn's last knife",
        "neutral evil", "War, Trickery", "A skull surrounded by a ring of bloody droplets, or a dagger laid on a palm",
        "greater",
        "A bald, severe man in close black-and-crimson robes, ritual dagger reversed against his palm, calm as a clerk. No open wounds. A dim stone chapel, candles, a floor-mosaic of a skull.",
        "Murder as vocation. Not rage. A calling.",
        "Bhaal is the Dead Three's knife. Baldur's Gate has never been rid of him. His name is on the city's oldest panic and its newest alley. He does not want a battlefield. He wants a person who was alive this morning and is not, and a reason that belongs to him.\n\nBhaalists keep lists. They prefer murders that teach a city to flinch. A cleric of Bhaal at the table is not a berserker. They are patient. They ask who would be most useful dead.\n\nHis return is a rumor that keeps being true. If the party finds a shrine of still-wet palms, they have found work whether they wanted it or not.",
        "A drop of blood on a stone. A name spoken once. Do not kill in anger; that is someone else's domain. Kill as an offering.",
        ["Seven victims in the Lower City, no theft, each left with a clean palm-cut. The Flaming Fist wants it quiet. Bhaal wants it famous.", "A child of Bhaal is hiding in a temple of another god, trying not to be a prophecy. Both churches will pay. Neither will tell you the truth."],
    ),
    (
        "baldur", "corellon", "Corellon Larethian", "Creator of the Elves, First of the Seldarine, Coronal of Arvandor",
        "chaotic good", "Light, War, Knowledge", "A crescent moon, a starburst, or an artist-warrior's longsword",
        "greater",
        "An androgynous elf in pearl and leaf-green silk, a painter's brush in one hand and a slender sword in the other, starlight in the hair. Fully clothed, ageless, slightly amused.",
        "Art as a way of fighting, and fighting as a way of remaining beautiful.",
        "Corellon made the elves and has been arguing with the result ever since. Lolth is the argument that went to war. He is worshipped in Baldur's Gate wherever elves still keep a shrine that is also a studio.\n\nClerics of Corellon bless a blade the way they bless a song: it should be excellent. They dislike ugliness more than they dislike evil, which gets them in trouble with paladins.\n\nAt the table he is a patron of daring. A plan that is clever and a little theatrical may receive help. A plan that is merely efficient may not.",
        "Make something before you ask. A sketch, a verse, a clean kill. Do not worship him with copied work.",
        ["An elven shrine in the Upper City was vandalized with spider-sign. Corellon's priest wants the web cut before dawn, quietly.", "A stolen painting is a door. Someone walked through it. The frame is still warm."],
    ),
    (
        "baldur", "cyric", "Cyric", "Prince of Lies, the Dark Sun, the Mad God",
        "chaotic evil", "Trickery, War", "A white jawless skull on a dark sunburst, or a black sun",
        "greater",
        "A lean, fever-eyed man in black and purple, a pale skull-mask pushed up on his brow like a hat he forgot, smiling at a joke no one else heard. Fully clothed. A shattered altar behind him.",
        "Madness with a press office. Lies that become true if enough people repeat them.",
        "Cyric murdered his way into godhood and has been rewriting the minutes ever since. He hates the other gods the way a forger hates a signature. Baldur's Gate hears him as rumor: a new prophet every season, a pamphlet that contradicts itself and still sells.\n\nHis clerics cannot be trusted, including by each other. That is the point. A Cyricist at the table is a plot device that walks.\n\nUse him when the party needs an enemy who will betray their own side for the poetry of it.",
        "Swear on a lie and keep the lie until it hardens. Never tell the same story twice.",
        ["A street preacher in the Wide is telling three versions of the party's last job. All of them are almost true. One of them will get someone hanged.", "A holy book of Cyric was found blank. Words appear when a specific person lies. The Flaming Fist has that person in a cell."],
    ),
    (
        "baldur", "gond", "Gond", "Wonderbringer, the Holy Maker, Lord of All Smiths",
        "neutral", "Knowledge, War", "A toothed cog, a smith's hammer on an anvil, or a mechanical arm",
        "greater",
        "A stout craftsman in a leather apron over good clothes, one forearm a beautiful brass-and-steel mechanism, hammer in the living hand, a workbench of unfinished wonders. No text on the tools. Sparks, concentration.",
        "Invention as worship. If it works, it is a prayer that passed.",
        "Gond is the god of making things that did not exist this morning. Lantan loves him. Baldur's Gate keeps a High House of Wonders and a street full of people who think a better lock is a moral act.\n\nGondians will bless a firearm, a clock, a prosthetic, a mill. They will not bless a tool they cannot take apart. A cleric of Gond at the table is the reason the party has a device with a nickname.\n\nHe is not kind about shoddy work. A miracle that is also sloppy offends him more than a crime that is well built.",
        "Offer a working model, not a speech. Break nothing you cannot improve.",
        ["The High House of Wonders is missing a prototype that walks. It was last seen heading for the sewers with a child's drawing of a map.", "A Gondian will arm the party if they retrieve a crate of smokepowder from a ship that is on fire in a useful way."],
    ),
    (
        "baldur", "gruumsh", "Gruumsh", "One-Eye, He Who Never Sleeps, the Great God of the Orcs",
        "chaotic evil", "War, Tempest", "A single unblinking eye, or a bloodied spear",
        "greater",
        "A massive orc war-chief in hide and iron, left eye a ruin, right eye burning, spear taller than a man, a storm behind the camp. Clothed, furious, not a caricature.",
        "The god who was denied a seat and took a continent instead.",
        "Gruumsh is the orc answer to every other god's map. He does not want a temple with pews. He wants the next hill. On the Sword Coast his name is a warning in the Wood of Sharp Teeth and a recruiting poster in the wrong taverns.\n\nClerics of Gruumsh bless the first charge and the last stand. They do not write doctrine. They remember grudges.\n\nAt the table he is a war-band with theology. A party that treats orcs as scenery will meet his eye. A party that treats an orc as a person may still have to fight the god.",
        "Take something that was refused. Do not blink. The spear is the prayer.",
        ["An orc war-priest is offering a truce if the party blinds a statue of Corellon in the Upper City. He is telling most of the truth.", "A one-eyed raven has been circling the camp. It drops spearheads. They are warm."],
    ),
    (
        "baldur", "helm", "Helm", "The Watcher, He of the Unsleeping Eyes, the Vigilant",
        "lawful neutral", "War, Life", "An open staring eye on a gauntlet, or a full helm with no visor-slit you can find",
        "greater",
        "A still figure in unadorned full plate, helm down, a large eye-device on the shield, standing a watch that has no end of shift. No face. Only the feeling of being seen.",
        "Duty after the reason for the duty has gone home.",
        "Helm is the god of the door that stays shut because someone has to. He is not kind and he is not cruel. He is the watch. Baldur's Gate understands him: walls, fists, harbors, the feeling that if you look away the city will be stolen.\n\nHis clerics take shifts seriously. They will guard a thing they dislike if they swore to. They will not abandon a post because the party has a better plan.\n\nAt the table Helm is a lock. A Helmite NPC is the one who will not be bribed and will not be hurried. If the party is the watch tonight, they are doing his work whether they pray or not.",
        "Stand the watch you named. Do not sit. Do not close both eyes. A report is a prayer.",
        ["A Helmite has been on the same wall for three days without relief. He will not leave. Something on the far side of the wall does not want him to.", "The party is hired to watch a door until dawn. Helm will know if they dice."],
    ),
    (
        "baldur", "ilmater", "Ilmater", "The Crying God, the Broken God, Our Martyred Father",
        "lawful good", "Life, War", "A pair of white hands bound with red cord, or a rack that has been made into a stretcher",
        "greater",
        "A gentle, worn man in simple white robes, wrists wrapped in clean red cord, sitting among the injured with a bowl of water. No torture display. Compassion, not spectacle.",
        "Suffering taken on purpose so someone else does not have to.",
        "Ilmater is the god the Sword Coast calls when the pain is already here. His priests run infirmaries, orphanages, and the kind of quiet that makes tyrants nervous. In Baldur's Gate they are in the Lower City because that is where the bones break.\n\nAn Ilmatari cleric will take a wound for a stranger. They will also stand up after. The faith is not suicide. It is the decision that the party does not get to leave a child on the road.\n\nAt the table he is the reason a paladin of pain is not a joke. He is also the reason a villain who tortures for fun has made a very specific enemy.",
        "Bind a wound. Take one more than your share. Do not make a theatre of it.",
        ["An Ilmatari hospice in the Lower City is being taxed by a gang 'for protection.' The priests will not fight. They will ask the party to.", "A bound-hands symbol appeared on a Flaming Fist shield overnight. The wearer has started taking hits for civilians without being asked."],
    ),
    (
        "baldur", "jergal", "Jergal", "Lord of the End of Everything, Scribe of the Doomed, the Pitiless One",
        "lawful neutral", "Knowledge, Trickery", "A jawless skull and a writing quill, or a scroll sealed in bone-wax",
        "lesser",
        "An impossibly old, dry figure in grey-green scribe's robes, skull-lean face, a ledger and a quill, no drama. A quiet crypt-office. Clothed, dust-scented, precise.",
        "Death as paperwork. He did the job before the Dead Three, and he still keeps the books.",
        "Jergal was the end of all things and then he was bored. He gave Bane, Bhaal, and Myrkul their portfolios the way a clerk hands over keys. He stayed on as the scribe.\n\nIn Baldur's Gate his shrines are small and accurate. A name, a date, a cause. His clerics do not raise the dead to be kind. They record why the dead should stay so.\n\nAt the table he is a source. If you need to know who died and whether it counted, you ask Jergal. He will tell you. He will not comfort you.",
        "Write the name correctly. Do not omit a title. Ink is the offering.",
        ["A ledger in a tomb lists the party — one name ahead of today's date. The ink is still wet.", "Jergal's priest will identify a body if the party fetches the true name of a man who has been using three."],
    ),
    (
        "baldur", "kelemvor", "Kelemvor", "Lord of the Dead, Judge of the Damned, the Great Guide",
        "lawful neutral", "Life, Knowledge", "An upright skeletal arm holding scales, or a balanced scale over a grave",
        "greater",
        "A stern, living man in grey scale and a dark cloak, a judge's bearing, a simple crown of pale metal, scales at his hip. Not a skeleton. A man who has a job among the dead.",
        "Death as a fair gate. No torment for its own sake. No bargains that skip the line.",
        "Kelemvor took the dead from Myrkul's cruelty and made a court. The Sword Coast prefers him when they think about it, which they try not to. His clergy bury people properly and hate undeath the way a mason hates a crooked wall.\n\nA cleric of Kelemvor at the table will walk into a haunted house and start taking names. They are not grim for fashion. They are busy.\n\nIf the party wants a loved one back, Kelemvor's answer is almost always no. If the party wants a lich undone, the answer is yes, and here is the form.",
        "Bury the named. Burn the nameless if you must. Do not pay a necromancer to skip the queue.",
        ["A graveyard in Rivington has empty holes and no bodies. Kelemvor's scale at the gate is tilted. Someone is selling funerals twice.", "A paladin of Kelemvor will join for one job: a talking skull in a wizard's study that refuses to be judged."],
    ),
    (
        "baldur", "lathander", "Lathander", "The Morninglord, Commander of Creativity, Inspiration's Dawn",
        "neutral good", "Light, Life", "A rosy-gold sun rising over a disk, or a phoenix in dawn colors",
        "greater",
        "A youthful, rosy-gold man in cream and pink-gold vestments, open hands, a sun-disk at his breast, dawn over a harbor. Fully clothed, hopeful, not naive.",
        "Sunrise as a policy. Beginnings, and the stubbornness to begin again.",
        "Lathander is the most popular good god on the Sword Coast for a reason: he is the morning after. Temples of the Morninglord are pink stone, choirs, and people who genuinely believe the next day can be better than this one.\n\nIn Baldur's Gate his church is wealthy, political, and sometimes infuriating. A Lathanderite will try to redeem a villain the party wanted to end. They will also stand in a doorway at dawn and make a darkness-cult blink.\n\nAt the table he is light you can plan around. His miracles like new starts: a second wind, a city gate opening, a child born on the right side of a war.",
        "Be there at dawn. Light something that was dark. Do not confuse optimism with blindness — but do not skip the optimism.",
        ["The temple's dawn service was silent. The sun-disk would not catch the light. Something in the cellar is holding the morning.", "A Lathanderite novice saw the party's future in a sunrise and will not stop following them. She is correct about one thing."],
    ),
    (
        "baldur", "lolth", "Lolth", "Queen of Spiders, Demon Queen of the Abyss, Weaver of Destiny",
        "chaotic evil", "Trickery, War", "A black widow, a female drow spider-face, or a webbed silver star",
        "greater",
        "A beautiful drow woman in structured spider-silk armor and a high collar, a living spider as a brooch, cruel amusement, a suggestion of more legs in the shadow behind her. Fully clothed. No gore.",
        "Betrayal as doctrine. The web is the church, and the church eats its own.",
        "Lolth is the reason drow houses keep knives under the dinner plates. She was Corellon's until she was not. Baldur's Gate meets her as rumor from below: a shrine in the Undercellar, a merchant who never blinks together, a deal that was always a trap.\n\nHer clerics are almost always women of the faith as the Spider Queen prefers it. They test loyalty by breaking it. A Lolthite ally is a countdown.\n\nAt the table she is underground politics. If the party goes beneath the city, they are in her weather.",
        "Offer a betrayal that is elegant. A clumsy murder offends her. The web should still look like a web after.",
        ["A drow envoy in the Upper City claims to have left Lolth. She has not. She will pay the party to prove she has.", "Webs in the sewers form letters. They spell a party member's name, then another, then a time."],
    ),
    (
        "baldur", "loviatar", "Loviatar", "Maiden of Pain, the Willing Whip, patron of the hurt that is chosen",
        "lawful evil", "War, Trickery", "A nine-stranded whip, or a dagger through a pale rose",
        "lesser",
        "A severe, pale woman in a high-necked black gown with silver piping, a coiled ceremonial whip at her belt like a badge of office, composed, unsmiling. Fully clothed. A cold chapel, not a dungeon peep-show.",
        "Pain as a language. She is not chaos. She is a curriculum.",
        "Loviatar is the god of hurt that is meant. Her clergy keep rules. They are not Bhaal. They do not want you dead. They want you to remember.\n\nIn Baldur's Gate she has small, expensive shrines and a reputation the city uses as a joke until someone comes back quieter. A cleric of Loviatar at the table is a specialist: interrogation, endurance, the breaking of a siege of the will.\n\nKeep her cold and lawful. She is worse that way.",
        "Do not scream unless it is part of the rite. A clean line is a prayer. Cruelty without craft is amateur.",
        ["A merchant's 'debts' are being collected by a woman with a silver-handled whip who never raises her voice. The merchant wants her stopped. He will not say what he bought.", "A paladin of Ilmater and a priestess of Loviatar have claimed the same wounded soldier. The soldier can still choose."],
    ),
    (
        "baldur", "mask", "Mask", "Lord of Shadows, Master of All Thieves, the Unseen",
        "chaotic neutral", "Trickery, Knowledge", "A black velvet mask, or a coin half in shadow",
        "lesser",
        "A slim figure in black with gold-thread edges, a half-mask of dark wood, one visible eye amused, a gloved hand empty on purpose. Fully clothed. A rooftop, a moon, a city that has not noticed.",
        "Theft as a sacrament. Shadows as a guildhall.",
        "Mask is the god every thief in Baldur's Gate thanks and none of them admit. He is the reason a purse is gone and the reason a secret is worth more than the purse. His clergy are rare in public and thick in the Guild.\n\nA cleric of Mask at the table is a specialist who will not steal from the party unless the party makes it interesting. He prefers a job that is also a story.\n\nHe has died and come back the way a rumor does. If you see his mask on a hook, do not put it on unless you mean to keep it.",
        "Leave a coin in a shadow. Steal only what was guarded. A gift that was not missed is not a prayer.",
        ["The Guild's tithe-box was stolen. Only Mask's people could have done it. Mask's people are angry, which means someone new is in town.", "A mask of black wood fits the face of one party member and no one else. It whispers a job. The job is real."],
    ),
    (
        "baldur", "mielikki", "Mielikki", "Our Lady of the Forest, the Forest Queen, daughter of Silvanus in all but blood",
        "neutral good", "Nature, Life", "A unicorn's head, a white stag, or a walking-staff of living oak",
        "lesser",
        "A tall huntress in green and brown leathers, cloak of leaves, a longbow unstrung, a pale unicorn at her shoulder in the trees. Fully clothed. A sun-dapple, not a trophy-wall.",
        "The forest as a home, not a resource. Rangers' first name.",
        "Mielikki keeps the woods that still remember being woods. On the Sword Coast that is a shrinking parish: the Cloakwood, the edges of the Wood of Sharp Teeth, any park the Upper City has not paved.\n\nHer clerics and rangers overlap. They will guide a party. They will not guide a logging camp. A unicorn is not a mount. If you see one, you are being evaluated.\n\nAt the table she is the wild that can still be kind. If the party camps clean, the night is easier. If they chop a standing stone for firewood, the night has opinions.",
        "Leave the camp as you found it. Water a tree that is dying. Do not put a bit in a unicorn's mouth, even in a story.",
        ["The Cloakwood is walking toward the city by a few yards a night. Mielikki's ranger says it is looking for someone the party already met.", "A white stag in the Lower City at dawn. It should not be here. It will lead the party once. Then it will not."],
    ),
    (
        "baldur", "moradin", "Moradin", "The Soul Forger, Dwarffather, the All-Father of the dwarves",
        "lawful good", "Knowledge, War", "A hammer and anvil, or a soul being drawn from stone",
        "greater",
        "A broad dwarf in work-scarred royal armor, white beard forked and bound in gold, hammer across an anvil that glows from within. A forge-hall, not a battlefield. Clothed, concentrated, kind around the eyes.",
        "Making a people the way you make a good axe: heat, patience, and no lies about the metal.",
        "Moradin forged the dwarves and still checks the work. His temples are foundries. Baldur's Gate has a dwarven quarter that smells of coal and oaths.\n\nA cleric of Moradin will bless a tool, a marriage, a gate-bar. They dislike unfinished business and unfinished blades equally.\n\nAt the table he is craft and clan. If the party keeps their word to a dwarf, they have a god on the side of the contract. If they cheapen the metal, they have a problem that will not rust away.",
        "Work the bellows. Name the thing you are making. Do not swear an oath you will not stamp.",
        ["A clan-hammer was sold to a collector in the Upper City. Moradin's priest will not buy it back. He wants it taken, then re-forged.", "A new vein under the city sings when struck. The dwarves say it is a door. The Gondians say it is ore. Both are a little right."],
    ),
    (
        "baldur", "myrkul", "Myrkul", "Lord of Bones, Old Lord Skull, the Reaper",
        "neutral evil", "Trickery, Knowledge", "A white skull on a black field, or a scythe of bone",
        "greater",
        "A crowned skeletal figure in intact royal robes of black and bone-white, not naked bone, a scythe grounded like a sceptre. A dry mausoleum. Regal, not dripping.",
        "Death as a kingdom. He wants the dead afraid of him, and the living late.",
        "Myrkul is the Dead Three's crown. Where Kelemvor made a court, Myrkul made a fear. He is the old way of dying: bribes, bones, and a god who liked you scared.\n\nHis cult in Baldur's Gate hides in crypts that were supposed to be empty. A Myrkulite cleric raises what Kelemvor would put down. They speak softly. The dead lean in.\n\nAt the table he is undeath with manners. A skull that talks. A tax on graves. A promise that dying will not be the end of your problems.",
        "A bone, named. A fear, admitted. Do not bury anyone important without his cut — or do, and see what stands up.",
        ["A charnel house is paying better than the temple of Kelemvor for the same bodies. The difference is what happens after sunset.", "Old Lord Skull has a new priest who is still alive and would prefer to stay that way. He will sell the cult for a true burial."],
    ),
    (
        "baldur", "mystra", "Mystra", "The Lady of Mysteries, Mother of All Magic, the Weave",
        "lawful neutral", "Knowledge, Light", "A circle of seven stars, or a single star over a misty road",
        "greater",
        "A composed woman in layered blue-white robes that look woven from faint light, a circlet of seven small stars, hands open as if holding an invisible thread. Fully clothed. A night library, not a battlefield.",
        "Magic as a law of nature she happens to be. Break the law, and she feels it.",
        "Mystra is the Weave. Spellcasters on the Sword Coast work in her weather whether they pray or not. Baldur's Gate has always had too many wizards for one city's good; her church tries to keep them from burning the docks.\n\nA cleric of Mystra is a mage with a conscience, or a conscience with a spellbook. They dislike wild magic the way a sailor dislikes a hole in the hull.\n\nAt the table she is the reason magic has rules. If the party rips a hole in the Weave, her people will arrive with questions and a net.",
        "Cast cleanly. Teach what you can. Do not hoard a spell that would save a street. Do not give a spell to a fool.",
        ["A dead-magic alley has opened in the Lower City. Mystra's star-circle at the temple is missing one point.", "A young sorcerer is bleeding Weave. Both Mystra's church and a Banite cell have offers. The sorcerer wants to live through the night."],
    ),
    (
        "baldur", "oghma-binder", "Oghma", "Binder of What is Known, Lord of Knowledge, the Wise God",
        "neutral", "Knowledge, Trickery", "A blank scroll, a silver collar of a bard, or an unopened book",
        "greater",
        "A keen-eyed scholar in rich but practical robes, a blank book bound in pale leather, a half-smile of someone who already read the ending. Fully clothed. A library with too many candles.",
        "Knowledge as a living thing. He wants it bound, named, and not set on fire.",
        "This is the Oghma of Baldur's Gate: patron of bards, wizards, clerks, and anyone who thinks a fact should outlive a king. His temple in the city is a place you go when the rumor has too many versions.\n\nAn Oghmanyte cleric will copy a dying man's last words and then argue about the punctuation. They are the party's librarian and, if you are not careful, its leak.\n\nAt the table he is information with a price. The price is often that you must tell the truth in return.",
        "Leave a true account. Do not burn a book to hide a crime — he will know the smoke. A song that teaches counts.",
        ["A book in the temple has started writing the party's private conversations. Oghma's priest wants to know who bound a spy into the paper.", "The Binder will trade a map of a vault for a story the party has been refusing to tell."],
    ),
    (
        "baldur", "selune", "Selûne", "The Moonmaiden, She Who Guides, Our Lady of Silver",
        "chaotic good", "Life, Knowledge, Light", "A pair of female eyes surrounded by seven silver stars, or a crescent moon",
        "greater",
        "A woman of changing age in silver-white, moon-pale hair, a crescent at her brow, standing on a balcony over a night harbor. Fully clothed. Kind, not fragile. Stars, not glare.",
        "The moon as a lantern for people who have to walk at night.",
        "Selûne is Shar's sister and opposite. Where Shar wants the dark to be empty, Selûne wants it to be navigable. Sailors, lycanthropes who are trying, and anyone lost on the Coast Way keep her.\n\nIn Baldur's Gate her house is a lighthouse of a church. Her clerics heal, guide, and feud with Sharrans in ways the city pretends not to see.\n\nAt the table she is a night that helps. A moonlit path. A wolf that did not bite. A dream that is a map.",
        "Walk by moonlight once without a torch. Help someone find the shore. Do not hide from your own night.",
        ["The moon over the harbor went black for an hour and no one in the Upper City noticed. The Lower City did. Selûne's priestess is already packing.", "A werewolf in a Selûne shrine wants to be cured before the next full moon. Shar's people have the same appointment."],
    ),
    (
        "baldur", "shar", "Shar", "Mistress of the Night, Lady of Loss, Nightsinger",
        "neutral evil", "Trickery, Knowledge", "A black disk with a purple border, or a circle of darkness inside a circle",
        "greater",
        "A pale, beautiful woman in structured black and deep purple, a void-disk at her throat, eyes that do not reflect the candles. Fully clothed. A windowless chapel, one black candle.",
        "Loss as a sacrament. Forgetfulness as mercy she will charge for.",
        "Shar is the night with the lanterns taken away. She is Selûne's twin and the older wound. Baldur's Gate has always had Sharrans: grief-cults, spy-rings, people who would rather not remember a name.\n\nA cleric of Shar at the table offers to take a memory. That is not a metaphor. The price is real and the hole it leaves is useful to her.\n\nShe is patient. Her plots are the ones that were already running when the party arrived. If a house has no mirrors, ask why.",
        "A secret kept. A light put out on purpose. Do not pray in moonlight. She is the dark between the stars, not the stars.",
        ["A whole street forgot the same man. His bills still arrive. Shar's disk was painted on his door from the inside.", "A Sharran will fund the party's job if they retrieve a song that makes listeners forget the last hour. The song is already in a bard's head."],
    ),
    (
        "baldur", "silvanus-oak", "Silvanus", "Oak Father, the Forest Father, Treefather",
        "neutral", "Nature, Tempest", "A green oak leaf, a summer oak, or a wooden staff in leaf",
        "greater",
        "A huge, oak-bearded man in living bark and leaf-cloak, staff rooted to the earth, eyes like a canopy. The city is small behind him. Clothed in the forest itself.",
        "The wild that does not negotiate. Balance, including the kind that eats farms.",
        "This is the Silvanus of the Sword Coast woods, not the old Celtic name on another page. He is the oak that was here before Baldur's Gate and will be here after, if the Gate is not careful.\n\nHis druids dislike cities. They will still walk into one if a river is being killed. A cleric of Silvanus at the table is weather, beasts, and a refusal to pave.\n\nHe is not sweet. A wolf pack is his choir. A blighted field may be a correction.",
        "Plant what you cut. Do not name a tree after a king. Blood in the soil is a last resort, not a fertilizer plan.",
        ["The oak in the Wide is older than the city and has started shedding leaves in the wrong season. Silvanus wants a conversation under it at midnight.", "A logging charter for the Cloakwood has a forged seal. The trees have already started the trial."],
    ),
    (
        "baldur", "sune", "Sune", "Firehair, Lady Firehair, goddess of love and beauty",
        "chaotic good", "Life, Light", "A face of a red-haired woman, or a rose in flame-gold",
        "greater",
        "A stunning red-gold-haired woman in elegant rose-red silk, a single perfect rose, a painter's warmth, laughing as if the room improved. Fully clothed, glamorous, not a pin-up.",
        "Beauty as a duty to the world. Love as a risk she still recommends.",
        "Sune is the reason Baldur's Gate has fountains that are nicer than they need to be. Her temples teach that making a place lovely is not vanity. It is resistance to despair.\n\nA cleric of Sune will heal a scar if you want it gone and leave it if it is a story you are proud of. They dislike ugliness that is cruel, not ugliness that is honest.\n\nAt the table she is charm with a spine. Her people will walk into a tyrant's hall looking like a festival and refuse to be seated last.",
        "Make something beautiful today. Tell someone they are. Do not use beauty as a knife unless the other person brought a knife first.",
        ["A Sune shrine's mirror shows a party member as they could be if they forgave one person. The shrine wants that person found.", "Someone is throwing acid on public art. Sune's priestess will pay in healing and introductions."],
    ),
    (
        "baldur", "talona", "Talona", "Lady of Poison, Mistress of Disease, She of the Deadly Kiss",
        "chaotic evil", "Trickery, Tempest", "Three amber teardrops on a purple triangle, or a vial and a thorn",
        "lesser",
        "A thin woman in layered green-black veils and gloves, a physician's satchel of sealed vials, a triangle-mark at her throat. Fully clothed. A clean, wrong infirmary. No rotting bodies.",
        "Plague as a sermon. Poison as a signature.",
        "Talona is the cough that becomes a street. Baldur's Gate has had her summers. Her cult travels with caravans and with doctors who smile too much.\n\nA cleric of Talona at the table is a biological problem. They may sell the antidote to the thing they started. That is the faith.\n\nKeep her clinical. She is scarier as a pharmacist than as a monster.",
        "A drop in a well is a hymn. A measured dose is a better hymn. Random slaughter bores her.",
        ["The Lower City has a new fever that only hits people who visited one tavern. Talona's triangle is under the bar. The barkeep is already dying and still serving.", "A Talonite will halt an outbreak for a relic. The relic is a child's doll that has never been washed."],
    ),
    (
        "baldur", "talos", "Talos", "The Destroyer, Stormlord, the Raging One",
        "chaotic evil", "Tempest, War", "Three lightning bolts from one point, or a storm-gauntlet",
        "greater",
        "A towering warrior in storm-dark armor, lightning caught in a raised fist, wreckage of a ship behind him on black water. Clothed in metal. Wrath, not gore.",
        "Destruction as weather. He is the storm that wants to be thanked.",
        "Talos is the Sword Coast's bad night. Lightning, wreck, riot, the roof coming off. His priests do not build. They wait for a storm and then take credit.\n\nIn Baldur's Gate he is a dockside god. Sailors bribe him. The rest of the city pretends the bribe is insurance.\n\nA cleric of Talos at the table is an artillery strike with a holy symbol. They are useful until they are not. Do not stand them next to a library of Gond.",
        "Break something that was too proud. Do it in weather. A whisper in a calm is not his.",
        ["Lightning hit the same warehouse three nights. Talos wants whatever is in the cellar brought outside and named.", "A storm-priest is offering to wreck a rival's ship. He will. He will not stop at one ship."],
    ),
    (
        "baldur", "tempus", "Tempus", "The Foehammer, Lord of Battles, the Lord of War",
        "chaotic neutral", "War, Tempest", "A blazing silver sword on a blood-red field, or a battered war-helm",
        "greater",
        "A huge, battle-worn warrior in notched plate, red cloak, a sword that has seen too many wars, standing on a field after the fight. Respect for the fallen. No torture. Clothed in war.",
        "War as a sacred craft. He loves the fight and hates the clerk who starts one from a desk.",
        "Tempus is the god of the battle, not the massacre. Cowards and butchers offend him. Brave enemies please him. Baldur's Gate keeps him in the barracks and in the heads of people who think a duel still means something.\n\nA cleric of Tempus will bless both sides of a fair war. They will walk away from an assassination and call it what it is.\n\nAt the table he is the honest fight. If the party wants a war-god who is not Bane, this is the one.",
        "Fight facing the foe. Spare the beaten. Do not poison a well and call it strategy in his hearing.",
        ["A Tempuran wants the party to referee a gang war so it stays a war and not a slaughter. Both gangs have already cheated.", "A sword on an altar will not come free until it has been used in a fight the god considers real. A tavern brawl does not count."],
    ),
    (
        "baldur", "tiamat", "Tiamat", "The Chromatic Dragon, Queen of Evil Dragons, the Dark Queen, the Avaricious",
        "lawful evil", "War, Trickery", "A five-headed dragon, or five colored gems in a claw",
        "greater",
        "A draconic queen in jeweled chromatic scale-mail, a five-colored crown, one claw on a hoard, five ghost-heads of dragon-fire in the smoke above her. Clothed in treasure. Greedy, imperial, not a pin-up.",
        "Greed with five throats. She wants the hoard, the throne, and the map to the next hoard.",
        "Tiamat is Bahamut's opposite and the reason chromatic dragons have a foreign policy. Her cult in Baldur's Gate is money, dragon-blooded ambitious people, and a rumor of a hidden shrine that smells like a mint.\n\nA cleric of Tiamat at the table will help if the take is large enough. They will eat the take. The contract should be read twice.\n\nShe is a lawful evil: hierarchies, tribute, color-coded grudges. Red is not green. Do not mix the books.",
        "Tribute in the correct color. A stolen hoard is a hymn. A shared hoard is a heresy.",
        ["Five colored coins were left on the party's table. Spending them summons a collector. The collector is polite.", "A Tiamat cult is funding both sides of a dock war. They want the warehouses empty so a dragon can nest. The dragon is not a metaphor."],
    ),
    (
        "baldur", "torm", "Torm", "The True, the Loyal Fury, Hand of Righteousness",
        "lawful good", "War, Life", "A gauntlet held upright, or a lion's head on a white field",
        "greater",
        "A handsome, earnest warrior in bright plate, lion-cloak, a gauntlet raised in oath, standing before a city gate at morning. Fully clothed. Duty you can like.",
        "Loyalty as a superpower. Paladins' other favorite, after the one who cries.",
        "Torm is the god of keeping the promise you made when you were still brave. He is popular with the Flaming Fist's better officers and with people who think Baldur's Gate could be a just city if someone insisted.\n\nA cleric of Torm will not abandon the party. That can be inconvenient. They will also not ignore a crime because it is useful.\n\nAt the table he is the lawful good that still goes into the sewer. He is not naive. He is stubborn.",
        "Swear with a gauntlet on a table. Then go. Do not leave a post. Do not leave a friend.",
        ["A Tormite just resigned from the Fist for refusing an order. He will tell the party the order if they walk with him to the person it would have hurt.", "An upright gauntlet appeared on a door in the Outer City. Behind the door is a child the city forgot. Torm has not."],
    ),
    (
        "baldur", "tymora", "Tymora", "Lady Luck, Our Smiling Lady, the Lady Who Smiles",
        "chaotic good", "Trickery, Light", "A silver coin with her face, or a shining featureless disk",
        "greater",
        "A laughing woman in traveling blue and silver, a coin walking across her knuckles, wink ready, a tavern behind her that is having a good night. Fully clothed. Warm, not drunk.",
        "Good fortune for people willing to roll. She likes a brave bet more than a safe prayer.",
        "Tymora is Beshaba's sister and the reason adventurers toast before a job. Baldur's Gate loves her: gambling houses, sailors, anyone whose plan has a fifty-fifty.\n\nA cleric of Tymora will bless a leap. They will not bless a ledger. If the party never takes a risk, she gets bored and her sister does not.\n\nAt the table she is the god of the second chance that still requires you to jump.",
        "Flip a coin and abide. Leave a silver in a fountain. Do not count cards in her house and then ask for a miracle.",
        ["A coin landed on its edge in the Elfsong and has not fallen. Tymora wants a question asked out loud. The answer will be expensive and correct.", "Lady Luck's priest will stake the party for a vault job if they let her roll the last die."],
    ),
    (
        "baldur", "tyr-evenhanded", "Tyr", "The Even-Handed, Grimjaws, God of Justice",
        "lawful good", "War, Knowledge", "A balanced scale resting on a warhammer, or a wounded-but-upright sword",
        "greater",
        "A missing-right-hand noble warrior, eye-patch, warhammer in the remaining fist, scales on a chain at his belt, a court-hall that is also a barracks. Clothed, grim, fair.",
        "Justice that paid in advance. He already gave the hand and the eye. You can give the truth.",
        "This is the Tyr of Baldur's Gate, cousin in spirit to the northern one-hand on another page. He is the court that does not sell. His clergy keep law when the city would rather keep convenience.\n\nA cleric of Tyr at the table will insist on a trial even when a knife would be faster. They are exhausting. They are how a party stays the good side.\n\nHe is missing a hand because an oath cost it. Mention that if you want a paladin to sit up straight.",
        "Tell the truth in a hall. Return what was stolen to the person it was stolen from, not to a fence. A maimed oath is still an oath.",
        ["A magistrate of Tyr was found with his scales stuffed with coin. He says he did not do it. The scales still balance. That is the problem.", "Tyr's hammer on an altar will not lift for anyone who is lying about why they came. The party has to pick a spokesperson."],
    ),
    (
        "baldur", "umberlee", "Umberlee", "The Bitch Queen, Queen of the Depths, the Wavemother",
        "chaotic evil", "Tempest, Trickery", "A forked blue-green wave, or a drowning hand and a shark",
        "greater",
        "A wrathful sea-queen in kelp-dark silk and foam-white, crown of coral, the harbor storming behind her. Fully clothed in the sea. Beautiful the way a reef is beautiful: you do not grab it.",
        "The sea as a god who wants to be paid. Drowning is the invoice.",
        "Umberlee has a Water Queen's House on the Baldur's Gate docks because the city is not stupid. Ships leave a cut. Storms still happen. The cut is not a guarantee. It is a maybe.\n\nA cleric of Umberlee at the table is a maritime problem. They can calm a bay. They can also take a person who skipped the tithe.\n\nShe is not a metaphor for 'nature.' She is a queen with a temper and a lot of water.",
        "Gold into the harbor. A true fear of the deep. Do not whistle a storm down unless you can put it back.",
        ["A ship refused the Water Queen's cut and arrived anyway. Umberlee wants to know who blessed it. The blessing smells like Selûne.", "Bodies have been coming in with the tide, all missing the same offering-coin. Someone is skimming the goddess."],
    ),
    (
        "baldur", "waukeen", "Waukeen", "Merchant's Friend, Liberty's Maiden, the Golden Lady",
        "neutral", "Knowledge, Trickery", "A gold coin with her face, or a pair of scales over a trade-road",
        "lesser",
        "A prosperous woman in travel-cut gold and green, a ledger and a sample-pouch, a smile that has done this deal before. Fully clothed. A market at peak hour, honest weights in the foreground.",
        "Trade as a holy road. She wants the caravan through, the contract clear, the coin moving.",
        "Waukeen is why Baldur's Gate has a philosophy of money that is not only greed. Her people bless markets, loans, and the idea that a city is a machine for moving goods.\n\nShe has been missing and returned, which the church treats the way a company treats a founder who came back from the dead: carefully.\n\nA cleric of Waukeen at the table will fund a job that increases trade and walk away from one that only burns a rival. They are the party's accountant with a holy symbol.",
        "A fair weight. A paid debt. A coin given to open a road, not to close one.",
        ["A Waukeenar will underwrite the party's expedition if they reopen a trade spur the Zhentarim 'closed.' The spur is a person.", "Gold coins in the counting-house have her face on both sides tonight. Spending them is fine. Hoarding them is not."],
    ),
]


def main() -> None:
    existing = json.loads(OUT.read_text())
    have = {row["id"] for row in existing}
    added = 0
    for pan, gid, name, aka, align, domains, symbol, rank, look, blurb, text, worship, hooks in GODS:
        if gid in have:
            existing = [row for row in existing if row["id"] != gid]
        existing.append(
            {
                "id": gid,
                "name": name,
                "aka": aka,
                "kind": pan,
                "pantheon": pan,
                "align": align,
                "domains": domains,
                "symbol": symbol,
                "rank": rank,
                "look": look,
                "blurb": blurb,
                "text": text,
                "worship": worship,
                "hooks": hooks,
            }
        )
        added += 1
        have.add(gid)
    existing.sort(key=lambda r: (str(r.get("name") or "").lower(), r.get("id") or ""))
    OUT.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n")
    print(f"wrote {len(existing)} gods ({added} Baldur's Gate)")


if __name__ == "__main__":
    main()
