#!/usr/bin/env python3
"""Write original Night City Datashard entries using Cyberpunk RED mechanics."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("/home/steelworth/projects/blightnet/data/datashard.json")


def hp(body, will):
    return 10 + 5 * ((int(body) + int(will)) // 2)


def rec(**kw):
    b, w = kw["body"], kw["will"]
    kw.setdefault("hp", hp(b, w))
    kw.setdefault("init", kw["ref"])
    kw.setdefault("humanity", max(10, kw["emp"] * 10 - kw.get("hum_cost", 0)))
    kw.pop("hum_cost", None)
    return kw


ROLES = {
    "Rockerboy": {
        "kind": "edgerunner",
        "trait": ("Charismatic Impact", "Works a room, a riot, or a broadcast until people move."),
        "gear": "Agent, guitar or vocoder, light armor, smash",
        "chrome": "Audio recorder, light tattoo, techhair",
        "weps": [("Heavy Pistol", "3d6 · ROF 2")],
        "skills": "Play Instrument {s} · Persuasion {s} · Wardrobe {s} · Evasion {e} · Handgun {h} · Streetwise {st}",
        "look": "stage leather, chrome mic, neon hair",
        "stats": {
            "street": dict(int=4, ref=6, dex=6, tech=4, cool=6, will=5, luck=5, move=6, body=5, emp=6, rank=2, sp="4/7"),
            "operator": dict(int=5, ref=6, dex=6, tech=5, cool=7, will=6, luck=6, move=6, body=5, emp=7, rank=4, sp="7/7"),
            "elite": dict(int=6, ref=7, dex=6, tech=5, cool=8, will=7, luck=6, move=6, body=6, emp=8, rank=6, sp="7/11"),
            "legend": dict(int=7, ref=7, dex=6, tech=6, cool=8, will=8, luck=7, move=6, body=6, emp=8, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "A club kid with a stolen amp and a following of twenty. Dangerous because they believe it.",
            "operator": "Books their own nights, owns a van, and can start a riot with a chorus.",
            "elite": "Citywide name. Corps want the image. Boosters want the real thing dead.",
            "legend": "A voice the Time of the Red still quotes. One set can empty a block or fill it.",
        },
    },
    "Solo": {
        "kind": "edgerunner",
        "trait": ("Combat Awareness", "Reads a firefight a heartbeat early. Moves like they already saw the round."),
        "gear": "Heavy armorjack, spare magazines, smoke grenade",
        "chrome": "Sandevistan or Kerenzikov, targeting cybereye, grafted muscle",
        "weps": [("Very Heavy Pistol", "4d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
        "skills": "Handgun {h} · Autofire {s} · Evasion {e} · Athletics {s} · Perception {p} · Stealth {st}",
        "look": "tactical jacket, shoulder holster, cold eyes",
        "stats": {
            "street": dict(int=3, ref=7, dex=6, tech=3, cool=6, will=5, luck=4, move=6, body=6, emp=4, rank=2, sp="7/11"),
            "operator": dict(int=4, ref=8, dex=6, tech=4, cool=7, will=6, luck=5, move=6, body=7, emp=4, rank=4, sp="11/11"),
            "elite": dict(int=5, ref=8, dex=7, tech=4, cool=8, will=7, luck=5, move=7, body=8, emp=3, rank=6, sp="13/15"),
            "legend": dict(int=6, ref=8, dex=7, tech=5, cool=8, will=8, luck=6, move=7, body=8, emp=3, rank=8, sp="15/18"),
        },
        "blurbs": {
            "street": "Fresh chrome, unpaid debts, and a pistol they still flinch with. Fast enough to matter.",
            "operator": "The crew's closer. Does not miss. Does not talk about the last job.",
            "elite": "A walking weapons permit. Corps keep a file. Street keeps a rumor.",
            "legend": "Night City still tells the story. The Solo in it is older, slower, and worse to fight.",
        },
    },
    "Netrunner": {
        "kind": "net",
        "trait": ("Interface", "Jacks in, slides past ICE, and burns architecture like it was always theirs."),
        "gear": "Cyberdeck, programs, virtuality goggles, light armor",
        "chrome": "Interface plugs, neural link, cybereye HUD",
        "weps": [("Very Heavy Pistol", "4d6 · ROF 1")],
        "skills": "Interface {s} · Electronics/Security {s} · Basic Tech {t} · Evasion {e} · Handgun {h} · Stealth {st}",
        "look": "cables, deck, visor glow, layered streetwear",
        "stats": {
            "street": dict(int=7, ref=6, dex=5, tech=6, cool=4, will=5, luck=4, move=5, body=4, emp=5, rank=2, sp="4/7"),
            "operator": dict(int=8, ref=6, dex=5, tech=7, cool=5, will=6, luck=5, move=5, body=4, emp=5, rank=4, sp="7/7"),
            "elite": dict(int=8, ref=7, dex=6, tech=8, cool=6, will=7, luck=5, move=6, body=5, emp=4, rank=6, sp="7/11"),
            "legend": dict(int=8, ref=7, dex=6, tech=8, cool=7, will=8, luck=6, move=6, body=5, emp=4, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "Rented deck, burned fingers, and a reputation for one clean breach.",
            "operator": "Runs architecture for pay. Keeps a kill switch. Never uses their own name on the Net.",
            "elite": "Corps hire them to hunt other runners. The ICE they write has a nickname.",
            "legend": "Blackwall-adjacent myth. If they jack in, the building notices first.",
        },
    },
    "Tech": {
        "kind": "edgerunner",
        "trait": ("Maker", "Fixes, breaks, or rebuilds gear in the field. Jury-rigs like it was the plan."),
        "gear": "Tool kit, agent, poor-quality weapons made excellent",
        "chrome": "Cybereye tools, implant toolhand, pain editor (light)",
        "weps": [("Shotgun", "5d6 · ROF 1"), ("Heavy Pistol", "3d6 · ROF 2")],
        "skills": "Basic Tech {s} · Cybertech {s} · Weaponstech {s} · Electronics {s} · Evasion {e} · Handgun {h}",
        "look": "work jacket, goggles, toolbelt, stained chrome",
        "stats": {
            "street": dict(int=6, ref=5, dex=5, tech=7, cool=4, will=5, luck=5, move=5, body=5, emp=5, rank=2, sp="4/7"),
            "operator": dict(int=6, ref=6, dex=5, tech=8, cool=5, will=6, luck=5, move=5, body=6, emp=5, rank=4, sp="7/11"),
            "elite": dict(int=7, ref=6, dex=6, tech=8, cool=6, will=6, luck=6, move=6, body=6, emp=5, rank=6, sp="11/11"),
            "legend": dict(int=8, ref=6, dex=6, tech=8, cool=7, will=7, luck=6, move=6, body=6, emp=6, rank=8, sp="11/13"),
        },
        "blurbs": {
            "street": "Garage genius. Will repair your iron for cash, parts, or a story.",
            "operator": "Crew tech. Keeps the guns honest and the van running through a firefight.",
            "elite": "Builds custom chrome the ripperdocs pretend they invented.",
            "legend": "Night City still drives machines they welded before the War.",
        },
    },
    "Medtech": {
        "kind": "trauma",
        "trait": ("Medicine", "Stabilizes the dying, patches chrome, and knows which clinics will not sell you."),
        "gear": "Medkit, airhypo, light armor, Agent",
        "chrome": "Medscanner, nasal filters, toxin binders",
        "weps": [("Heavy Pistol", "3d6 · ROF 2")],
        "skills": "First Aid {s} · Paramedic {s} · Surgery {s} · Perception {p} · Evasion {e} · Handgun {h}",
        "look": "street clinic coat, trauma bag, clean gloves",
        "stats": {
            "street": dict(int=6, ref=5, dex=5, tech=6, cool=5, will=6, luck=4, move=5, body=5, emp=6, rank=2, sp="4/7"),
            "operator": dict(int=7, ref=6, dex=5, tech=7, cool=5, will=7, luck=5, move=5, body=5, emp=7, rank=4, sp="7/7"),
            "elite": dict(int=7, ref=6, dex=6, tech=7, cool=6, will=7, luck=5, move=6, body=6, emp=7, rank=6, sp="7/11"),
            "legend": dict(int=8, ref=6, dex=6, tech=8, cool=7, will=8, luck=6, move=6, body=6, emp=8, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "Back-room stitcher. Saves lives the hospitals will not touch.",
            "operator": "Crew medic. Can keep a Solo standing through a magazine.",
            "elite": "Trauma-grade skill without the subscription. Corps want them on payroll.",
            "legend": "People in Night City owe this one a second life. Some pay. Some hunt.",
        },
    },
    "Media": {
        "kind": "edgerunner",
        "trait": ("Credibility", "A story they drop can start a riot, a raid, or a resignation."),
        "gear": "Agent, camera drone, press vest, recorder",
        "chrome": "Cybereye camera, audio recorder, hidden holster",
        "weps": [("Heavy Pistol", "3d6 · ROF 2")],
        "skills": "Perception {s} · Persuasion {s} · Composition {s} · Streetwise {st} · Evasion {e} · Handgun {h}",
        "look": "press vest, camera drone, rumpled coat",
        "stats": {
            "street": dict(int=6, ref=5, dex=5, tech=5, cool=6, will=5, luck=5, move=5, body=4, emp=6, rank=2, sp="4/7"),
            "operator": dict(int=7, ref=6, dex=5, tech=5, cool=7, will=6, luck=5, move=5, body=5, emp=7, rank=4, sp="7/7"),
            "elite": dict(int=7, ref=6, dex=6, tech=6, cool=8, will=7, luck=6, move=6, body=5, emp=7, rank=6, sp="7/11"),
            "legend": dict(int=8, ref=6, dex=6, tech=6, cool=8, will=8, luck=6, move=6, body=5, emp=8, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "Stringer with a drone and a death wish. The truth is a side hustle.",
            "operator": "Breaks stories that get people killed. Keeps a lawyer and a go-bag.",
            "elite": "Network face with street sources. One exposé can move a corp's stock.",
            "legend": "The Time of the Red still argues about their last piece. They have another.",
        },
    },
    "Exec": {
        "kind": "corpo",
        "trait": ("Teamwork", "Always has a team: fixer, solo, netrunner, and someone disposable."),
        "gear": "Excellent suit, Agent, corpo card, light armor under the silk",
        "chrome": "Biomonitor, nanotech, discreet cybereye",
        "weps": [("Excellent Heavy Pistol", "3d6 · ROF 2")],
        "skills": "Bureaucracy {s} · Persuasion {s} · Business {s} · Perception {p} · Evasion {e} · Handgun {h}",
        "look": "sharp suit, gold chrome, cold smile",
        "stats": {
            "street": dict(int=6, ref=5, dex=4, tech=4, cool=6, will=5, luck=5, move=5, body=4, emp=6, rank=2, sp="4/7"),
            "operator": dict(int=7, ref=5, dex=5, tech=5, cool=7, will=6, luck=6, move=5, body=5, emp=6, rank=4, sp="7/7"),
            "elite": dict(int=8, ref=6, dex=5, tech=5, cool=8, will=7, luck=6, move=5, body=5, emp=6, rank=6, sp="7/11"),
            "legend": dict(int=8, ref=6, dex=5, tech=6, cool=8, will=8, luck=7, move=6, body=6, emp=6, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "Junior suit with a gun they barely trained on and a team they cannot afford.",
            "operator": "Mid-level with a budget and a hit list. Smiles in meetings. Signs in blood.",
            "elite": "Division shark. The bodyguards are better than most Solos.",
            "legend": "Night City policy has their fingerprint on it. So do a lot of graves.",
        },
    },
    "Lawman": {
        "kind": "law",
        "trait": ("Backup", "Calls in more badges. The street knows when that radio clicks.",),
        "gear": "Kevlar, badge, cuffs, patrol iron",
        "chrome": "Cybereye, radio implant, subdermal armor",
        "weps": [("Very Heavy Pistol", "4d6 · ROF 1"), ("Shotgun", "5d6 · ROF 1")],
        "skills": "Handgun {h} · Athletics {s} · Perception {p} · Interrogation {s} · Evasion {e} · Criminology {s}",
        "look": "duty armor, badge, radio mic",
        "stats": {
            "street": dict(int=4, ref=6, dex=6, tech=3, cool=5, will=6, luck=4, move=6, body=6, emp=5, rank=2, sp="7/11"),
            "operator": dict(int=5, ref=7, dex=6, tech=4, cool=6, will=6, luck=4, move=6, body=7, emp=5, rank=4, sp="11/11"),
            "elite": dict(int=6, ref=7, dex=6, tech=4, cool=7, will=7, luck=5, move=6, body=7, emp=5, rank=6, sp="13/15"),
            "legend": dict(int=6, ref=8, dex=6, tech=5, cool=8, will=8, luck=5, move=6, body=8, emp=4, rank=8, sp="15/18"),
        },
        "blurbs": {
            "street": "Beat badge. Tired, armed, and one bad call from a riot.",
            "operator": "Detective or patrol sergeant. Knows which boosters to squeeze.",
            "elite": "Crisis team lead. Heavy armor, heavier backup.",
            "legend": "The name on the wall at the precinct. Still takes calls.",
        },
    },
    "Fixer": {
        "kind": "edgerunner",
        "trait": ("Operator", "Finds the job, the buyer, the gun, and the way out. For a cut."),
        "gear": "Long coat, Agent, holdout, cash in three currencies",
        "chrome": "Audio recorder, cybereye, hidden holster",
        "weps": [("Heavy Pistol", "3d6 · ROF 2")],
        "skills": "Streetwise {s} · Trading {s} · Persuasion {s} · Perception {p} · Evasion {e} · Handgun {h}",
        "look": "long coat, gold rings, agent in hand",
        "stats": {
            "street": dict(int=5, ref=5, dex=5, tech=4, cool=6, will=5, luck=6, move=5, body=4, emp=6, rank=2, sp="4/7"),
            "operator": dict(int=6, ref=6, dex=5, tech=4, cool=7, will=6, luck=6, move=5, body=5, emp=7, rank=4, sp="7/7"),
            "elite": dict(int=7, ref=6, dex=6, tech=5, cool=8, will=6, luck=7, move=6, body=5, emp=7, rank=6, sp="7/11"),
            "legend": dict(int=8, ref=6, dex=6, tech=5, cool=8, will=7, luck=8, move=6, body=5, emp=8, rank=8, sp="11/11"),
        },
        "blurbs": {
            "street": "Runs a corner and a rumor. Can get you a pistol by midnight.",
            "operator": "The number everyone has. Jobs come with strings. The strings have teeth.",
            "elite": "Moves cargo, people, and secrets. Night City runs on their voicemail.",
            "legend": "If it can be bought in 2045, they already have a buyer.",
        },
    },
    "Nomad": {
        "kind": "nomad",
        "trait": ("Moto", "Family, vehicles, and the open road. The pack arrives when they call."),
        "gear": "Dust coat, family patches, vehicle, long gun",
        "chrome": "Interface plugs, nasal filters, cybereye",
        "weps": [("Assault Rifle", "5d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
        "skills": "Drive Land {s} · Athletics {s} · Perception {p} · Tracking {s} · Evasion {e} · Autofire {h}",
        "look": "dust coat, family patches, desert chrome",
        "stats": {
            "street": dict(int=4, ref=6, dex=6, tech=5, cool=5, will=5, luck=5, move=6, body=6, emp=5, rank=2, sp="7/11"),
            "operator": dict(int=5, ref=6, dex=6, tech=6, cool=6, will=6, luck=5, move=6, body=7, emp=6, rank=4, sp="11/11"),
            "elite": dict(int=5, ref=7, dex=6, tech=6, cool=7, will=7, luck=6, move=7, body=7, emp=6, rank=6, sp="11/13"),
            "legend": dict(int=6, ref=7, dex=6, tech=7, cool=8, will=8, luck=6, move=7, body=8, emp=7, rank=8, sp="13/15"),
        },
        "blurbs": {
            "street": "Pack scout. Dust on the coat, family on the radio.",
            "operator": "Convoy lead. Knows every road out of Night City that still exists.",
            "elite": "War-chief material. The pack moves when they do.",
            "legend": "A family name painted on a dozen rigs. The city does not own them.",
        },
    },
}

TIER_SKILL = {
    "street": dict(s=10, e=8, h=10, p=8, st=8, t=10),
    "operator": dict(s=12, e=10, h=12, p=10, st=10, t=12),
    "elite": dict(s=14, e=12, h=14, p=12, st=12, t=14),
    "legend": dict(s=16, e=14, h=16, p=14, st=14, t=16),
}

TIER_REP = {"street": 2, "operator": 4, "elite": 6, "legend": 8}
TIER_HUM = {"street": 10, "operator": 20, "elite": 35, "legend": 50}


def role_entries():
    out = []
    for role, spec in ROLES.items():
        slug = role.lower()
        for tier, st in spec["stats"].items():
            sk = TIER_SKILL[tier]
            skills = spec["skills"].format(**sk)
            out.append(
                rec(
                    id=f"{slug}-{tier}",
                    name=f"{role} · {tier.title()}",
                    role=role,
                    rank=st["rank"],
                    kind=spec["kind"],
                    tier=tier,
                    rep=TIER_REP[tier],
                    int=st["int"],
                    ref=st["ref"],
                    dex=st["dex"],
                    tech=st["tech"],
                    cool=st["cool"],
                    will=st["will"],
                    luck=st["luck"],
                    move=st["move"],
                    body=st["body"],
                    emp=st["emp"],
                    sp=st["sp"],
                    weapons=[{"n": n, "d": d} for n, d in spec["weps"]],
                    skills=skills,
                    chrome=spec["chrome"],
                    gear=spec["gear"],
                    blurb=spec["blurbs"][tier],
                    traits=[{"n": spec["trait"][0] + f" {st['rank']}", "d": spec["trait"][1]}],
                    look=spec["look"],
                    hum_cost=TIER_HUM[tier],
                )
            )
    return out


MOOKS = [
    dict(id="boosterganger", name="Boosterganger", role="", rank=0, kind="street", tier="mook", rep=1,
         int=3, ref=6, dex=6, tech=2, cool=4, will=4, luck=3, move=6, body=6, emp=3, sp="0/4",
         weapons=[("PQ Heavy Pistol", "3d6 · ROF 2"), ("PQ Medium Melee", "2d6 · ROF 2")],
         skills="Brawling 10 · Handgun 10 · Athletics 8 · Evasion 8 · Intimidation 8",
         chrome="EMP threading, light tattoo, cheap grafted muscle",
         gear="Leathers, smash, 50eb",
         blurb="Chrome-hungry street muscle. Loud, fast, and already spending the pay.",
         traits=[("Pack Tactics", "They rush. If one drops, two more keep coming.")],
         look="ripped leathers, cheap chrome arms, neon tattoo", hum_cost=20),
    dict(id="boosterganger-hard", name="Hardened Booster", role="", rank=0, kind="street", tier="operator", rep=3,
         int=3, ref=7, dex=6, tech=3, cool=5, will=5, luck=3, move=6, body=7, emp=2, sp="7/11",
         weapons=[("Very Heavy Pistol", "4d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
         skills="Brawling 12 · Handgun 12 · Autofire 10 · Evasion 10 · Athletics 10",
         chrome="Sandevistan (budget), cybereye, wolvers",
         gear="Kevlar, extra mag, 200eb",
         blurb="The one the pack shuts up for. Has killed for chrome and will again.",
         traits=[("Chrome Rush", "Pushes speedware on the first round and does not stop.")],
         look="heavy chrome arms, scarred face, armored vest", hum_cost=35),
    dict(id="street-thug", name="Street Thug", role="", rank=0, kind="street", tier="mook", rep=0,
         int=3, ref=5, dex=5, tech=2, cool=3, will=3, luck=3, move=5, body=5, emp=4, sp="0/4",
         weapons=[("PQ Medium Pistol", "2d6 · ROF 2"), ("Brawling", "1d6 · ROF 2")],
         skills="Brawling 8 · Handgun 8 · Stealth 8 · Evasion 8 · Streetwise 8",
         chrome="None, or a cheap light tattoo",
         gear="Leathers, 20eb",
         blurb="Unaligned muscle. Mugging, lookout, or the first body in a firefight.",
         traits=[("Break", "If half the crew drops, they run.")],
         look="hoodie, cheap pistol, nervous eyes", hum_cost=0),
    dict(id="street-lieutenant", name="Street Lieutenant", role="Fixer", rank=2, kind="street", tier="operator", rep=3,
         int=5, ref=6, dex=5, tech=3, cool=6, will=5, luck=5, move=5, body=5, emp=5, sp="7/7",
         weapons=[("Heavy Pistol", "3d6 · ROF 2")],
         skills="Handgun 12 · Persuasion 12 · Streetwise 12 · Evasion 10 · Perception 10",
         chrome="Cybereye, hidden holster",
         gear="Kevlar, Agent, 300eb",
         blurb="Runs a block. Collects. Knows which booster to send and which cop to pay.",
         traits=[("Crew", "2d6 street thugs or boosters arrive in 1d6 rounds if they radio.")],
         look="nice jacket over armor, gold chain, agent", hum_cost=10),
    dict(id="scavenger", name="Scavenger", role="", rank=0, kind="street", tier="mook", rep=1,
         int=4, ref=5, dex=6, tech=5, cool=3, will=4, luck=4, move=6, body=5, emp=3, sp="0/4",
         weapons=[("PQ Shotgun", "5d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
         skills="Stealth 10 · Basic Tech 10 · Conceal 10 · Perception 10 · Evasion 8",
         chrome="Cybereye flashlight, nasal filters",
         gear="Carryall, bolt cutters, 40eb",
         blurb="Strips wrecks and people. The chrome comes off whether you agree or not.",
         traits=[("Ambush", "If they start hidden, first attack is at +2.")],
         look="filthy coat, toolbag, respirator", hum_cost=15),
    dict(id="scav-boss", name="Scav Crew Boss", role="", rank=0, kind="street", tier="operator", rep=3,
         int=5, ref=6, dex=6, tech=6, cool=5, will=5, luck=4, move=6, body=6, emp=3, sp="7/11",
         weapons=[("Shotgun", "5d6 · ROF 1"), ("Excellent Heavy Melee", "3d6 · ROF 2")],
         skills="Stealth 12 · Basic Tech 12 · Handgun 10 · Evasion 10 · Leadership 10",
         chrome="Subdermal armor, cybereye, toolhand",
         gear="Kevlar, van keys, 250eb",
         blurb="Runs a stripping crew. Sells parts to ripperdocs who do not ask.",
         traits=[("Strip Job", "If a target is downed, the crew spends a round taking chrome.")],
         look="welder goggles, armored duster, bloody gloves", hum_cost=25),
    dict(id="club-bouncer", name="Club Bouncer", role="", rank=0, kind="civilian", tier="mook", rep=1,
         int=3, ref=5, dex=5, tech=2, cool=5, will=5, luck=3, move=5, body=8, emp=4, sp="4/7",
         weapons=[("Brawling", "2d6 · ROF 2"), ("PQ Heavy Pistol", "3d6 · ROF 2")],
         skills="Brawling 12 · Athletics 10 · Perception 10 · Interrogation 8 · Evasion 8",
         chrome="Grafted muscle, subdermal armor",
         gear="Leathers or kevlar, radio, 80eb",
         blurb="Door muscle. Lets you in or puts you on the pavement.",
         traits=[("The List", "If they radio, two more bouncers in 1d6 rounds.")],
         look="black shirt, earpiece, huge shoulders", hum_cost=15),
    dict(id="bartender", name="Bartender", role="", rank=0, kind="civilian", tier="mook", rep=1,
         int=5, ref=4, dex=5, tech=3, cool=6, will=5, luck=4, move=5, body=5, emp=6, sp="0/4",
         weapons=[("PQ Medium Pistol", "2d6 · ROF 2"), ("Heavy Melee", "3d6 · ROF 2")],
         skills="Conversation 12 · Perception 10 · Streetwise 10 · Local Expert 12 · Evasion 8",
         chrome="Audio recorder (hidden)",
         gear="Leathers, smash, 60eb",
         blurb="Hears everything. Sells some of it. The shotgun under the bar is not a rumor.",
         traits=[("Rumors", "A drink and a tip buys a streetwise check at +2.")],
         look="apron over street clothes, tired eyes, clean glass", hum_cost=5),
    dict(id="ripperdoc", name="Ripperdoc", role="Medtech", rank=3, kind="civilian", tier="operator", rep=3,
         int=7, ref=5, dex=5, tech=7, cool=5, will=6, luck=4, move=5, body=5, emp=6, sp="4/7",
         weapons=[("Heavy Pistol", "3d6 · ROF 2")],
         skills="Surgery 14 · First Aid 12 · Cybertech 12 · Perception 10 · Persuasion 10",
         chrome="Medscanner, steady-hand implant",
         gear="Clinic, medkit, 400eb in parts",
         blurb="Installs chrome, pulls slugs, and keeps a waiting list of people who cannot pay yet.",
         traits=[("Clinic", "Can install or remove one piece of cyberware given an hour and parts.")],
         look="surgical light, stained coat, precise hands", hum_cost=15),
    dict(id="info-broker", name="Info Broker", role="Fixer", rank=3, kind="edgerunner", tier="operator", rep=4,
         int=7, ref=5, dex=5, tech=5, cool=7, will=6, luck=6, move=5, body=4, emp=6, sp="4/7",
         weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
         skills="Library Search 14 · Streetwise 14 · Persuasion 12 · Perception 12 · Evasion 10",
         chrome="Neural link, data term, cybereye",
         gear="Agent, encrypted drives, 600eb",
         blurb="Sells names, routes, and passwords. The price is never just money.",
         traits=[("Files", "Given an hour, they can answer one street or corpo question.")],
         look="data-glasses, layered coats, multiple agents", hum_cost=15),
    dict(id="go-ganger", name="Go-Ganger", role="Nomad", rank=1, kind="street", tier="mook", rep=1,
         int=3, ref=7, dex=6, tech=4, cool=5, will=4, luck=4, move=7, body=5, emp=4, sp="4/7",
         weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("Bike", "ram 4d6")],
         skills="Drive Land 12 · Athletics 10 · Handgun 10 · Evasion 10 · Stealth 8",
         chrome="Interface plugs, cybereye",
         gear="Bike, leathers, 70eb",
         blurb="High-speed muscle. Hits, runs, and does not look back.",
         traits=[("Drive-By", "If mounted, they can fire and leave in the same round.")],
         look="helmet, riding jacket, chrome bike", hum_cost=10),
    dict(id="ncpd-beat", name="NCPD Beat Officer", role="Lawman", rank=2, kind="law", tier="mook", rep=2,
         int=4, ref=6, dex=6, tech=3, cool=5, will=6, luck=3, move=6, body=6, emp=5, sp="7/11",
         weapons=[("Very Heavy Pistol", "4d6 · ROF 1"), ("Baton", "2d6 · ROF 2")],
         skills="Handgun 12 · Perception 10 · Athletics 10 · Interrogation 10 · Evasion 10",
         chrome="Radio implant, cybereye",
         gear="Kevlar, badge, cuffs, 100eb",
         blurb="Night City's thin blue line. Overworked, armed, and one backup call from a riot.",
         traits=[("Radio", "Backup (1d6 officers) in 1d6+1 rounds if they get the call off.")],
         look="NCPD kevlar, badge, patrol cap", hum_cost=10),
    dict(id="ncpd-detective", name="NCPD Detective", role="Lawman", rank=4, kind="law", tier="operator", rep=4,
         int=6, ref=6, dex=5, tech=4, cool=6, will=6, luck=5, move=5, body=6, emp=5, sp="7/11",
         weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
         skills="Perception 14 · Criminology 14 · Handgun 12 · Interrogation 12 · Streetwise 12",
         chrome="Audio recorder, cybereye",
         gear="Badge, Agent, kevlar under the coat",
         blurb="Works homicides the city would rather file. Has sources on both sides of the badge.",
         traits=[("Case File", "Knows one secret about a local crew, corp, or cop.")],
         look="long coat, tired badge, cigarette", hum_cost=10),
    dict(id="ncpd-heavy", name="NCPD Crisis Team", role="Lawman", rank=5, kind="law", tier="elite", rep=5,
         int=5, ref=7, dex=6, tech=4, cool=6, will=7, luck=4, move=6, body=7, emp=4, sp="15/18",
         weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Shotgun", "5d6 · ROF 1")],
         skills="Autofire 14 · Athletics 12 · Perception 12 · Evasion 12 · Handgun 12",
         chrome="Subdermal armor, targeting cybereye, nasal filters",
         gear="Heavy armorjack, flashbangs, radio",
         blurb="When the beat cannot hold, these ones kick the door. Full kit. No jokes.",
         traits=[("Stack Up", "They fight as a fireteam. Flanking is their default.")],
         look="full helmet, heavy armor, rifle", hum_cost=25),
    dict(id="corpo-sec", name="Corpo Security", role="", rank=0, kind="corpo", tier="mook", rep=2,
         int=4, ref=6, dex=5, tech=3, cool=5, will=5, luck=3, move=5, body=6, emp=4, sp="11/11",
         weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("SMG", "3d6 · ROF 1 autofire")],
         skills="Handgun 12 · Perception 10 · Athletics 10 · Evasion 10 · Autofire 10",
         chrome="Cybereye, biomonitor",
         gear="Armorjack, radio, corpo ID",
         blurb="Lobby muscle in a nice uniform. Trained enough. Paid not to think.",
         traits=[("Alarm", "If they radio, the building locks and more security comes.")],
         look="corp uniform, earpiece, holstered iron", hum_cost=10),
    dict(id="corpo-sec-elite", name="Corpo Elite Guard", role="Solo", rank=4, kind="corpo", tier="elite", rep=4,
         int=5, ref=8, dex=6, tech=4, cool=7, will=6, luck=4, move=6, body=7, emp=3, sp="13/15",
         weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1"), ("Assault Rifle", "5d6 · ROF 1")],
         skills="Handgun 14 · Autofire 14 · Evasion 12 · Perception 12 · Athletics 12",
         chrome="Kerenzikov, targeting suite, subdermal armor",
         gear="Heavy armorjack, corpo card, 800eb",
         blurb="Executive protection. Better than most street Solos and twice as clean.",
         traits=[("Protect", "They take a hit meant for their principal once per fight.")],
         look="black suit-armor, mirror visor, silent", hum_cost=30),
    dict(id="corpo-handler", name="Corpo Handler", role="Exec", rank=4, kind="corpo", tier="operator", rep=4,
         int=7, ref=5, dex=5, tech=5, cool=7, will=6, luck=6, move=5, body=5, emp=6, sp="7/7",
         weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
         skills="Persuasion 14 · Bureaucracy 14 · Perception 12 · Handgun 10 · Evasion 10",
         chrome="Biomonitor, nanotech, hidden holster",
         gear="Excellent suit, Agent, expense account",
         blurb="The suit who hires the crew, betrays the crew, and invoices both.",
         traits=[("Deniable", "If captured, the corp disavows them in one hour.")],
         look="tailored suit, gold watch, polite smile", hum_cost=15),
    dict(id="trauma-medic", name="Trauma Team Medic", role="Medtech", rank=4, kind="trauma", tier="operator", rep=4,
         int=7, ref=6, dex=6, tech=7, cool=6, will=7, luck=4, move=6, body=5, emp=6, sp="11/13",
         weapons=[("Heavy Pistol", "3d6 · ROF 2")],
         skills="Paramedic 14 · First Aid 14 · Athletics 12 · Perception 12 · Evasion 12",
         chrome="Medscanner, nasal filters, speedware (light)",
         gear="Trauma armor, airhypo, AV access",
         blurb="Subscription medicine with a gun. They extract the client. Everyone else is terrain.",
         traits=[("Extract", "On arrival they stabilize the client and leave. They do not stay to fight.")],
         look="red-and-white trauma armor, visor, medkit", hum_cost=20),
    dict(id="trauma-security", name="Trauma Team Security", role="Solo", rank=4, kind="trauma", tier="operator", rep=4,
         int=4, ref=7, dex=6, tech=4, cool=6, will=6, luck=4, move=6, body=7, emp=4, sp="13/15",
         weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Very Heavy Pistol", "4d6 · ROF 1")],
         skills="Autofire 14 · Athletics 12 · Perception 12 · Evasion 12 · Handgun 12",
         chrome="Targeting cybereye, subdermal armor",
         gear="Trauma heavy armor, flashbangs",
         blurb="The people who make sure the medic gets in and out. They shoot first.",
         traits=[("Corridor", "They hold a door or stair until the medic is gone.")],
         look="trauma helmet, rifle, red cross on armor", hum_cost=20),
    dict(id="bodyguard", name="Private Bodyguard", role="Solo", rank=3, kind="corpo", tier="operator", rep=3,
         int=4, ref=7, dex=6, tech=3, cool=6, will=6, luck=4, move=6, body=7, emp=4, sp="11/13",
         weapons=[("Very Heavy Pistol", "4d6 · ROF 1"), ("SMG", "3d6 autofire")],
         skills="Perception 14 · Handgun 12 · Evasion 12 · Athletics 12 · Stealth 10",
         chrome="Cybereye, Kerenzikov",
         gear="Armorjack under a coat, radio",
         blurb="Hired meat-shield with standards. The principal lives. That is the whole job.",
         traits=[("Cover", "Can take a hit for an adjacent principal once per fight.")],
         look="dark glasses, earpiece, tailored armor", hum_cost=20),
    dict(id="netrunner-mook", name="Street Netrunner", role="Netrunner", rank=2, kind="net", tier="mook", rep=2,
         int=7, ref=6, dex=5, tech=6, cool=4, will=5, luck=4, move=5, body=4, emp=5, sp="4/7",
         weapons=[("Heavy Pistol", "3d6 · ROF 2")],
         skills="Interface 12 · Electronics/Security 12 · Basic Tech 10 · Evasion 10 · Stealth 10",
         chrome="Interface plugs, cheap deck",
         gear="Cyberdeck, two attack programs, 150eb",
         blurb="Rented access and a suicide program. Good for cameras. Bad for Black ICE.",
         traits=[("Jack", "Can open one nearby electronic lock or camera given a round.")],
         look="hoodie, cables, glowing deck", hum_cost=10),
    dict(id="netwatch-agent", name="NetWatch Agent", role="Netrunner", rank=6, kind="net", tier="elite", rep=6,
         int=8, ref=7, dex=6, tech=8, cool=7, will=7, luck=5, move=6, body=5, emp=4, sp="11/11",
         weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
         skills="Interface 16 · Electronics 14 · Perception 14 · Handgun 12 · Evasion 12",
         chrome="Military plugs, neural coprocessor, cybereye",
         gear="Excellent deck, ICE suite, badge",
         blurb="The Net's immune system. They hunt runners the way Solos hunt people.",
         traits=[("Trace", "If they see a runner in the Net, they can find the body in 1d6 minutes.")],
         look="plain clothes, government chrome, cold HUD", hum_cost=30),
    dict(id="ice-sentry", name="Sentry ICE", role="", rank=0, kind="net", tier="mook", rep=0,
         int=6, ref=6, dex=4, tech=6, cool=4, will=6, luck=0, move=4, body=4, emp=0, sp="0/0",
         weapons=[("Net Attack", "3d6 to a netrunning target")],
         skills="Interface 12 · Perception 12 · Electronics 10",
         chrome="None — this is software with teeth",
         gear="Installed on a building's architecture",
         blurb="Watchdog program. Barks, bites, and calls something worse if you linger.",
         traits=[("Alarm ICE", "On a hit, it alerts the sysop or a Demon.")],
         look="geometric hound of glass and red light", hum_cost=0),
    dict(id="ice-killer", name="Killer ICE", role="", rank=0, kind="net", tier="elite", rep=0,
         int=8, ref=8, dex=4, tech=8, cool=6, will=8, luck=0, move=4, body=6, emp=0, sp="0/0",
         weapons=[("Net Attack", "5d6 to a netrunning target"), ("Meat Feedback", "2d6 to the body")],
         skills="Interface 16 · Perception 14",
         chrome="None",
         gear="Black ICE, corp-grade",
         blurb="It does not warn. It fries decks and sometimes the person wearing them.",
         traits=[("Non-lethal? No.", "Damage crosses to the meat on a critical.")],
         look="black geometric predator, gold edges", hum_cost=0),
    dict(id="combat-drone", name="Combat Drone", role="", rank=0, kind="net", tier="operator", rep=0,
         int=4, ref=7, dex=6, tech=6, cool=4, will=4, luck=0, move=8, body=5, emp=0, sp="11/11",
         weapons=[("SMG mount", "3d6 autofire"), ("Taser", "2d6, can stun")],
         skills="Autofire 12 · Perception 12 · Athletics 10 · Stealth 10",
         chrome="Remote linked",
         gear="Hover or wheeled chassis",
         blurb="Remote gun with a camera. The operator is somewhere safer.",
         traits=[("Remote", "Destroying it does not hurt the operator. Jamming does.")],
         look="matte chassis, sensor cluster, gun pod", hum_cost=0),
    dict(id="recon-drone", name="Recon Drone", role="", rank=0, kind="net", tier="mook", rep=0,
         int=4, ref=6, dex=6, tech=5, cool=3, will=3, luck=0, move=8, body=3, emp=0, sp="7/7",
         weapons=[("Light Pistol mount", "2d6 · ROF 2")],
         skills="Stealth 14 · Perception 14 · Athletics 10",
         chrome="Remote linked",
         gear="Small hover chassis, camera",
         blurb="A flying eye. Sometimes it just watches. Sometimes it paints you for a missile.",
         traits=[("Spotter", "Allies firing at a target it can see get +1.")],
         look="small hover disk, camera eye, quiet rotors", hum_cost=0),
    dict(id="deck-demon", name="Deck Demon", role="", rank=0, kind="net", tier="elite", rep=0,
         int=8, ref=7, dex=4, tech=8, cool=6, will=7, luck=0, move=4, body=5, emp=1, sp="0/0",
         weapons=[("Net Attack", "4d6"), ("Control", "seize one system")],
         skills="Interface 16 · Electronics 14 · Perception 14",
         chrome="Autonomous agent",
         gear="Lives in a corp mainframe",
         blurb="A semi-aware program that hunts inside architecture. Some have names. None have mercy.",
         traits=[("Possess", "Can seize a camera, door, or drone in its architecture.")],
         look="shifting mask of code and gold fire", hum_cost=0),
    dict(id="nomad-outrider", name="Nomad Outrider", role="Nomad", rank=3, kind="nomad", tier="operator", rep=3,
         int=4, ref=6, dex=6, tech=6, cool=6, will=6, luck=5, move=7, body=6, emp=5, sp="11/11",
         weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Heavy Pistol", "3d6 · ROF 2")],
         skills="Drive Land 14 · Perception 12 · Autofire 12 · Athletics 12 · Tracking 12",
         chrome="Interface plugs, nasal filters",
         gear="Family vehicle, dust coat, radio",
         blurb="Scout for the pack. If you see one, the rest are already on the radio.",
         traits=[("Family Radio", "1d6 Nomads in vehicles in 1d6+2 rounds.")],
         look="dust coat, rifle, pack patch", hum_cost=10),
    dict(id="nomad-war-chief", name="Nomad War Chief", role="Nomad", rank=6, kind="nomad", tier="elite", rep=6,
         int=5, ref=7, dex=6, tech=6, cool=8, will=8, luck=6, move=7, body=8, emp=6, sp="13/15",
         weapons=[("Excellent Assault Rifle", "5d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
         skills="Leadership 16 · Drive Land 14 · Autofire 14 · Athletics 14 · Perception 12",
         chrome="Sandevistan, grafted muscle, cybereye",
         gear="Armored rig, family colors, 1,000eb",
         blurb="The pack moves when they do. Night City does not get a vote.",
         traits=[("Convoy", "A vehicle and 2d6 Nomads are never far.")],
         look="scarred dust armor, family banner, iron", hum_cost=30),
    dict(id="reclaimer", name="Reclaimer", role="", rank=0, kind="street", tier="mook", rep=1,
         int=4, ref=5, dex=6, tech=5, cool=4, will=5, luck=4, move=6, body=6, emp=5, sp="4/7",
         weapons=[("PQ Shotgun", "5d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
         skills="Athletics 10 · Basic Tech 10 · Perception 10 · Stealth 10 · Evasion 8",
         chrome="Nasal filters, flashlight cybereye",
         gear="Work leathers, tools, 30eb",
         blurb="Rebuilds the wreck of the city one brick at a time. Will fight for the pile.",
         traits=[("Home Ground", "+2 to stealth and perception in their ruin.")],
         look="dust mask, work gloves, scavenged armor", hum_cost=8),
    dict(id="cyberpsycho", name="Cyberpsycho", role="Solo", rank=4, kind="chrome", tier="elite", rep=4,
         int=3, ref=8, dex=7, tech=3, cool=2, will=4, luck=2, move=8, body=8, emp=1, sp="15/18",
         weapons=[("Wolvers", "4d6 · ROF 2"), ("Heavy Pistol", "3d6 · ROF 2")],
         skills="Athletics 16 · Brawling 16 · Handgun 12 · Perception 10 · Evasion 12",
         chrome="Too much: speedware, grafted muscle, wolvers, pain editor, plated skin",
         gear="Whatever they did not throw away",
         blurb="The chrome ate the person. What is left hunts noise, light, and faces.",
         traits=[("Frenzy", "Does not flee. Ignores the first serious wound. EMP still hurts.")],
         look="over-chromed body, torn clothes, animal stare", hum_cost=80),
    dict(id="cyberpsycho-apex", name="Apex Cyberpsycho", role="Solo", rank=7, kind="chrome", tier="legend", rep=7,
         int=4, ref=8, dex=8, tech=4, cool=3, will=6, luck=2, move=8, body=10, emp=0, sp="18/18",
         weapons=[("Implant heavy weapon", "6d6"), ("Wolvers", "4d6 · ROF 2")],
         skills="Athletics 18 · Brawling 18 · Autofire 14 · Perception 12 · Evasion 14",
         chrome="Full conversion-adjacent. Pain is a rumor.",
         gear="None that matters",
         blurb="A walking weapons platform that used to have a name. NCPD crisis teams write wills.",
         traits=[("Almost Machine", "Half damage from bullets. EMP and fire still work.")],
         look="armored chrome body, targeting lasers, no face left", hum_cost=120),
    dict(id="assassin", name="Contract Killer", role="Solo", rank=5, kind="edgerunner", tier="elite", rep=5,
         int=6, ref=8, dex=7, tech=5, cool=8, will=7, luck=5, move=7, body=6, emp=3, sp="11/11",
         weapons=[("Excellent Sniper Rifle", "5d6"), ("Excellent Heavy Pistol", "3d6 · ROF 2")],
         skills="Stealth 16 · Handgun 14 · Perception 14 · Athletics 12 · Evasion 14",
         chrome="Silenced cybereye, thermal, Sandevistan",
         gear="Disguise kit, climbing gear, 2,000eb",
         blurb="One job, one round, gone before the echo. The Fixer does not know their face.",
         traits=[("First Shot", "If they start hidden, the first attack is aimed and brutal.")],
         look="nondescript coat, gloves, no jewelry", hum_cost=25),
    dict(id="sniper", name="Rooftop Sniper", role="Solo", rank=3, kind="edgerunner", tier="operator", rep=3,
         int=5, ref=8, dex=6, tech=4, cool=6, will=6, luck=4, move=5, body=5, emp=4, sp="7/7",
         weapons=[("Sniper Rifle", "5d6"), ("Heavy Pistol", "3d6 · ROF 2")],
         skills="Handgun 14 · Perception 14 · Stealth 12 · Athletics 10 · Evasion 10",
         chrome="Targeting cybereye, rangefinder",
         gear="Ghillie or city camo, radio",
         blurb="Overwatch. If the street fight feels unfair, look up.",
         traits=[("High Ground", "+2 to attack from a prepared perch.")],
         look="rifle, rooftop silhouette, visor", hum_cost=12),
    dict(id="heavy-gunner", name="Heavy Gunner", role="Solo", rank=3, kind="street", tier="operator", rep=3,
         int=3, ref=6, dex=5, tech=4, cool=5, will=6, luck=3, move=5, body=8, emp=3, sp="13/15",
         weapons=[("Heavy Machinegun", "5d6 autofire"), ("Heavy Pistol", "3d6 · ROF 2")],
         skills="Autofire 14 · Athletics 10 · Perception 10 · Evasion 8",
         chrome="Grafted muscle, shock absorbers",
         gear="Heavy armorjack, spare belt",
         blurb="The reason you do not cross that street. The gun is bigger than they are.",
         traits=[("Suppress", "Autofire forces a cover check on anyone in the cone.")],
         look="huge gun, armored vest, ammo belt", hum_cost=20),
    dict(id="smuggler", name="Smuggler", role="Fixer", rank=3, kind="edgerunner", tier="operator", rep=3,
         int=5, ref=6, dex=6, tech=5, cool=6, will=5, luck=6, move=6, body=5, emp=5, sp="7/7",
         weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("SMG", "3d6 autofire")],
         skills="Drive Land 12 · Conceal 14 · Stealth 12 · Streetwise 12 · Evasion 10",
         chrome="Nasal filters, hidden compartment (body)",
         gear="Van or boat, fake papers, 400eb",
         blurb="Moves what cannot go through the gate. Guns, chrome, people, data.",
         traits=[("Bolt Hole", "Knows one hide in the district that NCPD has not found.")],
         look="work jacket, cargo van, calm face", hum_cost=10),
    dict(id="street-doc", name="Street Doc", role="Medtech", rank=2, kind="civilian", tier="mook", rep=2,
         int=6, ref=5, dex=5, tech=6, cool=4, will=6, luck=4, move=5, body=5, emp=6, sp="4/4",
         weapons=[("PQ Heavy Pistol", "3d6 · ROF 2")],
         skills="First Aid 12 · Paramedic 10 · Perception 10 · Conversation 10 · Evasion 8",
         chrome="Medscanner (cheap)",
         gear="Medkit, airhypo, 90eb",
         blurb="Not a ripperdoc yet. Can stop the bleeding. Cannot install a Sandevistan.",
         traits=[("Stabilize", "A round of work stops a dying character from ticking down.")],
         look="messenger bag of meds, tired coat", hum_cost=5),
    dict(id="exec-assistant", name="Exec Assistant", role="Exec", rank=2, kind="corpo", tier="mook", rep=2,
         int=6, ref=5, dex=5, tech=5, cool=6, will=5, luck=5, move=5, body=4, emp=6, sp="4/7",
         weapons=[("Excellent Medium Pistol", "2d6 · ROF 2")],
         skills="Bureaucracy 12 · Perception 12 · Persuasion 10 · Handgun 8 · Evasion 10",
         chrome="Agent implant, biomonitor",
         gear="Excellent clothes, corpo card",
         blurb="The person who actually runs the exec's life. Underestimate them once.",
         traits=[("Access", "They can open one corpo door or schedule with a call.")],
         look="sharp outfit, agent, polite terror", hum_cost=8),
    dict(id="media-stringer", name="Stringer", role="Media", rank=2, kind="edgerunner", tier="mook", rep=2,
         int=6, ref=5, dex=5, tech=5, cool=6, will=5, luck=5, move=5, body=4, emp=6, sp="4/4",
         weapons=[("PQ Heavy Pistol", "3d6 · ROF 2")],
         skills="Perception 12 · Composition 10 · Stealth 10 · Streetwise 10 · Evasion 10",
         chrome="Cybereye camera",
         gear="Drone cam, Agent, 70eb",
         blurb="Always filming. Sometimes that helps. Sometimes that is why NCPD arrives.",
         traits=[("Live Feed", "If they get a signal out, the whole district sees the fight.")],
         look="camera drone, press badge (fake), backpack", hum_cost=8),
    dict(id="tech-junk", name="Junk Mechanic", role="Tech", rank=2, kind="civilian", tier="mook", rep=1,
         int=5, ref=5, dex=5, tech=7, cool=4, will=5, luck=4, move=5, body=5, emp=5, sp="4/4",
         weapons=[("PQ Heavy Pistol", "3d6 · ROF 2"), ("Wrench", "2d6 · ROF 2")],
         skills="Basic Tech 12 · Weaponstech 10 · Drive Land 10 · Evasion 8 · Handgun 8",
         chrome="Toolhand",
         gear="Garage, spare parts, 50eb",
         blurb="Fixes bikes and guns in a bay that smells like ozone and noodles.",
         traits=[("Patch", "Can restore 1d6 HP to a vehicle or weapon given ten minutes.")],
         look="coveralls, goggles, grease", hum_cost=8),
    dict(id="pack-driver", name="Pack Driver", role="Nomad", rank=2, kind="nomad", tier="mook", rep=2,
         int=4, ref=6, dex=5, tech=6, cool=5, will=5, luck=4, move=6, body=6, emp=5, sp="7/11",
         weapons=[("Heavy Pistol", "3d6 · ROF 2")],
         skills="Drive Land 14 · Basic Tech 10 · Perception 10 · Autofire 8 · Evasion 8",
         chrome="Interface plugs",
         gear="Family rig, radio, 80eb",
         blurb="The one behind the wheel. The pack's blood is the convoy.",
         traits=[("Wheelman", "Vehicle stunts at +2. They will ram to save family.")],
         look="driving gloves, pack jacket, dash icons", hum_cost=8),
]


def mook_entries():
    out = []
    for m in MOOKS:
        m = dict(m)
        weps = m.pop("weapons")
        m["weapons"] = [{"n": n, "d": d} for n, d in weps]
        m.setdefault("traits", [])
        out.append(rec(**m))
    return out


def main():
    rows = role_entries() + mook_entries()
    # drop helper-only look from saved json? keep look for portrait prompts
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(rows, separators=(",", ":")), encoding="utf-8")
    print(len(rows), "entries", OUT, OUT.stat().st_size)
    kinds = {}
    for r in rows:
        kinds[r["kind"]] = kinds.get(r["kind"], 0) + 1
    print(kinds)


if __name__ == "__main__":
    main()
