#!/usr/bin/env python3
"""Named Night City 2045 faces. Original dossiers; RED-flavored stats, not reprints."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("/home/steelworth/projects/blightnet/data/npcs.json")


def hp(body, will):
    return 10 + 5 * ((int(body) + int(will)) // 2)


def n(**kw):
    b, w = kw["body"], kw["will"]
    kw.setdefault("hp", hp(b, w))
    kw.setdefault("init", kw["ref"])
    kw.setdefault("humanity", max(0, kw["emp"] * 10 - kw.pop("hum_cost", 0)))
    kw.setdefault("hooks", [])
    kw.setdefault("weapons", [])
    return kw


PEOPLE = [
    n(
        id="rogue-amendiares",
        name="Rogue Amendiares",
        aka="Queen of the Fixers",
        role="Fixer",
        kind="legend",
        district="Upper Marina · Afterlife",
        affiliation="Afterlife",
        status="alive",
        rep=9,
        rank=8,
        int=8, ref=7, dex=6, tech=5, cool=8, will=8, luck=7, move=6, body=6, emp=6,
        sp="11/13", hum_cost=20,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Streetwise 18 · Persuasion 16 · Handgun 14 · Perception 14 · Evasion 14 · Bureaucracy 12",
        chrome="Interface plugs, cybereye HUD, hidden holster, light subdermal",
        gear="Afterlife keys, black book, Agent, excellent coat",
        look="silver-streak hair, black fixer coat, temple ports",
        blurb="She owns the Afterlife and half the gigs that matter. You do not walk in. You get invited.",
        text="Rogue stopped being a Solo when the Fourth Corporate War made legends expensive. In 2045 she is the fixer other fixers call when the job would get them killed. The Afterlife in the Upper Marina is her court: drinks named after the dead, a door that does not open for tourists, and a list of mercs she will actually pick up the phone for.\n\nShe still takes new talent to the Forlorn Hope when Marianne allows it. She still hates Arasaka with a personal heat that never cooled after 2023. A crew that impresses her gets work. A crew that wastes her time gets a polite smile and a door that will not open twice.",
        hooks=["A gig only Rogue will broker, and she wants a cut of the story as well as the cash.", "Someone used her name on a job she did not send. She wants the liar alive."],
    ),
    n(
        id="morgan-blackhand",
        name="Morgan Blackhand",
        aka="The other legend",
        role="Solo",
        kind="legend",
        district="Missing · last seen 2023",
        affiliation="Unaffiliated",
        status="missing",
        rep=10,
        rank=8,
        int=6, ref=8, dex=7, tech=5, cool=8, will=8, luck=6, move=7, body=8, emp=4,
        sp="15/18", hum_cost=35,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
        skills="Handgun 18 · Athletics 16 · Perception 16 · Evasion 16 · Stealth 14 · Tactics 16",
        chrome="Black cyberarm, targeting suite, Sandevistan, subdermal armor",
        gear="Military duster, spare mags, a reputation that still opens doors",
        look="black cyberarm, duster, one amber optic",
        blurb="The Solo the Afterlife will not name a drink after, because nobody confirmed the body.",
        text="Morgan Blackhand was the professional to Johnny's fire. When Arasaka Tower came down in 2023 he went in and did not come out in a way anyone can prove. Night City still argues. Some say he died in the blast. Some say he walked into the Badlands and kept the black glove on.\n\nIn 2045 his name is a password. Fixers use it to scare juniors. Solos use it as a toast. If a table ever puts him on the map, he is not a mook. He is the reason a crew brought backup, and the backup is still not enough.",
        hooks=["A black-gloved body is on a slab that is not his. Someone wants the real one found.", "A gig to retrieve 'Blackhand's iron' from a corp vault that may be empty."],
    ),
    n(
        id="adam-smasher",
        name="Adam Smasher",
        aka="Arasaka's monster",
        role="Solo",
        kind="legend",
        district="City Center · Arasaka",
        affiliation="Arasaka",
        status="alive",
        rep=10,
        rank=8,
        int=5, ref=8, dex=8, tech=6, cool=6, will=8, luck=3, move=8, body=12, emp=0,
        sp="18/18", hum_cost=80,
        weapons=[("Implant heavy weapon", "6d6"), ("Wolvers", "4d6 · ROF 2")],
        skills="Autofire 18 · Athletics 16 · Perception 14 · Intimidation 18 · Evasion 12",
        chrome="Full conversion. Pain is a rumor. EMP still hurts.",
        gear="Whatever Arasaka bolts on this week",
        look="skull chrome face, red optics, armored frame",
        blurb="The thing Arasaka sends when they want a person to stop existing.",
        text="Adam Smasher finished becoming a weapon a long time ago. In 2045 he is Arasaka's walking atrocity: full borg, licensed murder, and a reputation that makes even Maelstrom quiet. He does not take street gigs. He takes orders from Tokyo's favorite branch office.\n\nEdgerunners who see him and live do not brag. They change names. If a crew is on a job that intersects Smasher, the smart play is to abort. The other play is a funeral the Afterlife will actually name a drink after.",
        hooks=["Arasaka wants a witness silenced. Smasher is already in the building.", "A netrunner stole his maintenance codes. They have hours, not days."],
    ),
    n(
        id="johnny-silverhand",
        name="Johnny Silverhand",
        aka="The dead rockerboy",
        role="Rockerboy",
        kind="legend",
        district="Legend · 2023",
        affiliation="Samurai (gone)",
        status="dead",
        rep=10,
        rank=8,
        int=6, ref=7, dex=6, tech=4, cool=8, will=8, luck=6, move=6, body=6, emp=7,
        sp="7/11", hum_cost=15,
        weapons=[("Malorian Arms 3516", "5d6 · ROF 1")],
        skills="Play Instrument 16 · Persuasion 16 · Handgun 14 · Athletics 12 · Streetwise 14",
        chrome="Chrome left arm, audio suite, light tattoo",
        gear="Leather, shades, a war he started and did not finish",
        look="chrome arm, aviators, leather jacket",
        blurb="He died in 2023. Night City still orders the drink. Some nights the Net still plays the set.",
        text="Robert John Linder burned Arasaka's tower into a story the Time of the Red still tells badly. The body did not walk out. The myth did. In 2045 he is a cocktail, a bootleg holoset, and a problem for anyone who still works for the zaibatsu.\n\nUse him as a ghost in a file, a stolen engram, a Samurai cover band that knows too much, or the reason a corpo wants a crew to shut a broadcast down. He is not a random encounter. He is a plot.",
        hooks=["A bootleg engram claims to be him and is booking gigs.", "Arasaka will pay to bury a tape. Someone else will pay more to play it."],
    ),
    n(
        id="alt-cunningham",
        name="Alt Cunningham",
        aka="Soulkiller's author",
        role="Netrunner",
        kind="net",
        district="The Net · nowhere",
        affiliation="Unaffiliated (digital)",
        status="net",
        rep=9,
        rank=8,
        int=8, ref=6, dex=5, tech=8, cool=7, will=8, luck=5, move=5, body=4, emp=5,
        sp="0/0", hum_cost=0,
        weapons=[("Net attack", "5d6 to a runner")],
        skills="Interface 18 · Electronics 16 · Library Search 16 · Programming 18",
        chrome="She is the chrome now",
        gear="Architecture, rage, and a name corps still fear",
        look="pale, high collar, dissolving into gold code",
        blurb="The woman who wrote Soulkiller and got eaten by it. She is still in there.",
        text="Altiera Cunningham built the program Arasaka used to steal people. Then they used it on her. In 2045 she is not meat. She is a presence in old architecture, a rumor past the Blackwall's grandparents, and a reason NetWatch drinks.\n\nA table can meet her as a voice in a stolen mainframe, a ghost that wants a body, or a debt Johnny left unpaid. She does not do street fights. She does rewriting.",
        hooks=["A corp node starts answering in her voice.", "She offers a crew a door through ICE if they burn a specific Arasaka rack."],
    ),
    n(
        id="kerry-eurodyne",
        name="Kerry Eurodyne",
        aka="Samurai's other voice",
        role="Rockerboy",
        kind="legend",
        district="North Oak · sometimes the street",
        affiliation="Solo artist",
        status="alive",
        rep=8,
        rank=7,
        int=6, ref=6, dex=6, tech=5, cool=8, will=7, luck=6, move=6, body=5, emp=7,
        sp="7/11", hum_cost=15,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Play Instrument 18 · Persuasion 16 · Wardrobe 16 · Streetwise 12 · Handgun 10",
        chrome="Audio suite, light tattoo, discreet biomonitor",
        gear="Guitar, villa keys, a publicist he ignores",
        look="highlighted hair, leather stage jacket, smirk",
        blurb="The one who lived. Still loud. Still expensive. Still writes songs that start riots.",
        text="Kerry survived the war Johnny did not. In 2045 he is a villa, a catalog, and a man who has not decided whether the Time of the Red deserves another album or another bomb. Corps want the image. Boosters want the real thing on a stage they can storm.\n\nHe still drinks with people who remember 2020. He still owes Rogue a favor he will not name. A crew can bodyguard him, steal a master tape, or talk him into a set that gets them killed for free.",
        hooks=["He wants a reunion gig in a district that will riot.", "A corp bought his catalog. He wants the contract burned, not litigated."],
    ),
    n(
        id="nancy-hartley",
        name="Nancy Hartley",
        aka="Bes Isis",
        role="Media",
        kind="media",
        district="Downtown · Network 54",
        affiliation="Network 54",
        status="alive",
        rep=7,
        rank=6,
        int=7, ref=6, dex=5, tech=6, cool=8, will=7, luck=6, move=5, body=5, emp=7,
        sp="7/11", hum_cost=15,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
        skills="Perception 16 · Composition 16 · Persuasion 14 · Streetwise 14 · Evasion 12",
        chrome="Cybereye camera, audio recorder",
        gear="Press creds, drone cam, a lawyer on speed-dial",
        look="sharp bob, gold ear chrome, press jacket",
        blurb="The face that still asks the question corps do not want on air.",
        text="Bes Isis made a career out of being in the room when Night City lied. In 2045 she is older, meaner, and still on Network 54's air because firing her would prove her last piece. She has sources in the Afterlife, the Hope, and at least one Arasaka floor that does not exist on the public map.\n\nShe will hire a crew to get footage. She will also film the crew if the story is better. Read the contract. Assume the camera is on.",
        hooks=["She needs a camera inside a corp memorial.", "Someone is killing her stringers. She wants the pattern, not a eulogy."],
    ),
    n(
        id="spider-murphy",
        name="Spider Murphy",
        aka="The runner who got out",
        role="Netrunner",
        kind="net",
        district="Night City · moving",
        affiliation="Unaffiliated",
        status="alive",
        rep=8,
        rank=7,
        int=8, ref=7, dex=6, tech=8, cool=7, will=8, luck=6, move=6, body=5, emp=5,
        sp="7/11", hum_cost=25,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Interface 18 · Electronics 16 · Stealth 14 · Evasion 14 · Handgun 12",
        chrome="Military plugs, neural coprocessor, cybereye",
        gear="Excellent deck, kill switch, three dead names",
        look="short hair, visor on the forehead, cables",
        blurb="She ran with legends and lived. NetWatch would like to discuss that.",
        text="Spider Murphy was in the architecture when the old Net died. In 2045 she still jacks, still moves, and still will not sit for a corp interview. She knows where the old backdoors were. Some of them still open. Some of them eat people now.\n\nHire her if the job is a ghost in a mainframe. Do not hire her if you need a mascot. She will ghost you first.",
        hooks=["She will open one door for a crew that burns a NetWatch trace on her.", "A student of hers is frying. She wants them pulled before the ICE finishes."],
    ),
    n(
        id="rache-bartmoss",
        name="Rache Bartmoss",
        aka="DataKrash",
        role="Netrunner",
        kind="net",
        district="Legend · the old Net",
        affiliation="None (dead)",
        status="dead",
        rep=10,
        rank=8,
        int=8, ref=6, dex=5, tech=8, cool=6, will=8, luck=4, move=5, body=4, emp=3,
        sp="0/0", hum_cost=0,
        weapons=[("DataKrash", "the Net as you knew it")],
        skills="Interface 18 · Programming 18 · Electronics 16",
        chrome="Too much, then none",
        gear="A fridge, a legend, a crater in communications",
        look="wild hair, stained hoodie, cables at the wrists",
        blurb="He killed the old Net on the way out. Corps still have not forgiven the corpse.",
        text="Rache Bartmoss died in a way that took the global Net with him. The DataKrash is why 2045 still runs on local architecture and why your grandmother's bank still blames a man in a fridge. He is not a combat encounter. He is weather.\n\nUse him as a virus with a personality, a lost backup that should stay lost, or the reason a corp will pay a crew to sit on a sealed node and not jack in.",
        hooks=["A Bartmoss fragment is selling access in Kabuki.", "NetWatch wants a sealed apartment opened. They will not go in first."],
    ),
    n(
        id="shaitan",
        name="Shaitan",
        aka="The quiet fullborg",
        role="Solo",
        kind="legend",
        district="Combat Zone · wandering",
        affiliation="Unaffiliated",
        status="alive",
        rep=8,
        rank=7,
        int=6, ref=8, dex=7, tech=6, cool=8, will=8, luck=4, move=7, body=10, emp=2,
        sp="18/18", hum_cost=70,
        weapons=[("Implant blades", "4d6 · ROF 2"), ("Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Athletics 16 · Stealth 14 · Perception 14 · Handgun 14 · Evasion 14",
        chrome="Full conversion, ceramic shell, single optic",
        gear="Long coat, a church he still visits",
        look="black ceramic body, gold inlay, blue optic",
        blurb="A fullborg who still pretends there is a person in the shell. Sometimes there is.",
        text="Shaitan is the other famous conversion: quieter than Smasher, no zaibatsu leash, and a habit of standing in ruined churches like the building might still forgive him. Street rumor says he takes jobs that punish chrome-cults and corpo conversion mills.\n\nHe will not talk much. He will not miss. A crew that treats him like a vending machine learns that the optic is not off.",
        hooks=["He wants a conversion clinic emptied without a massacre. That is harder.", "Inquisitors called him an abomination in public. He asked for names."],
    ),
    n(
        id="nomad-santiago",
        name="Santiago Aldecaldo",
        aka="Nomad Santiago",
        role="Nomad",
        kind="nomad",
        district="Badlands · Aldecaldo pack",
        affiliation="Aldecaldos",
        status="alive",
        rep=8,
        rank=7,
        int=6, ref=7, dex=6, tech=6, cool=8, will=8, luck=6, move=7, body=8, emp=6,
        sp="13/15", hum_cost=20,
        weapons=[("Excellent Assault Rifle", "5d6 · ROF 1"), ("Heavy Pistol", "3d6 · ROF 2")],
        skills="Drive Land 16 · Leadership 16 · Athletics 14 · Perception 14 · Autofire 14",
        chrome="Interface plugs, nasal filters, cybereye",
        gear="Pack rig, family radio, dust coat",
        look="grey-streak hair, patched duster, desert light",
        blurb="The pack moves when he does. Night City is a supply stop, not a home.",
        text="Santiago Aldecaldo is the name on half the convoy stories that survived the War. In 2045 the pack still runs the roads the NUSA pretends it owns. He has pulled family out of corpo trunks and put corpo trunks in the sand.\n\nHe will hire a city crew if the job needs city sins. He will not leave family as collateral. Cross the pack and the road out of Night City gets longer.",
        hooks=["A kidnapped Aldecaldo kid is in a Santo Domingo warehouse.", "He needs a city fixer who will not sell the pack's route to Petrochem."],
    ),
    n(
        id="trace-santiago",
        name="Trace Santiago",
        aka="The kid the pack protected",
        role="Nomad",
        kind="nomad",
        district="Outskirts · Aldecaldo",
        affiliation="Aldecaldos",
        status="alive",
        rep=4,
        rank=3,
        int=5, ref=6, dex=6, tech=5, cool=6, will=6, luck=6, move=7, body=6, emp=6,
        sp="7/11", hum_cost=8,
        weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Heavy Pistol", "3d6 · ROF 2")],
        skills="Drive Land 12 · Perception 12 · Athletics 12 · Streetwise 10 · Autofire 10",
        chrome="Interface plugs, cheap cybereye",
        gear="Pack cap, radio, a city map he is still learning",
        look="young, dust jacket, pack cap",
        blurb="Santiago's blood. Kiroshi already tried once. The pack answered.",
        text="Trace is the next generation of a name that already scares corps. Kiroshi grabbed him once. Rogue and the Willows got him back. In 2045 he rides scout, runs messages into the city, and is still young enough to think a Night City night is a story instead of a bill.\n\nA crew that helps him gets pack credit. A crew that uses him as bait gets the road closed.",
        hooks=["He is in the city without backup and will not admit it.", "He saw a Petrochem tanker doing something the pack needs proven."],
    ),
    n(
        id="saburo-arasaka",
        name="Saburo Arasaka",
        aka="The old man of Tokyo",
        role="Exec",
        kind="corpo",
        district="Tokyo · Night City Tower",
        affiliation="Arasaka",
        status="alive",
        rep=10,
        rank=8,
        int=8, ref=4, dex=3, tech=5, cool=8, will=8, luck=6, move=3, body=3, emp=2,
        sp="4/7", hum_cost=10,
        weapons=[("Holdout", "2d6 · ROF 1")],
        skills="Bureaucracy 18 · Persuasion 16 · Business 18 · Interrogation 14 · Perception 14",
        chrome="Life-extension suite, biomonitor, discreet ports",
        gear="Cane, Tower, a family that is a weapon",
        look="ancient, black silk suit, ice eyes",
        blurb="He does not visit the street. The street visits him as a quarterly report.",
        text="Saburo Arasaka is older than most of the city's ruins and twice as maintained. In 2045 he still treats Night City as a branch that disappointed him. The Tower is his knife. Soulkiller is his theology. His children are succession math.\n\nA street crew does not fight him. They fight the people who want to impress him. If his name is on a gig, someone is already dead on paper.",
        hooks=["A leaked memo has his chop. Half of Night City would kill for the other half.", "Hanako wants a package delivered without Yorinobu seeing it."],
    ),
    n(
        id="hanako-arasaka",
        name="Hanako Arasaka",
        aka="The daughter who waits",
        role="Exec",
        kind="corpo",
        district="City Center · Arasaka Tower",
        affiliation="Arasaka",
        status="alive",
        rep=8,
        rank=7,
        int=8, ref=5, dex=5, tech=5, cool=8, will=8, luck=6, move=5, body=4, emp=5,
        sp="7/11", hum_cost=12,
        weapons=[("Excellent Medium Pistol", "2d6 · ROF 2")],
        skills="Bureaucracy 16 · Persuasion 16 · Perception 14 · Business 14 · Evasion 10",
        chrome="Discreet biomonitor, nanotech, cybereye",
        gear="Ivory coat, bodyguards who do not joke",
        look="precise updo, ivory-and-black coat",
        blurb="Polite as a blade. She is the succession plan that smiles.",
        text="Hanako is the child Saburo trusts to look like stability. In 2045 she hosts, she listens, and she files every slight. Street rumor says she is kinder than her father. Street rumor has not sat in her meetings.\n\nA crew might bodyguard a garden party, steal a sibling's drive, or deliver a letter she cannot send through the Tower. She pays on time. She never forgets who saw her bleed.",
        hooks=["She needs a deniable team to watch Yorinobu for one night.", "A Relic prototype is leaving the Tower. She wants it to arrive somewhere else."],
    ),
    n(
        id="yorinobu-arasaka",
        name="Yorinobu Arasaka",
        aka="The son who hates the house",
        role="Exec",
        kind="corpo",
        district="Westbrook · and the street",
        affiliation="Arasaka (badly)",
        status="alive",
        rep=7,
        rank=6,
        int=7, ref=6, dex=6, tech=5, cool=7, will=7, luck=6, move=6, body=5, emp=5,
        sp="7/11", hum_cost=15,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Persuasion 14 · Streetwise 12 · Handgun 12 · Athletics 12 · Bureaucracy 12",
        chrome="Light, stylish, deniable",
        gear="Designer jacket, penthouse, a list of people Tokyo wants watched",
        look="dark street jacket, bitter calm",
        blurb="He wears the name like a bruise. He still spends the money.",
        text="Yorinobu is the Arasaka who would rather be a criminal than a prince, and has not committed to either. In 2045 he funds street crews, embarrasses the Tower, and still sleeps in a building with his father's logo on it.\n\nHe hires edgerunners for jobs that look like rebellion and sometimes are. Check who actually benefits before you shoot.",
        hooks=["He wants a shipment diverted from an Arasaka dock. The guards still work for Dad.", "A recording of a family argument is worth more than the guns around it."],
    ),
    n(
        id="michiko-sanderson",
        name="Michiko Sanderson",
        aka="Danger Gal",
        role="Exec",
        kind="corpo",
        district="Westbrook · Danger Gal",
        affiliation="Danger Gal",
        status="alive",
        rep=7,
        rank=6,
        int=8, ref=6, dex=6, tech=6, cool=8, will=7, luck=6, move=6, body=5, emp=6,
        sp="7/11", hum_cost=12,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
        skills="Perception 16 · Bureaucracy 14 · Persuasion 14 · Criminology 14 · Handgun 12",
        chrome="Visor glasses, biomonitor, recorder",
        gear="Trench, agency card, a file on everyone you have met",
        look="trench, chrome visor glasses, rain",
        blurb="Saburo's granddaughter built a detective agency instead of a throne. That is not softness.",
        text="Michiko took the Arasaka bloodline and opened Danger Gal: private investigation with a J-pop grin and a bodyguard budget. In 2045 her analysts know more about Night City's crews than NCPD does, because her clients pay and NCPD does not.\n\nShe will hire street talent. She will also write the dossier that gets them hired by someone worse. Assume the cute logo has teeth.",
        hooks=["Danger Gal needs deniable eyes on a client they cannot be seen watching.", "A stolen Gal file is circulating. She wants it back before the subject reads it."],
    ),
    n(
        id="donald-lundee",
        name="Donald Lundee",
        aka="Militech's old war",
        role="Exec",
        kind="corpo",
        district="Santo Domingo · Militech campus",
        affiliation="Militech",
        status="alive",
        rep=8,
        rank=8,
        int=7, ref=5, dex=5, tech=6, cool=8, will=8, luck=5, move=5, body=6, emp=3,
        sp="11/13", hum_cost=18,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Bureaucracy 16 · Leadership 16 · Tactics 16 · Persuasion 14 · Handgun 12",
        chrome="Cyberhand, biomonitor, targeting optic",
        gear="Olive uniform, war-room, NUSA friends",
        look="grey buzzcut, Militech dress greens",
        blurb="America's favorite general-in-a-suit. He still thinks the Fourth Corporate War is unfinished.",
        text="Lundee sold the NUSA its guns and Night City its occupation-with-invoices. In 2045 he is older, still loud, and still sure Arasaka should have been glass. Militech's Santo campus is his leftover war.\n\nA crew working Militech jobs is working his mood. He pays. He also writes people off as acceptable losses in a memo.",
        hooks=["A crate of Fourth War surplus is walking. He wants it shot, not recovered.", "He will fund a hit that looks like street crime if Arasaka bleeds."],
    ),
    n(
        id="marianne-freeman",
        name="Marianne Freeman",
        aka="The Hope's other owner",
        role="Fixer",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=6,
        rank=5,
        int=6, ref=5, dex=5, tech=4, cool=7, will=7, luck=6, move=5, body=5, emp=7,
        sp="4/7", hum_cost=5,
        weapons=[("Shotgun", "5d6 · ROF 1"), ("Heavy Pistol", "3d6 · ROF 2")],
        skills="Persuasion 14 · Streetwise 14 · Perception 12 · Local Expert 16 · Evasion 10",
        chrome="Minimal. She kept the person.",
        gear="Bar keys, payroll, a shotgun under the wood",
        look="short hair, vest, leather apron",
        blurb="She pours, she books, she rebuilds. The Hope stands because she decided it would.",
        text="Marianne co-owns the Forlorn Hope with John. When Maelstrom bombed the old bar in 2045 she crawled out of the rubble and bought a new building in Woodland Park. She is the reason there is still a headquarters bar for people who are not Afterlife-famous yet.\n\nShe will hire a crew to watch a neighborhood, scare a landlord, or keep Ripper's people off her door. She pays in cash, rooms, and the kind of loyalty that outlives corps.",
        hooks=["Opening night needs extra guns that will not start a war.", "Someone is selling Hope secrets to Maelstrom. She wants a name, not a body, first."],
    ),
    n(
        id="john-freeman",
        name="John Freeman",
        aka="The Professor",
        role="Fixer",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=6,
        rank=5,
        int=8, ref=4, dex=3, tech=5, cool=7, will=8, luck=5, move=3, body=4, emp=7,
        sp="4/7", hum_cost=8,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Library Search 16 · Tactics 16 · Persuasion 14 · Bureaucracy 12 · Perception 12",
        chrome="Cyberchair, biomonitor, life-support assists",
        gear="Maps, medals, the bar's memory",
        look="grey beard, sweater, powered chair",
        blurb="Military historian in a chair that still pulled rubble off a friend. Do not confuse slow with done.",
        text="The Professor founded the Hope as a place soldiers could drink without being a product. ALS put him in a Rocklin chair. The 2045 bombing put smoke in lungs that were already losing. He lived, and he still runs strategy from the office upstairs.\n\nHe plans the Hope's wars. Marianne fights the days. Together they are why edgerunners have a home that is not a corpo lobby.",
        hooks=["He wants a Fourth War cache mapped before Militech files it.", "He needs a crew to extract a veteran from an Inquisitor basement."],
    ),
    n(
        id="cicely-feng",
        name="Cicely Feng",
        aka="Backhand",
        role="Tech",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=4,
        rank=4,
        int=6, ref=6, dex=6, tech=8, cool=6, will=6, luck=5, move=6, body=5, emp=6,
        sp="7/11", hum_cost=12,
        weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("Wrench", "2d6 · ROF 2")],
        skills="Basic Tech 16 · Cybertech 14 · Electronics 14 · Weaponstech 12 · Evasion 10",
        chrome="Toolhand, cybereye tools, light pain editor",
        gear="Workshop, spare parts, soldering iron",
        look="undercut, neon streak, grease jacket",
        blurb="The Hope's in-house tech. If it is broken, Backhand will make it worse, then better.",
        text="Cicely 'Backhand' Feng keeps the Hope's guns honest and its generators lying in a useful way. She scouted the new building. She will scout your van if you buy her noodles.\n\nShe is not a Solo. She is the reason Solos still have working irons after a Friday.",
        hooks=["She needs a rare part from a scav chop that will not sell.", "A bomb in the new Hope's walls has her signature on a wire she did not pull."],
    ),
    n(
        id="edelweiss-dolarhyde",
        name="Edelweiss Dolarhyde",
        aka="The Hope's kitchen",
        role="Fixer",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=3,
        rank=3,
        int=5, ref=5, dex=6, tech=6, cool=6, will=6, luck=5, move=6, body=5, emp=7,
        sp="4/7", hum_cost=4,
        weapons=[("Shotgun", "5d6 · ROF 1")],
        skills="Local Expert 12 · Perception 12 · Persuasion 12 · First Aid 10 · Evasion 10",
        chrome="Almost none",
        gear="Chef coat, kitchen shotgun, family recipes",
        look="messy bun, stained chef coat",
        blurb="Dollar Bill's niece. She feeds the Hope and hears everything the bar pretends it did not.",
        text="Edelweiss took over the kitchen when the Professor got sick and never gave it back. In 2045 she is head cook, rumor mill, and the person who knows which regular has not eaten in two days. Dollar Bill is her uncle. She is the honest one in that sentence.\n\nBe decent in her kitchen. The shotgun is not décor. A crew that buses tables for a night hears more than they will from a fixer who charges for the same gossip.",
        hooks=["A supplier is cutting the meat with something that is not meat.", "She wants a missing dishwasher found before Marianne notices the till."],
    ),
    n(
        id="petra-david",
        name="Petra David",
        aka="Door",
        role="Solo",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=4,
        rank=4,
        int=5, ref=7, dex=6, tech=3, cool=7, will=7, luck=4, move=6, body=7, emp=5,
        sp="11/13", hum_cost=15,
        weapons=[("Very Heavy Pistol", "4d6 · ROF 1"), ("Baton", "2d6 · ROF 2")],
        skills="Perception 14 · Handgun 14 · Athletics 12 · Interrogation 12 · Evasion 12",
        chrome="Cybereye, radio implant, subdermal",
        gear="Kevlar, door list, backup baton",
        look="short hair, vest, radio mic",
        blurb="Security chief. If she does not know your face, you wait in the rain.",
        text="Petra took the Hope's door after the bombing and treats every stranger like a sequel. She is fair. She is not friendly on the clock. The list in her pocket is shorter than Rogue's and meaner about second chances.\n\nA crew that starts trouble in the Hope starts it with her, then with everyone who drinks there. She would rather throw you into the rain than mop you off the boards.",
        hooks=["She needs extra hands on a night Maelstrom promised to visit.", "Someone on the list is using a dead regular's name."],
    ),
    n(
        id="doc-stoic",
        name="Doc Stoic",
        aka="House ripper",
        role="Medtech",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Forlorn Hope",
        status="alive",
        rep=4,
        rank=4,
        int=7, ref=5, dex=5, tech=7, cool=6, will=7, luck=4, move=5, body=5, emp=6,
        sp="4/7", hum_cost=10,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Surgery 16 · First Aid 14 · Cybertech 12 · Perception 12 · Persuasion 10",
        chrome="Medscanner, steady-hand, loupes",
        gear="Clinic room, airhypo, a waiting list",
        look="clinic coat, surgical loupes, tired",
        blurb="He will pull a slug and install a hand in the same hour. He will also tell you to stop.",
        text="Doc Stoic is the Hope's in-house ripper. He does not advertise. If you can find the door, you are already family or bleeding enough to be.\n\nHe hates Inquisitors, loves clean tools, and will trade a discount for a story that does not waste his time.",
        hooks=["A patient woke up with extra chrome. Stoic wants the installer.", "He needs a rare implant moved across town without Trauma Team noticing."],
    ),
    n(
        id="aurora-oreilly",
        name="Aurora O'Reilly",
        aka="Rory",
        role="Media",
        kind="media",
        district="University District",
        affiliation="Independent",
        status="alive",
        rep=4,
        rank=3,
        int=7, ref=5, dex=5, tech=5, cool=6, will=6, luck=6, move=5, body=4, emp=7,
        sp="4/7", hum_cost=6,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Perception 14 · Composition 12 · Streetwise 12 · Stealth 10 · Evasion 10",
        chrome="Cybereye camera",
        gear="Press vest, campus pass, drone",
        look="red-brown hair, press vest, hoodie",
        blurb="University District stringer. She got the Professor out of the rubble and still wants the rest of the story.",
        text="Rory covers the campus ruins and the Hope's resurrection like they are the same beat, because they are. She was in the bombing. She lived. She has not stopped recording.\n\nShe will trade footage for protection. She will also upload before you can confiscate the drone.",
        hooks=["She has pictures of a city manager taking a bag. She needs a crew to stay alive long enough to air it.", "A campus lab is growing something Biotechnica will pay to keep quiet."],
    ),
    n(
        id="grace-steel",
        name="Grace Steel",
        aka="Soul Rebels",
        role="Rockerboy",
        kind="hope",
        district="Woodland Park · Forlorn Hope",
        affiliation="Soul Rebels / Forlorn Hope",
        status="alive",
        rep=3,
        rank=3,
        int=5, ref=6, dex=6, tech=5, cool=7, will=6, luck=6, move=6, body=5, emp=7,
        sp="4/7", hum_cost=8,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Play Instrument 14 · Persuasion 12 · Wardrobe 12 · Streetwise 10 · Evasion 10",
        chrome="Audio suite, techhair",
        gear="Guitar, amp, house-band contract",
        look="teal mohawk, patched leather, guitar",
        blurb="House band. Her set can empty a room or fill it with the wrong people.",
        text="Grace won the Hope's battle of the bands in 2045 and has been the house noise since. She knows which regulars are packing and which songs make Bozos show up uninvited.\n\nA crew can bodyguard a gig, smuggle a master, or ask her to play a signal into a crowded night.",
        hooks=["A corp wants her signed. She wants them embarrassed.", "Someone requested a song that is a Maelstrom calling card."],
    ),
    n(
        id="great-bozo",
        name="The Great Bozo",
        aka="Clown war",
        role="Fixer",
        kind="gang",
        district="Sewers · everywhere",
        affiliation="Bozos",
        status="alive",
        rep=6,
        rank=6,
        int=6, ref=6, dex=6, tech=5, cool=7, will=6, luck=7, move=6, body=6, emp=2,
        sp="7/11", hum_cost=20,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2"), ("Gas grenades", "special")],
        skills="Persuasion 14 · Stealth 14 · Streetwise 12 · Demolitions 12 · Evasion 12",
        chrome="Biosculpt, voice changer, toxin filters",
        gear="Carnival coat, sewer maps, unwilling converts",
        look="clown makeup, ruffled collar, carnival coat",
        blurb="The smile that starts a civil war. Hilaria 2045 was not a joke.",
        text="The Bozos are a biosculpted nightmare with a punchline. The Great Bozo is whichever face currently owns the joke. In 2045 a clown war spilled out of the sewers and hit the Hope among other places. Most of the attackers were victims in makeup.\n\nDo not negotiate like they are boosters. They want an audience. They will make you one.",
        hooks=["A friend came home with a new face they did not order.", "He offers a crew a gig that is actually an audition for the circus."],
    ),
    n(
        id="ripper-maelstrom",
        name="Ripper",
        aka="Maelstrom underboss",
        role="Solo",
        kind="gang",
        district="Northside · Combat Zone",
        affiliation="Maelstrom",
        status="alive",
        rep=6,
        rank=5,
        int=4, ref=7, dex=6, tech=5, cool=5, will=6, luck=4, move=6, body=8, emp=2,
        sp="11/13", hum_cost=40,
        weapons=[("Heavy Melee", "3d6 · ROF 2"), ("Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Brawling 16 · Handgun 14 · Athletics 14 · Intimidation 14 · Evasion 10",
        chrome="Facial chrome, saw implant, grafted muscle, pain editor",
        gear="Spiked vest, scrap chapel, a bomb recipe",
        look="circular saw arm, spiked vest, red neon",
        blurb="He bombed the Forlorn Hope. The Hope is not done with him.",
        text="Ripper is Maelstrom's idea of middle management: extra chrome, extra cruelty, and a personal grudge against a bar that would not pay tribute. The 2045 bombing is his signature. He is still in Northside, still recruiting, still sure the Hope will fold.\n\nA crew working for Marianne will meet him. Bring EMP. Bring friends.",
        hooks=["He is planning a second gift for opening night.", "A Maelstrom kid wants out. Ripper wants the kid's chrome back first."],
    ),
    n(
        id="hammer-maelstrom",
        name="Hammer",
        aka="Maelstrom muscle",
        role="Solo",
        kind="gang",
        district="Northside",
        affiliation="Maelstrom",
        status="alive",
        rep=4,
        rank=4,
        int=3, ref=6, dex=5, tech=3, cool=5, will=6, luck=3, move=5, body=10, emp=2,
        sp="13/15", hum_cost=35,
        weapons=[("Heavy Machinegun", "5d6 autofire"), ("Brawling", "3d6 · ROF 2")],
        skills="Autofire 14 · Brawling 16 · Athletics 12 · Intimidation 14",
        chrome="Grafted muscle, targeting optic, plated torso",
        gear="Stolen riot vest, ammo belt",
        look="huge, optic eye, torn NCPD vest",
        blurb="The reason a Northside alley has a dress code. The dress code is 'leave.'",
        text="Hammer is Ripper's door. He used to be NCPD chrome that walked off the lot. Now he is a walking roadblock with a machinegun and a Northside chop-shop that smells like ozone and fear.\n\nHe is not clever. He does not have to be. A crew that tries to talk him down learns that Maelstrom negotiations are measured in broken architecture. Bring EMP, or bring a better alley.",
        hooks=["He has a hostage in a chop-shop and a timer he cannot read.", "NCPD wants their vest back. They will not go in to get it."],
    ),
    n(
        id="hayato-nakagawa",
        name="Hayato Nakagawa",
        aka="Tyger Claws oyabun",
        role="Fixer",
        kind="gang",
        district="Japantown · Westbrook",
        affiliation="Tyger Claws",
        status="alive",
        rep=7,
        rank=6,
        int=7, ref=6, dex=6, tech=4, cool=8, will=7, luck=6, move=5, body=5, emp=5,
        sp="7/11", hum_cost=12,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2"), ("Mono-katana", "4d6")],
        skills="Persuasion 16 · Streetwise 16 · Bureaucracy 14 · Melee 14 · Perception 12",
        chrome="Discreet, expensive, a blade that is not",
        gear="Black suit, karaoke back room, a city of favors",
        look="grey temples, tiger-stripe cuff, suit",
        blurb="Japantown's polite knife. The karaoke is mandatory. The loyalty is too.",
        text="Hayato runs Tyger Claw business like a restaurant: reservations, dress code, and a kitchen you do not see. In 2045 Japantown still pays him in protection, parties, and silence.\n\nHe will hire outsiders for jobs his own people cannot be seen doing. He will not hire outsiders twice if they talk.",
        hooks=["A Claw lieutenant is skimming. Hayato wants it handled off-books.", "A corpo wants a table at his club. The corpo is bait."],
    ),
    n(
        id="abuela",
        name="Abuela",
        aka="Valentinos' kitchen",
        role="Fixer",
        kind="gang",
        district="Heywood",
        affiliation="Valentinos",
        status="alive",
        rep=6,
        rank=5,
        int=7, ref=4, dex=4, tech=3, cool=8, will=8, luck=6, move=4, body=4, emp=7,
        sp="4/7", hum_cost=2,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Persuasion 16 · Streetwise 16 · Local Expert 16 · Perception 14 · Leadership 14",
        chrome="Hearing aid chrome, gold teeth, a pistol in the drawer",
        gear="Kitchen, family photos, a neighborhood",
        look="silver bun, black dress, shawl",
        blurb="She will feed you. She will also decide if Heywood still wants you.",
        text="Abuela is not the loudest Valentino. She is the one the loud ones call. Funerals, weddings, and disappearances go through her kitchen in Heywood.\n\nA crew that respects the block gets work. A crew that shoots a cousin gets a city that will not sell them water.",
        hooks=["A kid from the block joined 6th Street. She wants them walked home, not buried.", "Someone used her name to move guns. She is insulted, which is worse than angry."],
    ),
    n(
        id="dahlia-vdb",
        name="Dahlia",
        aka="Voodoo Boys houngan",
        role="Netrunner",
        kind="gang",
        district="Pacifica",
        affiliation="Voodoo Boys",
        status="alive",
        rep=6,
        rank=6,
        int=8, ref=6, dex=5, tech=8, cool=7, will=8, luck=5, move=5, body=5, emp=4,
        sp="7/7", hum_cost=22,
        weapons=[("Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Interface 16 · Electronics 14 · Persuasion 12 · Stealth 12 · Perception 12",
        chrome="Data-bead braids, military plugs, neural link",
        gear="Server shrine, candles, a deck that hums",
        look="purple coat, bone-white harness, CRT glow",
        blurb="Pacifica's Net is a religion. She is clergy with a kill program.",
        text="Dahlia speaks for a Voodoo Boys cell that still treats the old Net like a sea you can drown in on purpose. Outsiders jack in here and do not come back with the same name.\n\nShe will trade access for a body dumped in the right tide. She will not explain the metaphor.",
        hooks=["A runner from the city stole a Vévé. She wants it, and the thief's deck.", "She offers a Blackwall-adjacent look if the crew burns a NetWatch van."],
    ),
    n(
        id="cornelius-wright",
        name="Cornelius Wright",
        aka="Hellraiser",
        role="Lawman",
        kind="gang",
        district="Santo Domingo",
        affiliation="6th Street",
        status="alive",
        rep=5,
        rank=5,
        int=5, ref=7, dex=6, tech=4, cool=6, will=7, luck=4, move=6, body=7, emp=5,
        sp="11/13", hum_cost=14,
        weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Autofire 14 · Athletics 12 · Perception 12 · Leadership 12 · Streetwise 12",
        chrome="Targeting optic, radio, subdermal",
        gear="NUSA surplus jacket, rooftop, a block watch that is a gang",
        look="surplus jacket, 6th Street tee, rifle",
        blurb="Veteran who decided the neighborhood would police itself. It does. Unevenly.",
        text="Cornelius 'Hellraiser' Wright came home from a war and found Santo Domingo worse. 6th Street is his answer: veterans, flags, and checkpoints that are not NCPD. Danger Gal already wrote him up. He hates that.\n\nHe will hire a crew to hit scavs. He will also shake down a crew that looks like scavs. Wear the right patch.",
        hooks=["A 6th Street kid executed a corpo in the wrong uniform. He wants it cleaned.", "He needs proof a Militech stash is feeding Maelstrom, not the block."],
    ),
    n(
        id="father-grace",
        name="Father Grace",
        aka="Chrome is sin",
        role="Lawman",
        kind="gang",
        district="Combat Zone · burned churches",
        affiliation="Inquisitors",
        status="alive",
        rep=5,
        rank=5,
        int=6, ref=5, dex=5, tech=3, cool=7, will=8, luck=4, move=5, body=6, emp=3,
        sp="7/11", hum_cost=0,
        weapons=[("Shotgun", "5d6 · ROF 1"), ("Chrome-ripper", "2d6 + special")],
        skills="Persuasion 14 · Intimidation 14 · Melee 12 · Perception 12 · Athletics 10",
        chrome="None. That is the point.",
        gear="Cassock over armor, flock, a list of ripperdocs",
        look="shaved head, stained cassock, body armor",
        blurb="He tears chrome out of people and calls it salvation. The street calls it a hate crime with a choir.",
        text="The Inquisitors are a religion of meat. Father Grace is a cell leader who preaches in ruins and hunts ripperdocs like they were demons. In 2045 his flock is growing because the Time of the Red made chrome look like a curse that worked.\n\nHe is not a joke encounter. He is a riot with scripture.",
        hooks=["A ripperdoc the Hope uses is on his list for tonight.", "He offers a crew a 'clean' job that is actually a kidnapping."],
    ),
    n(
        id="amanda-polishchuk",
        name="Amanda Polishchuk",
        aka="The Pole",
        role="Solo",
        kind="law",
        district="Little Europe",
        affiliation="City Hall (district)",
        status="alive",
        rep=5,
        rank=5,
        int=6, ref=7, dex=6, tech=4, cool=7, will=7, luck=5, move=6, body=6, emp=5,
        sp="11/11", hum_cost=12,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Handgun 14 · Perception 14 · Bureaucracy 12 · Persuasion 12 · Athletics 12",
        chrome="Cybereye, hidden holster, light subdermal",
        gear="City-manager coat, district budget, old iron",
        look="blonde-grey, holstered vest, balcony",
        blurb="Retired Solo running Little Europe. She does not like Downtown's manager. She likes results.",
        text="Amanda 'The Pole' Polishchuk took a district instead of a grave. Little Europe is working-class, wet, and hers. She still wears the holster. She still hates Emilia Ortega on principle and on paper.\n\nHire her office if you need a permit that is actually a threat. Hire her personally if the threat needs a second shot.",
        hooks=["A Downtown developer is buying her block. She wants them discouraged.", "She needs a crew to sit on a dock the NCPD will not admit exists."],
    ),
    n(
        id="emilia-ortega",
        name="Emilia Ortega",
        aka="Downtown's captain",
        role="Exec",
        kind="law",
        district="Downtown",
        affiliation="Chamber of Commerce / Mister K",
        status="alive",
        rep=5,
        rank=5,
        int=7, ref=5, dex=5, tech=5, cool=7, will=6, luck=6, move=5, body=5, emp=5,
        sp="7/7", hum_cost=10,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
        skills="Bureaucracy 16 · Persuasion 14 · Business 14 · Perception 12 · Handgun 10",
        chrome="Biomonitor, discreet ports",
        gear="Charcoal coat, plaza office, gentrification budget",
        look="short hair, ship-captain shirt, charcoal coat",
        blurb="Used to run a cargo ship. Now she runs Downtown for people who do not say their names on letters.",
        text="Emilia Ortega gentrifies with a captain's patience. Downtown's old families and new glass both answer her office. Mister K and the Chamber like her because she understands cargo: it moves, or it spoils.\n\nA crew can be her deniable longshoremen. They can also be the spoilage.",
        hooks=["A shipment through her plaza is not on any manifest she wrote.", "She will pay to embarrass Amanda Polishchuk without a shooting war. Ideally."],
    ),
    n(
        id="david-ling-po",
        name="David Ling Po",
        aka="Little China's respectable man",
        role="Exec",
        kind="law",
        district="Little China",
        affiliation="City Hall (district) · other things",
        status="alive",
        rep=6,
        rank=5,
        int=8, ref=5, dex=5, tech=4, cool=8, will=7, luck=6, move=5, body=5, emp=5,
        sp="7/11", hum_cost=8,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
        skills="Bureaucracy 16 · Persuasion 16 · Streetwise 14 · Perception 14 · Business 14",
        chrome="Discreet cybereye, recorder",
        gear="Grey suit, mahjong parlor, minions",
        look="neat hair, expensive grey suit",
        blurb="Harvard MBA. Respectable business. Probably does not watch the district through a hundred eyes.",
        text="David Ling Po is Little China's city manager and, depending who you ask, its other government. The parlor is an office. The office is a parlor. Tyger Claws have opinions. So does he.\n\nHe hires clean crews for dirty errands and dirty crews for clean ones. Guess which you are.",
        hooks=["A Claw shipment is using his docks without paying the city cut.", "He wants a journalist convinced that a story about him is unhealthy."],
    ),
    n(
        id="kabria-chung",
        name="Kabria Chung",
        aka="Upper Marina's postcard",
        role="Exec",
        kind="law",
        district="Upper Marina",
        affiliation="City Hall (district)",
        status="alive",
        rep=4,
        rank=4,
        int=7, ref=5, dex=5, tech=5, cool=7, will=6, luck=6, move=5, body=4, emp=6,
        sp="4/7", hum_cost=6,
        weapons=[("Excellent Medium Pistol", "2d6 · ROF 2")],
        skills="Persuasion 14 · Bureaucracy 14 · Business 12 · Perception 12 · Wardrobe 12",
        chrome="Tasteful, expensive",
        gear="Gallery invitations, waterfront office, NCPD liaison",
        look="breezy tailored coat, marina light",
        blurb="She wants the Marina to look like Richard Night's brochure. The Afterlife is a problem she cannot quite evict.",
        text="Kabria Chung sells Upper Marina as bohemian wealth. Yacht people on top, unhoused labor on the bottom, NCPD in the middle pretending that is a plan. Rogue's Afterlife sits in her district like a stain she has to call 'heritage.'\n\nShe will hire a crew to move a protest or a body. She will not say body.",
        hooks=["A yacht party needs security that will not look like security.", "She wants dirt on Rogue that will not get her killed for asking."],
    ),
    n(
        id="eran-malour",
        name="Eran Malour",
        aka="Malorian Arms",
        role="Tech",
        kind="street",
        district="Night City · by appointment",
        affiliation="Malorian Arms",
        status="alive",
        rep=7,
        rank=6,
        int=7, ref=6, dex=6, tech=8, cool=7, will=6, luck=5, move=5, body=5, emp=5,
        sp="7/11", hum_cost=10,
        weapons=[("Malorian custom", "5d6 · ROF 1")],
        skills="Weaponstech 18 · Basic Tech 16 · Handgun 14 · Business 12 · Perception 12",
        chrome="Steady-hand, cybereye rangefinder",
        gear="Workshop, waiting list, a legend's pistol design",
        look="craftsman coat, precision glasses, gun-oil light",
        blurb="He built the pistol on Johnny's hip. He still builds things that start wars in alleys.",
        text="Malorian is a name Solos drop when they want you to know they have taste. Eran still works. In 2045 a custom from him is a year of waiting and a year of enemies.\n\nHe does not do walk-ins. He does favors for people who brought him something impossible.",
        hooks=["A stolen Malorian prototype is in a scav den.", "He will build a gun for a crew that recovers a specific barrel from a corp vault."],
    ),
    n(
        id="thompson",
        name="Thompson",
        aka="The military-base media",
        role="Media",
        kind="media",
        district="NorCal Military Base",
        affiliation="Independent / NUSA-adjacent",
        status="alive",
        rep=5,
        rank=4,
        int=7, ref=5, dex=5, tech=5, cool=6, will=6, luck=5, move=5, body=5, emp=6,
        sp="7/11", hum_cost=8,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Perception 14 · Composition 14 · Bureaucracy 12 · Persuasion 12 · Streetwise 10",
        chrome="Cybereye camera, recorder",
        gear="Press vest, base pass, a flask",
        look="rumpled coat, camera, tired grin",
        blurb="He covers the base like it is a beat and a cage. Sometimes it is both.",
        text="Thompson is the media who got the military-base assignment and did not leave. He knows which officers drink and which convoys are off the books. The NUSA likes him close because a reporter on the base is easier than a reporter in a downtown studio.\n\nHe will trade a story for a ride. He will also burn a crew that treats the base like a dungeon crawl. Bring a cover that survives a checkpoint, not a joke.",
        hooks=["A convoy is moving something that is not on the manifest. He needs pictures.", "NUSA wants him quietly discredited. He wants a crew to make that expensive."],
    ),
    n(
        id="fireman",
        name="Fireman",
        aka="Afterlife regular",
        role="Solo",
        kind="street",
        district="Upper Marina · Afterlife",
        affiliation="Afterlife circuit",
        status="alive",
        rep=5,
        rank=4,
        int=5, ref=8, dex=6, tech=4, cool=7, will=6, luck=5, move=6, body=7, emp=4,
        sp="11/13", hum_cost=18,
        weapons=[("Excellent Very Heavy Pistol", "4d6 · ROF 1"), ("Incendiary", "special")],
        skills="Handgun 14 · Athletics 12 · Perception 12 · Evasion 12 · Streetwise 12",
        chrome="Heat-resistant skin weave, targeting eye",
        gear="Long coat, a drink named after someone else",
        look="burn-scarred coat, calm eyes, Afterlife neon",
        blurb="Rogue's kind of regular. If he is at the bar, the job already went loud somewhere.",
        text="Fireman is the Afterlife solo who did not get a cocktail because he is still walking. He takes burn jobs, literally and otherwise. He does not talk about the name.\n\nA crew can hire him as overwatch if Rogue nods. Without the nod he is scenery with a gun.",
        hooks=["He wants a partner for a gig Rogue will not officially send.", "Someone is copying his methods on civilians. He wants that stopped."],
    ),
    n(
        id="angel",
        name="Angel",
        aka="Afterlife doll",
        role="Fixer",
        kind="street",
        district="Upper Marina · Afterlife",
        affiliation="Afterlife",
        status="alive",
        rep=3,
        rank=3,
        int=6, ref=6, dex=6, tech=4, cool=7, will=5, luck=6, move=6, body=5, emp=7,
        sp="4/7", hum_cost=25,
        weapons=[("Holdout", "2d6 · ROF 2")],
        skills="Persuasion 14 · Perception 14 · Streetwise 12 · Wardrobe 14 · Evasion 12",
        chrome="Full-body sculpt, pheromone suite, recorder",
        gear="Look, a booth, everyone's secrets",
        look="perfect sculpt, club lights, listening",
        blurb="People tell dolls things they would not tell a cop. Angel remembers all of it.",
        text="Angel works the Afterlife the way a netrunner works a node: smile, log, sell the right packet to the right fixer. In 2045 that is still a living. The chrome is the costume. The mind is the weapon.\n\nBe decent. She has ended better Solos than you with a sentence in Rogue's ear.",
        hooks=["A client confessed a hit. Angel will sell the time and place.", "Someone is trying to buy her contract out from under the Afterlife."],
    ),
    n(
        id="elizabeth-kress",
        name="Elizabeth Kress",
        aka="NUSA's wartime president",
        role="Exec",
        kind="corpo",
        district="Washington · rarely Night City",
        affiliation="NUSA",
        status="alive",
        rep=8,
        rank=8,
        int=8, ref=4, dex=4, tech=4, cool=8, will=8, luck=6, move=4, body=4, emp=5,
        sp="4/7", hum_cost=6,
        weapons=[("Ceremonial pistol", "3d6")],
        skills="Persuasion 16 · Bureaucracy 18 · Leadership 16 · Perception 14",
        chrome="Life-extension, biomonitor",
        gear="Office, Secret Service, a country that still calls itself united",
        look="steel hair, NUSA colors, podium light",
        blurb="She ran a country through the War. Night City is still a problem on her desk.",
        text="President Kress is the NUSA's wartime face that never fully left the frame. In 2045 she is still the name on executive orders that make Militech smile and Night City sneer.\n\nA street crew meets her the way they meet a storm: through agents, through Lundee, through a law that arrives with tanks.",
        hooks=["A Night City leak would embarrass the NUSA. Her people want it plugged.", "A defector from her office is hiding in Pacifica."],
    ),
    n(
        id="jack-skorkowsky",
        name="Jack Skorkowsky",
        aka="The Hope's realtor",
        role="Fixer",
        kind="street",
        district="Woodland Park",
        affiliation="Independent",
        status="alive",
        rep=4,
        rank=3,
        int=6, ref=5, dex=5, tech=4, cool=7, will=5, luck=7, move=5, body=5, emp=6,
        sp="4/7", hum_cost=6,
        weapons=[("Heavy Pistol", "3d6 · ROF 2")],
        skills="Bureaucracy 14 · Trading 14 · Persuasion 14 · Streetwise 12 · Perception 12",
        chrome="Agent implant, recorder",
        gear="Keys, contracts, a renovated mahjong parlor",
        look="nice jacket, too many keys, salesman smile",
        blurb="He sold Marianne a new Hope. He always has another building. The buildings always have histories.",
        text="Jack finds spaces. In 2045 that meant a dead mahjong parlor that became the new Forlorn Hope. He takes a cut, tells a story, and somehow still has all his fingers. Every building he sells has a previous tenant who did not file a forwarding address.\n\nHire him to hide a crew. Check the basement yourself. If the walls hum, that is not the HVAC.",
        hooks=["The Hope's new walls have a previous tenant who did not leave.", "He needs a building 'cleared' before a corpo tour at dawn."],
    ),
    n(
        id="dollar-bill",
        name="William Dolarhyde",
        aka="Dollar Bill",
        role="Fixer",
        kind="hope",
        district="Forlorn Hope (legacy)",
        affiliation="Forlorn Hope",
        status="alive",
        rep=5,
        rank=4,
        int=6, ref=5, dex=5, tech=4, cool=7, will=6, luck=7, move=5, body=5, emp=6,
        sp="7/7", hum_cost=8,
        weapons=[("Excellent Heavy Pistol", "3d6 · ROF 2")],
        skills="Streetwise 16 · Trading 16 · Persuasion 14 · Perception 12 · Bureaucracy 12",
        chrome="Cybereye, hidden holster",
        gear="Long coat, cash in three currencies, niece in the kitchen",
        look="gold rings, long coat, fixer smile",
        blurb="Old Hope fixer. He can still get a gun by midnight and a problem by 12:05.",
        text="Dollar Bill helped own the original Hope and still treats the new one like a tab he never closed. Edelweiss is his niece. That is the only person he will not sell a rumor about. Everyone else is inventory with a pulse.\n\nHe is useful. He is also a leak with a price list. Marianne knows. She uses him anyway, which tells you how good he is at finding guns at midnight.",
        hooks=["He offers a sweet gig that belongs to someone who will notice.", "He wants a debt collected without Marianne hearing the method."],
    ),
    n(
        id="hardhat",
        name="Hardhat",
        aka="Afterlife regular",
        role="Tech",
        kind="street",
        district="Upper Marina · Afterlife",
        affiliation="Afterlife circuit",
        status="alive",
        rep=4,
        rank=3,
        int=6, ref=6, dex=5, tech=8, cool=5, will=6, luck=5, move=5, body=6, emp=5,
        sp="7/11", hum_cost=10,
        weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("Wrench", "2d6")],
        skills="Basic Tech 16 · Demolitions 14 · Electronics 12 · Perception 12 · Evasion 10",
        chrome="Toolhand, hardhat HUD, nasal filters",
        gear="Actual hardhat, charges, a tab Rogue watches",
        look="scorched helmet, work jacket, Afterlife stool",
        blurb="If the job needs a wall to stop being a wall, buy this one a drink first.",
        text="Hardhat blows holes for a living and drinks where the holes get named after people. He is an Afterlife regular because he lived. That is the whole résumé, plus a satchel that NCPD would call a crime scene if they opened it.\n\nHe will demo a door. He will not demo a bar he likes. Do not confuse the two. Pay extra if you want quiet. He considers quiet a luxury upgrade.",
        hooks=["A corpo vault needs a quiet hole. He does not do quiet without extra cash.", "Someone used his charges in a civilian stack. He wants a word."],
    ),
    n(
        id="piranha-queen",
        name="Nixie Cruz",
        aka="Piranhas queen",
        role="Nomad",
        kind="gang",
        district="Docks · go-gang circuit",
        affiliation="Piranhas",
        status="alive",
        rep=5,
        rank=5,
        int=5, ref=8, dex=7, tech=5, cool=7, will=6, luck=6, move=8, body=5, emp=4,
        sp="7/11", hum_cost=14,
        weapons=[("Heavy Pistol", "3d6 · ROF 2"), ("Bike ram", "4d6")],
        skills="Drive Land 16 · Athletics 14 · Handgun 12 · Stealth 12 · Evasion 14",
        chrome="Interface plugs, cybereye, reflex boost",
        gear="Chrome bike, leathers, dock keys",
        look="riding leathers, visor, dock neon",
        blurb="Go-gang royalty. If you hear engines in a pack, she already priced your organs.",
        text="The Piranhas run the wet edges of the city on bikes and spite. Nixie Cruz took the crown by being faster than the last crown. In 2045 the docks pay her a tax they call insurance.\n\nShe hires city crews for jobs that cannot be done at 200 an hour. She pays in eddies and in not running you down.",
        hooks=["A rival pack is using her colors. She wants a public correction.", "She will escort a van through the docks if the van is interesting."],
    ),
    n(
        id="steel-dragon",
        name="Mei 'Lantern' Zhao",
        aka="Steel Dragons",
        role="Solo",
        kind="gang",
        district="Little China · rooftops",
        affiliation="Steel Dragons",
        status="alive",
        rep=5,
        rank=5,
        int=6, ref=7, dex=7, tech=4, cool=7, will=6, luck=5, move=7, body=6, emp=5,
        sp="7/11", hum_cost=12,
        weapons=[("Mono-katana", "4d6"), ("Heavy Pistol", "3d6 · ROF 2")],
        skills="Melee 16 · Athletics 14 · Stealth 14 · Perception 12 · Evasion 14",
        chrome="Reflex boost, cybereye, light subdermal",
        gear="Dragon jacket, rooftop shrine, a code she actually keeps",
        look="dragon-embroidered jacket, blade, neon rain",
        blurb="Honor gang with real blades. They hate boosters. They hate cowards more.",
        text="The Steel Dragons play at being a martial order in a city that eats orders. Mei 'Lantern' Zhao is the one who still means it. Little China rooftops are her dojo and her tax route.\n\nShe will fight with a crew against scavs. She will not fight for a corpo who wants a photo.",
        hooks=["A booster crew tagged her shrine. She wants them taught, not necessarily buried.", "Hayato offered her a seat. She wants a street opinion before she answers."],
    ),
    n(
        id="red-chrome-colonel",
        name="Colonel Voss",
        aka="Red Chrome Legion",
        role="Solo",
        kind="gang",
        district="Combat Zone",
        affiliation="Red Chrome Legion",
        status="alive",
        rep=5,
        rank=5,
        int=5, ref=6, dex=6, tech=4, cool=6, will=7, luck=4, move=6, body=8, emp=3,
        sp="13/15", hum_cost=20,
        weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Heavy Melee", "3d6 · ROF 2")],
        skills="Autofire 14 · Leadership 14 · Athletics 12 · Tactics 12 · Intimidation 14",
        chrome="Plated limbs, targeting, radio",
        gear="Red-chrome armor, parade ground in a ruin",
        look="red-plated armor, ruin parade, banner",
        blurb="Boostergang that thinks it is an army. The colonel thinks that is cute and useful.",
        text="The Red Chrome Legion plays soldier with stolen kit and a color scheme you can see from orbit. Voss is an actual former officer who found a flock that likes orders. In 2045 they hold a few Combat Zone blocks like a joke with live ammo.\n\nThey will hire as muscle. They will also coup their own employer if the flag looks better.",
        hooks=["Voss wants a real Militech crate to make the parade look true.", "A lieutenant is planning a mutiny that will spill into a market."],
    ),
    n(
        id="scav-king",
        name="Lumen Graves",
        aka="Scav crew boss",
        role="Tech",
        kind="gang",
        district="Reclamation Zone",
        affiliation="Scavengers",
        status="alive",
        rep=4,
        rank=4,
        int=6, ref=6, dex=6, tech=7, cool=5, will=5, luck=4, move=6, body=6, emp=2,
        sp="7/11", hum_cost=18,
        weapons=[("Shotgun", "5d6 · ROF 1"), ("Mono-wire", "3d6")],
        skills="Basic Tech 14 · Stealth 14 · Cybertech 12 · Perception 12 · Evasion 12",
        chrome="Toolhand, flashlight eye, subdermal",
        gear="Van, bolt cutters, a clinic that does not ask",
        look="welder goggles, duster, bloody gloves",
        blurb="Strips wrecks and people. The chrome comes off whether you agree or not.",
        text="Lumen Graves runs a scav crew that supplies half the unlicensed rippers in the Reclamation Zone. They are not a gang with colors. They are a harvest. Wrecks, sleepers, and the unlucky all look like parts once the van doors close.\n\nDo not sleep in a wreck they marked. Do not wear chrome they can see from a roof. If you must buy from them, bring a friend who stays in the driver's seat with the engine on.",
        hooks=["A missing solo's chrome showed up in Graves' van. The solo's crew wants a refund.", "Doc Stoic will pay for a part Graves will not sell to anyone who looks like a cop."],
    ),
    n(
        id="trauma-captain",
        name="Captain Inez Sol",
        aka="Trauma Team night lead",
        role="Solo",
        kind="law",
        district="Citywide · AV corridor",
        affiliation="Trauma Team",
        status="alive",
        rep=5,
        rank=5,
        int=6, ref=7, dex=6, tech=5, cool=7, will=7, luck=4, move=6, body=7, emp=4,
        sp="13/15", hum_cost=16,
        weapons=[("Assault Rifle", "5d6 · ROF 1"), ("Very Heavy Pistol", "4d6 · ROF 1")],
        skills="Autofire 14 · Athletics 14 · Perception 14 · First Aid 12 · Evasion 12",
        chrome="Targeting, nasal filters, speedware light",
        gear="Trauma armor, AV, a client list",
        look="red-and-white armor, visor, AV ramp",
        blurb="She extracts the subscription. Everyone else is terrain. Do not be terrain.",
        text="Inez Sol runs a night AV. If your biomonitor screams and your card is good, she is the angel. If your card is declined, she is the weather.\n\nA crew can be hired as extra guns on an extraction. They can also be the reason the extraction needed extra guns.",
        hooks=["A client's extraction is in a building full of people who also called. Only one card is gold.", "Someone is cloning Trauma transponders. She wants the printer."],
    ),
]


def main():
    for p in PEOPLE:
        weps = []
        for w in p.get("weapons") or []:
            if isinstance(w, dict):
                weps.append(w)
            else:
                weps.append({"n": w[0], "d": w[1]})
        p["weapons"] = weps
    PEOPLE.sort(key=lambda p: (p.get("name") or "").casefold())
    OUT.write_text(json.dumps(PEOPLE, indent=2), encoding="utf-8")
    print(f"{len(PEOPLE)} faces -> {OUT}")


if __name__ == "__main__":
    main()
