#!/usr/bin/env python3
"""5e SRD fantasy-historical pantheons. Original table dossiers. Public-domain myths."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path("/home/steelworth/projects/blightnet")
OUT = ROOT / "data" / "gods.json"

# pantheon, id, name, aka, align, domains, symbol, rank, look, blurb, text, worship, hooks
GODS = [
    # ——— Celtic ———
    (
        "celtic", "dagda", "The Dagda", "The Good God, the All-Father of the Tuatha",
        "chaotic good", "Nature, Life, Trickery", "A cauldron, or a club that both slays and restores",
        "greater",
        "A huge, rustic chieftain in a short tunic and a cloak of raw wool, belly laughing, club on one shoulder, cauldron steaming at his feet.",
        "Plenty and ruin share the same table. He feeds armies from a cauldron and knocks down halls with a stick of oak.",
        "The Dagda is not a distant sky. He is the hall that never runs out of stew, and the club that ends a cattle-raid in one blow. Clerics who keep him do not preach. They cook, they fight, they make the next harvest happen.\n\nHis cauldron refuses a liar. His harp can order the seasons around a camp like a sergeant. A party that insults hospitality in his country finds the road longer and the rain meaner. A party that feeds strangers finds extra rations in the morning that no one packed.",
        "Shrines are hearths. A cleric of the Dagda blesses a meal, not a statue. Domain work: create food, goodberry, plant growth, and the odd thunderous smash.",
        ["The cauldron in a ruined dun still boils. It will feed the village if someone retrieves the ladle from a fomorian.", "His harp was stolen. Until it is played, no one in the valley can sleep or wake on time."],
    ),
    (
        "celtic", "arawn", "Arawn", "Lord of Annwn, Huntsman of the Otherworld",
        "lawful neutral", "Life, Trickery, Knowledge", "A white hound with red ears, or a crowned stag skull",
        "greater",
        "A pale hunter in grey-green, crowned faintly, a pack of white hounds with red ears at his knee. No gore. A winter wood behind him.",
        "The otherworld is a court, not a pit. Arawn keeps the dead in order and hunts those who cheat the hunt.",
        "Arawn rules Annwn as a king rules a winter estate: guests, laws, and a hunt that is not for sport. He has swapped faces with mortal princes to settle a feud, and he still expects the bargain kept.\n\nClerics of Arawn bury the named dead properly and refuse to raise them cheaply. They are the ones who know which barrow is a door. If the party raids a tomb for coin, they have made an appointment.",
        "Offer a clean kill and a true name at a barrow-gate. Speak softly. His hounds hear boast.",
        ["A mortal lord wore Arawn's face for a year and never gave it back. The hounds are in the fields.", "A barrow opened itself. The dead inside are polite, and they want a living champion for a hunt."],
    ),
    (
        "celtic", "belenus", "Belenus", "The Shining, Bright One",
        "neutral good", "Light, Life", "A sun-disc on a wheeled shrine, or a sprig of bel-fire",
        "greater",
        "A fair, bearded rider in pale gold wool, sun-wheel at his breast, standing before a hill-fire at dawn. Clothed, warm, no glare-text.",
        "Hill-fires and healing light. He is the year turning over, and the fever breaking.",
        "Belenus is kept where people still light fires on the first of summer. His light is not a courtroom. It is the thing that makes cattle well and wounds close.\n\nA cleric of Belenus carries a lantern they never bought. In a plague year they are more useful than a paladin. In a war they are the reason the night-watch can see the ditch.",
        "Light a fire on a high place at dawn. Heal by daylight when you can.",
        ["The beltane fire went out in a storm. Until it is relit from a true flame, calves are stillborn.", "A rival cult claims his sun-wheel. The hill is already arguing."],
    ),
    (
        "celtic", "brigantia", "Brigantia", "High One, lady of rivers and high places",
        "neutral good", "Life, War, Nature", "A crown of rushes over a spear, or a river-horse",
        "greater",
        "A tall woman in a green cloak pinned with gold, spear grounded, a river behind her and a hill-fort on the far bank. Fully clothed.",
        "Sovereignty of the land. Rivers, high forts, and the right to hold them.",
        "Brigantia is the name you give a river when it is also a queen. She blesses the people who keep the fords honest and the forts repaired.\n\nHer clerics settle border fights with a spear planted, not a speech. If the party is hired to take a hill, they may be taking it from her.",
        "Pour water from the local river over a spear-point. Do not dam a sacred stream for a mill without asking.",
        ["A new mill is starving the old ford of water. The salmon have left. So has the luck.", "A war-band took her hill-fort and hung their own banner. The well tastes of rust."],
    ),
    (
        "celtic", "diancecht", "Diancecht", "Physician of the Tuatha",
        "lawful good", "Life, Knowledge", "A bowl of healing water and a leaf of mistletoe",
        "lesser",
        "A calm, grey-haired physician in a linen apron over a tunic, hands clean, a silver bowl and herbs on a stone table. No gore.",
        "The god who puts people back together. He does not like sloppy miracles.",
        "Diancecht healed a king so well the king forgot to be grateful. He drowned his own son's better work out of pride, and the old stories do not hide that. A god of medicine who has been jealous is a useful warning at a table.\n\nHis clerics are surgeons. They will not raise the dead if a living patient is waiting. They keep a well that heals — once — and they know the difference between a cure and a story.",
        "Wash the wound in running water and name the injury honestly. Lies about how it happened spoil the work.",
        ["A well of Diancecht will heal one person a day. A war has a queue. Someone is selling places.", "His son's surviving work — a living silver arm — has been stolen from a tomb and fitted to a bandit."],
    ),
    (
        "celtic", "dunatis", "Dunatis", "God of the peaks and the cairn",
        "neutral", "Nature, Tempest", "A cairn of nine stones, or a ram's horn",
        "lesser",
        "A weathered hill-man in a sheepskin cloak, standing on a windy cairn, mountains stacked behind him like a court.",
        "Mountains, passes, and the stone piles that mark them.",
        "Dunatis does not come down. You go up. Cairns on the ridge are his parish. Travellers who add a stone get the next pass. Travellers who kick one down get weather.\n\nClerics of Dunatis are guides. They know which mountain is a door and which is only rock. A flying enemy is an insult they take personally.",
        "Add a stone to a cairn before you cross. Do not camp on a summit without leaving food for the next fool.",
        ["Someone pulled down a cairn to build a watchtower. The pass has been in cloud for a week.", "A ram with a gold collar is leading sheep off a cliff. Dunatis wants it walked home, not killed."],
    ),
    (
        "celtic", "goibhniu", "Goibhniu", "Smith of the Tuatha, brewer of the feast",
        "neutral good", "Knowledge, War", "An anvil and a cup of ale",
        "lesser",
        "A thick-armed smith in a leather apron, hammer raised over gold-hot iron, a drinking-horn on the anvil's horn. Sparks, no text.",
        "Weapons that do not miss, and ale that heals the people who made it through the day.",
        "Goibhniu forges the spears that always find their mark, and he brews for the feast after. His work is not pretty for its own sake. It is correct.\n\nA cleric of Goibhniu is a smith with a domain. They can bless a blade for a night. They will not bless a blade that will be used on a guest.",
        "Strike the anvil three times and pour the first cup on the coals.",
        ["A spear he made has been used in a murder. It will not leave the wound until a smith-priest sees it.", "His feast-ale recipe is in a giant's kitchen. The giant thinks it is soup."],
    ),
    (
        "celtic", "lugh", "Lugh", "Long-Arm, master of every art",
        "chaotic good", "Knowledge, War, Light", "A spear of light, or a many-skilled hand",
        "greater",
        "A young, bright warrior-king in a patterned cloak and gold torc, a slim spear that shines without fire, crafts laid at his feet: harp, anvil, sling.",
        "The god who is good at everything and expects you to pick one thing and be dangerous at it.",
        "Lugh arrived at a hall where every seat was filled by a specialist. He asked if they had anyone who was all of them. They made a seat. That is the whole religion.\n\nHis spear does not miss. His clerics are polymaths and show-offs. A party with a Lugh-priest has a plan for locks, lies, and lances — and an opinion about all three.",
        "Offer the work of your best skill, not a purchased jewel. He notices borrowed glory.",
        ["A contest of skills is being held under a false name. Lugh wants a champion who is not a cheat.", "His spear is in a museum that thinks it is a poker's rod. It has started humming."],
    ),
    (
        "celtic", "manannan", "Manannan mac Lir", "Son of the Sea, lord of the mist-gate",
        "lawful neutral", "Nature, Tempest, Trickery", "A wave-crest over a cloak of mist, or a sea-horse",
        "greater",
        "A sea-lord in a cloak the colour of deep water, gold-apple branch in one hand, a ship with no wake behind him. Mist, not storm-gore.",
        "The sea as a country. Mist as a door. He ferries, he hides, he bills you later.",
        "Manannan keeps the otherworld on the far side of weather. His cloak is fog. His horses are waves. He rents magic to heroes and collects when they pretend they invented it.\n\nClerics of Manannan are ferrymen, smugglers, and honest liars. Water walk is a courtesy. Control weather is a warning. If the party steals a boat in his waters, they have stolen from a landlord.",
        "Pay the first fish back. Do not boast about a safe crossing until you are ashore.",
        ["A mist-gate opened in a lake. Cattle walked in. Something else walked out.", "He lent a hero a boat that could fold into a pocket. The hero died. The boat is in a taxman's desk."],
    ),
    (
        "celtic", "math", "Math Mathonwy", "King of Gwynedd, wizard of the old law",
        "lawful neutral", "Knowledge, Trickery", "A wand of rowan and a king's footstool",
        "lesser",
        "An old king in a robe of dark wool and gold thread, seated so his feet never quite touch the earth, a living wand across his knees. Courtly, clothed.",
        "Magic as law. He cannot live unless his feet are in a virgin's lap — the old stories are strange, and the table can file that as a geas.",
        "Math is a wizard-king whose body is a contract. His feet cannot touch the ground. His court is a spell with manners. He turned people into animals for crimes that would be a fine in a kinder country.\n\nClerics and wizards who keep Math treat geasa as load-bearing. Break one and the hall notices. He is useful when the party needs a judge who cannot be bribed with gold, only with cleverness.",
        "Never let his name touch the floor. Speak judgments standing.",
        ["A geas has bound a whole village: no one may touch the earth at night. They are sleeping in the trees. It is going badly.", "Math's nephew stole a name and a face. The king wants the name back, not the head."],
    ),
    (
        "celtic", "morrigan", "The Morrigan", "Phantom Queen, of battle and prophecy",
        "chaotic neutral", "War, Trickery, Knowledge", "A raven over a ford, or three women as one shadow",
        "greater",
        "A dark-haired woman in a cloak of black feathers over a red gown, standing in a shallow ford, a raven on her wrist. Fully clothed, no corpses.",
        "She is the battle before it starts and the crow after. She offers victory. She does not offer comfort.",
        "The Morrigan is one and three: washer at the ford, queen of phantoms, crow on the shoulder of the dying. She will stand in the river and wash the armour of someone who has not died yet. That is not a riddle. That is a warning.\n\nHer clerics do not soothe. They tell you who will break. A paladin who wants a kind war-god should look elsewhere. A table that wants omens with teeth should keep her close.",
        "Leave meat for crows at a crossing. Do not ask her who wins if you cannot hear the answer.",
        ["She was seen washing a PC's cloak in a stream. She will trade the vision for a service at the next ford.", "A king refused her and lost a battle he had already won on paper. His banner is still in the river."],
    ),
    (
        "celtic", "nuada", "Nuada", "Silver-Hand, first king of the Tuatha",
        "lawful good", "War, Knowledge", "A silver right hand, or a sword that permits no lie",
        "greater",
        "A kingly warrior in a bronze-and-gold torc, one hand living silver, a straight sword point-down. Scarred, clothed, composed.",
        "Kingship that can be lost and earned back. A silver hand is not a weakness. It is a story you have to live with.",
        "Nuada lost an arm and, by the old law, the kingship. The physicians made him a silver hand. He took the chair again. That is the whole sermon: a leader who is incomplete can still be the right one, and the law can be argued with if you bring work.\n\nHis sword, when drawn, ends an argument. Clerics of Nuada are officers and mediators. They hate tyrants who were never wounded.",
        "Swear with the right hand visible. If it is silver, so much the better.",
        ["The silver hand has been stolen from a reliquary and fitted to a pretender.", "A law-speaker says a maimed captain cannot lead. Nuada's priest is on the other side of the table."],
    ),
    (
        "celtic", "oghma", "Oghma", "Sun-Face, binder of oaths, inventor of writing",
        "neutral good", "Knowledge, Trickery", "An open book bound in ogham, or a smiling sun",
        "greater",
        "A broad, golden-faced scholar-warrior in a poet's cloak, a tablet of ogham in one hand, a chain of oaths in the other. Warm light.",
        "Words as weapons and as glue. He invented letters so a promise could outlive a voice.",
        "Oghma is the reason a contract can be held up in a hall. He is also the reason a satire can raise blisters. His clerics are bards who went to law school.\n\nZone of truth is his handshake. A party that breaks a written oath in his country finds their own names misspelled on wanted posters — and the spelling still works.",
        "Write the oath. Speak it. Keep both copies.",
        ["A satire of Oghma's is eating a cruel lord alive, slowly, as rumour. The lord wants it unwritten.", "The first ogham stone in the valley has been defaced. Until it is recarved, no contract holds."],
    ),
    (
        "celtic", "silvanus-celt", "Silvanus", "Of the treeline, horned watcher of the wild wood",
        "neutral", "Nature", "A summer oak, or a wooden mallet",
        "greater",
        "A bearded woodland god in a cloak of leaves and bark, antlers modest, a mallet of living wood. Deep forest, no gore, fully covered.",
        "The forest as a person who was there first. Roads are a guest. Farms are a negotiation.",
        "This Silvanus is the Celtic wood, not a city cult. He is the treeline that does not like being straightened. His mallet is for fence-posts you should not have driven.\n\nClerics of Silvanus speak for trees that cannot hire lawyers. A logging camp that skipped the offering loses tools in the night. A party that sleeps on roots without asking wakes with sap in their hair and a debt.",
        "Leave the first cut of timber at the stump. Hunt what you eat. Do not map a grove for a mill.",
        ["A Roman-style road is being driven through an oak that has a name. The surveyors are vanishing one peg at a time.", "A dryad is not the problem. Silvanus is, and he wants the mill-wheel returned to being a tree."],
    ),
    # ——— Greek ———
    (
        "greek", "zeus", "Zeus", "King of Olympus, cloud-gatherer",
        "chaotic good", "Tempest, War", "A fistful of lightning, or an eagle",
        "greater",
        "A mature, bearded king in a white himation with a gold border, standing in cloud, a bolt resting in his hand like a sceptre, an eagle at his shoulder. Fully clothed.",
        "Sky, law, and the right to throw the furniture. He is hospitality and the storm that punishes those who break it.",
        "Zeus keeps the guest-right and the weather. He has a long list of children and a longer list of people who thought a closed door would hide them. At a table he is the reason a host who poisons a guest finds the roof open to rain.\n\nHis clerics are judges with a weather problem. They take xenia seriously: bread, salt, a bed, and no knives. Call lightning is not a metaphor.",
        "Offer the first cup of wine to the sky. Protect a guest even if they are inconvenient.",
        ["A guest was murdered under a peace-banner. The next storm will not stop until someone is named.", "An eagle will not leave a PC's pack. Zeus wants a message carried to a king who has stopped building guest-houses."],
    ),
    (
        "greek", "hera", "Hera", "Queen of the gods, of marriage and the watchful sky",
        "lawful neutral", "Life, Trickery, Knowledge", "A peacock fan, or a crowned diadem",
        "greater",
        "A regal woman in a peplos of deep blue and gold, diademed, a peacock at her side, looking at the viewer as if they have already broken a vow. Fully clothed.",
        "Queenship, marriage, and the memory of every slight. She is not cruel for sport. She is exact.",
        "Hera is the oath you swore in public. She blesses households that keep faith and unmakes ones that treat a spouse as furniture. The old stories make her jealous. At the table, treat that as a goddess who will not be made a fool.\n\nClerics of Hera officiate, negotiate, and ruin affairs that were going to ruin a city anyway. A ring blessed in her name is a contract with teeth.",
        "Keep the vow you said in front of people. A peacock feather on the altar is enough if the vow is real.",
        ["A royal marriage is a treaty. One side is already in another bed. Hera's priest knows, and is waiting in the courtyard.", "Peacocks have filled a palace. They will leave when the false dowry is admitted."],
    ),
    (
        "greek", "aphrodite", "Aphrodite", "Of the foam, of desire that starts wars",
        "chaotic good", "Life, Light, Trickery", "A scallop, a rose, or a golden apple",
        "greater",
        "A graceful woman in a rose-gold peplos and sea-pearl jewelry, standing at a shore with foam at her ankles, not unclothed, painted like a Titian court portrait.",
        "Love as weather. She can end a feud or start a ten-year war with the same glance.",
        "Aphrodite is not 'nice.' She is the force that makes people stupid and brave in the same hour. Her gift is wanting. What you do with it is still your crime.\n\nClerics of Aphrodite are diplomats, matchmakers, and saboteurs. Charm person is their handshake. A party that mocks a lonely NPC in her temple finds their next persuasion check is against themselves.",
        "Leave a rose and a true compliment, not a purchased one. She can tell.",
        ["A golden apple has shown up at a wedding with 'for the fairest' on it. Three queens are already armed.", "A sailor offered her a false lover's name. His ship will not catch wind until he says the real one."],
    ),
    (
        "greek", "apollo", "Apollo", "Of the lyre, the far shot, and the honest plague",
        "chaotic good", "Light, Knowledge, Life", "A lyre, a laurel, or a silver bow",
        "greater",
        "A youthful, sun-browned god in a laurel crown and a white-gold chiton, lyre in one hand, unstrung bow in the other, Delphic light behind him. Clothed, classical.",
        "Music, prophecy, medicine, and arrows that are also fevers. He is the bright twin.",
        "Apollo heals and he sends plague with the same bow. He speaks in riddles at Delphi because the truth, said plainly, would start a war before lunch.\n\nHis clerics keep a lyre and a kit. They are the ones who know the oracle is technically correct and still a menace. Lesser restoration and guiding bolt live in the same bag.",
        "Sing what you know. Do not fake an omen. He hates a counterfeit prophecy more than a quiet temple.",
        ["The oracle said a PC would 'die of gold.' A merchant is already wrapping them in gilded mail.", "A plague of arrows — actual arrows — falls at noon. Apollo wants a hymn that is also an apology."],
    ),
    (
        "greek", "ares", "Ares", "Of the spear-din, unashamed war",
        "chaotic evil", "War", "A bronze helm and a spear, or a wild boar",
        "greater",
        "A grim, bearded warrior in bronze panoply, helm under one arm, spear grounded, a red cloak, battlefield smoke but no corpses in frame.",
        "War without a speech. He is the hour when the plan is over and the shouting has a god.",
        "Ares is not strategy. Athena is strategy. Ares is the moment the line meets. Cities that pretend they do not need him still call him when the gate is on fire.\n\nClerics of Ares are not paladins. They are the people who keep you standing when the morale dice have failed. They take offence at a war fought only on paper.",
        "Offer a broken spear, not a clean one. He wants proof you were there.",
        ["Two armies have agreed to a duel of champions. Ares wants it to be a real fight, not a show.", "A general has banned his name in camp. The sentries keep falling asleep standing up."],
    ),
    (
        "greek", "artemis", "Artemis", "Of the wild wood, the unwed hunt, the moon's edge",
        "neutral good", "Nature, Life", "A crescent, a stag, or a hunter's bow",
        "greater",
        "A young woman in a short hunting chiton and boots, silver bow, a stag beside her in moonlit pines. Fully clothed, chaste classical pose.",
        "The hunt that feeds, the grove that is not for kings, the moon that does not ask permission.",
        "Artemis keeps the places maps call blank. She protects children, animals, and anyone who asked to be left alone. Actaeon is the sermon: do not look where you were not invited.\n\nHer rangers and clerics mark groves. A logging concession without her leave is a combat encounter with the forest itself.",
        "The first of the hunt is left on a stone. No trophies of what you did not eat.",
        ["A prince is hunting in a grove with a closed gate. The stags have human eyes this week.", "A missing child walked into her wood and will not come out until a vow is rewritten."],
    ),
    (
        "greek", "athena", "Athena", "Of the city, the aegis, the useful war",
        "lawful good", "Knowledge, War", "An owl, a spear, or the aegis with a quiet face",
        "greater",
        "A grey-eyed woman in a crested helm and a peplos under a goatskin aegis, spear upright, owl on the spear-butt, a city on a hill behind her. Fully clothed, calm.",
        "Wisdom that still knows how to hold a spear. She is the war you win because you thought.",
        "Athena is the patron of people who read the night before the battle. She invented useful things and then made sure they had laws. She is not kind to clever cruelty.\n\nClerics of Athena keep libraries and drill-yards in the same building. Shield of faith and identify are both hers. A party that wins by a trick she respects will find a grey owl on the tent-ridge.",
        "Offer a solved problem, not a trophy. Oil on a spear-point is traditional.",
        ["A city is about to vote for a stupid war. Her priest has one night to make them read the map.", "An owl dropped a bronze owl-coin in a PC's lap. Athena wants a labyrinth disarmed, not looted."],
    ),
    (
        "greek", "demeter", "Demeter", "Of the grain, the grief that winters the world",
        "neutral good", "Life, Nature", "A sheaf of wheat, or a torch in a field",
        "greater",
        "A mature woman in a harvest-coloured peplos, wheat in one arm, a torch in the other, a field half gold and half winter behind her. Clothed, grave, kind.",
        "Bread, and the mother who will stop the year if her child is taken.",
        "Demeter taught people to farm, which is to say she taught them to stay. When Persephone is below, she lets the world go hungry. That is not a tantrum. That is a god explaining the cost of a kidnapping.\n\nHer clerics keep granaries honest. Plant growth and hero's feast are their liturgy. Starve a village to fund an army in her country and the seed will not come up.",
        "The first loaf of a harvest on the altar. Do not waste grain in front of her name.",
        ["Winter is three weeks late to leave. Someone has Persephone's token in a locked box.", "A landlord is hoarding seed-grain. The mice will not touch it. Demeter will."],
    ),
    (
        "greek", "dionysus", "Dionysus", "Of the vine, the mask, the holy riot",
        "chaotic neutral", "Life, Trickery", "A grape-cluster, a thyrsus, or a theatre mask",
        "greater",
        "A long-haired youth in a panther-spotted cloak over a tunic, ivy crown, a pine-cone staff, theatre masks at his feet, vineyard twilight. Clothed, ecstatic not lewd.",
        "Wine, theatre, and the moment a crowd becomes one animal.",
        "Dionysus is the god of getting out of your own life without dying. He is theatre and vintage and the riot that starts when a king bans the play. He is not 'party guy.' He is the reminder that order without joy rots.\n\nClerics of Dionysus are actors, vintners, and the people who know when a feast is a spell. Confusion and charm are both on the list. A tyrant who bans masks in his city has made an enemy with a chorus.",
        "Pour the first wine on the ground. Put on a mask if you are going to tell the truth.",
        ["A king has banned theatre. The statues of the gods have started reciting lines at night.", "A vintage bottled in a hero's skull is being sold as a relic. Dionysus wants it drunk, not worshipped."],
    ),
    (
        "greek", "hades", "Hades", "Of the unseen house, rich in the dark earth",
        "lawful evil", "Knowledge, Trickery, Life", "A bident, a helm of dusk, or a key",
        "greater",
        "A dark-bearded king in a black-and-gold himation, bident in hand, seated on a stone throne, subterranean gold light, no corpses, no gore, living ruler.",
        "The dead are his citizens. He is not theatrical about it. He is a landlord with a very large building.",
        "Hades is grim because his work is grim, not because he eats babies. He keeps the gates. He hates people who steal from graves and people who skip the funeral. Wealth under the earth is his; miners pray whether they admit it or not.\n\nClerics of Hades are undertakers with jurisdiction. Speak with dead is a court appointment. Raise dead without his leave is theft.",
        "A coin under the tongue of the dead, and a clean name on the stone. Do not rob a grave for 'research.'",
        ["A necromancer is running a side door in Hades' house. The shades want a living lawyer.", "A mine struck a throne-room. The miners who came back will not speak of gold, only of a key."],
    ),
    (
        "greek", "hecate", "Hecate", "Of the three ways, of keys and the night-work",
        "chaotic good", "Knowledge, Trickery", "A three-way torch, a key, or a pair of hounds",
        "lesser",
        "A composed woman in a dark peplos, three-faced in the old icon way or holding three torches, keys at her belt, two calm hounds. Crossroads at night, clothed.",
        "Crossroads, witchcraft that has rules, and the key you were not supposed to copy.",
        "Hecate stands where three roads meet and hears all three rumours. She is the patron of people who work at night because the day will not have them. She is not 'evil magic.' She is magic that admits it is magic.\n\nHer clerics keep keys and dogs. They bless thresholds. A party that takes a third path at a fork without an offering has chosen her, whether they meant to.",
        "Leave food at a crossroads for dogs and the hungry. Do not pick the lock on a shrine.",
        ["Every lock in a town opened at midnight. Hecate wants to know who copied her key.", "A crossroads shrine was paved over. People who take that road arrive yesterday."],
    ),
    (
        "greek", "hephaestus", "Hephaestus", "Lame smith of Olympus, maker of working miracles",
        "neutral good", "Knowledge, War", "An anvil and a hammer, or a lame donkey",
        "greater",
        "A powerful, work-stained smith with a bad leg, leather apron over a tunic, hammer and tongs, bronze automata half-made on the bench, volcanic glow. Clothed, dignified.",
        "The god who makes the tools the other gods only wear. He is craft, fire, and the right to be ugly and indispensable.",
        "Hephaestus was thrown off a mountain and answered by inventing the world the rest of them live in: thrones, armour, bronze servants. He is the patron of anyone who was discarded and then became load-bearing.\n\nClerics of Hephaestus are smiths and inventors. Heat metal is a sermon. A cursed item on the table may simply be something he wants repaired, not destroyed.",
        "The first work of the day on the altar — a nail will do if it is true.",
        ["A bronze woman has walked out of a wrecked workshop and is looking for her maker's mark.", "The party's magic weapon was made here. It will not attune until they return a stolen hammer."],
    ),
    (
        "greek", "hercules", "Hercules", "The hero who became a god by surviving his own story",
        "chaotic good", "War, Life, Tempest", "A lion skin and a club, or twelve marks on a belt",
        "lesser",
        "A massive, weary hero in the Nemean lion skin over a tunic, olive-wood club, twelve small tokens on a baldric. Human, clothed, not a nude statue.",
        "Strength that had to be earned the long way. He is the patron of labours that were meant to kill you.",
        "Heracles — Hercules in the tavern-book — did twelve jobs that were supposed to be the end of him and then had to live with the reputation. He is a god now because the work did not stop when it should have.\n\nHis clerics take on ugly tasks. Enhance ability is their cantrip in spirit. A party on a 'simple errand' that has become a saga is already in his parish.",
        "Finish the job you named. Offer sweat, not incense.",
        ["A local tyrant is issuing 'labours' to political enemies. Hercules wants one of them done correctly, in public.", "The lion skin in a trophy hall is still warm. It wants to go home."],
    ),
    (
        "greek", "hermes", "Hermes", "Of the road, the lie, the letter, the luck",
        "chaotic good", "Trickery, Knowledge", "Winged sandals, a caduceus, or a roadside herm",
        "greater",
        "A lean traveller in a short cloak and winged hat, caduceus in hand, a road unwinding behind him, coin-pouch honest-looking. Clothed, sly, kind.",
        "Messages, thieves, merchants, and the dead on their first day of travel. He is the god of getting there.",
        "Hermes invented the lyre, stealing, and the excuse. He walks the living and escorts the newly dead. A letter that arrives in time is his miracle. A purse that changes owners is also his miracle.\n\nClerics of Hermes are couriers and con-artists with a code: do not steal from the ones who feed you. Dimension door is a professional courtesy.",
        "A coin at a roadside marker. Do not open other people's letters unless you are the mail.",
        ["Every message in a city arrived swapped. Hermes thinks it is funny. The duke does not.", "A psychopomp duty was skipped. A ghost is following the party because no one showed them the road."],
    ),
    (
        "greek", "hestia", "Hestia", "Of the hearth that does not travel",
        "neutral good", "Life, Knowledge", "A hearth-flame, or a circle of keys",
        "greater",
        "A quiet woman in a plain cinnamon peplos, seated at a round hearth, flame steady, household keys in her lap. No jewellery-flex, fully clothed, warm interior.",
        "The fire you do not let go out. She gave up a throne so the house would have a centre.",
        "Hestia is easy to skip in a war story and fatal to skip in a campaign about a town. She is the hearth. Cities keep a public fire in her name. If it dies, the city has forgotten what it is.\n\nHer clerics do not adventure unless the hearth is threatened. Tiny hut and sanctuary are their art. A party that loots a home altar will find their own campfire sulking.",
        "Feed the fire before you feed yourself. Keep one flame that has never been used to burn a person.",
        ["The civic hearth is out. No law passed since then has stuck.", "A landlord evicted a family and threw their hearth-stone in the street. The street is now warmer than his house, and angry."],
    ),
    (
        "greek", "nike", "Nike", "Of the winning, the wreath, the last inch",
        "lawful neutral", "War, Trickery", "A winged wreath, or a palm",
        "lesser",
        "A winged young woman in a wind-blown peplos, alighting to offer an olive wreath, battlefield banners behind her but no bodies. Clothed, classical Victory.",
        "Victory as a person who arrives late and still gets her name on the stone.",
        "Nike does not start wars. She lands on the one who is about to win and makes it look inevitable. Athletes, generals, and desperate duelists all shout for her in the last second.\n\nClerics of Nike bless contests that have rules. They hate a fixed fight. Bless and haste are her liturgy.",
        "The wreath goes on the altar after the win, not before. She notices a rented victory.",
        ["A champion has won every bout this year. Nike wants you to find the lead in his gloves.", "A city has a statue of Nike with her wings clipped. The army has not won since."],
    ),
    (
        "greek", "pan", "Pan", "Of the goat-foot panic, the pipes, the unmapped hill",
        "chaotic neutral", "Nature, Trickery", "Syrinx pipes, or a pine crown",
        "lesser",
        "A goat-legged rustic god in a pine crown, panpipes, a hairy chest under a cloak, woodland noon. Mythic satyr, not sexualized, no minors.",
        "Sudden fear in a quiet place. Music that makes cities feel like a bad idea.",
        "Pan is the reason a seasoned patrol runs from a noise that was only wind. He is also the reason a lonely hill feels like a temple. He is not a devil. He is the wild with a laugh.\n\nClerics of Pan are goatherds and saboteurs of straight roads. Fear and speak with animals. A party that drums through a grove at night has scheduled an encounter.",
        "Play a true note at noon. Leave the first cheese of the flock on a stone.",
        ["A legion built a straight road through his hill. At night the road is a spiral and the mile-stones lie.", "Panic has a name in a village: it starts at dusk and only a pipe-tune stops it."],
    ),
    (
        "greek", "poseidon", "Poseidon", "Earth-shaker, horse-lord, of the wine-dark road",
        "chaotic evil", "Tempest, Nature", "A trident, a horse, or a curling wave",
        "greater",
        "A massive sea-king in a sea-green himation, white beard, trident grounded, horses of foam, a cliff-temple behind. Clothed, storm-lit, no drowning bodies.",
        "The sea and the earthquake are the same temper. He is a gift of horses and a bill written in flood.",
        "Poseidon wanted a city and lost it to Athena, so the sea around it is still personal. He makes harbours and he breaks them. Sailors who skip his due find the horizon wrong.\n\nClerics of Poseidon are harbour-masters and cavalry chaplains. Tidal wave is not a metaphor. A campaign on the water that ignores him is a campaign about swimming.",
        "A horse, a bull, or the first catch, given to the water. Do not build on a last-year's wreck.",
        ["The tide came in and stayed. Poseidon wants a stolen trident-head back from a lighthouse.", "A horse born with webbed hooves will not take a rider until a sea-priest names it."],
    ),
    (
        "greek", "tyche", "Tyche", "Of the city's luck, the wheel that does not apologise",
        "neutral", "Trickery, Knowledge", "A rudder, a cornucopia, or a wheel",
        "lesser",
        "A crowned woman in a mural crown (city walls as a diadem), rudder in one hand, cornucopia in the other, a city behind her. Clothed, civic, slightly smiling.",
        "Luck as civic infrastructure. She is why one town always catches the fair wind.",
        "Tyche is the fortune of a place, not a dice charm. When she leaves a city, the dice still work and nothing good happens with them. When she stays, even a bad mayor gets a good harvest.\n\nClerics of Tyche keep a public shrine at the market gate. Bane and bless are both hers. A party that wants 'luck' from her will be asked what they did for the town this week.",
        "A coin in the civic fountain, heads-up. Do not pray for another city's ruin in her hearing.",
        ["The town's luck left in a box on a cart. The cart is three days ahead on the road.", "A rival city stole her mural crown from a statue. Birds will not land in either place until it is returned."],
    ),
    # ——— Egyptian ———
    (
        "egyptian", "re-horakhty", "Re-Horakhty", "The sun at the two horizons, falcon of the day-barque",
        "lawful good", "Light, Life, Knowledge", "A sun disk on a falcon, or a barque of day",
        "greater",
        "A falcon-headed king in white and gold linen, sun-disk crowned, standing in a solar barque on the sky-river, desert dawn. Majestic, clothed, no gore.",
        "The sun as a voyage that has to be made every night or the world does not open.",
        "Re-Horakhty is the sun that is also a hawk and a king. Each night his barque runs a gauntlet. Each morning is not guaranteed; it is a successful shift.\n\nClerics of Re keep watches. Daylight is a sacrament. They are terrible people to plan a coup with at noon and excellent people to have when the dark has a name.",
        "Face the sunrise. Do not sleep through a dawn you promised to watch.",
        ["The sun stalled at noon for a count of thirty. Something bit the barque. He wants a crew.", "A false sun-disk is being worshipped in a quarry. The real dawn is arriving late there."],
    ),
    (
        "egyptian", "anubis", "Anubis", "Jackal of the weighing, of the careful dead",
        "lawful good", "Death, Knowledge, Life", "A black jackal, or a scale with a feather",
        "greater",
        "A black jackal-headed man in white priest-linen and gold pectoral, holding a small scale, a feather on one pan, tomb-gold light. Dignified, no mummies in frame.",
        "Funerals done right. He is the reason a soul gets a fair weighing and a grave-robber does not.",
        "Anubis invented the funeral that works. He weighs the heart against a feather and he does not take bribes in gold — only in a life that was not a lie.\n\nHis clerics are embalmers and detectives. Speak with dead, gentle repose, zone of truth. A party that cracks a tomb 'just to look' has made a jackal-headed appointment.",
        "Linen, natron, a true name, a feather if you have one. Do not open a mouth that was closed on purpose.",
        ["A heart was stolen from a canopic jar. The shade cannot be weighed. It is haunting the thief's meals.", "A cult is selling 'guaranteed passage.' Anubis wants the stall closed and the money given to actual funerals."],
    ),
    (
        "egyptian", "apep", "Apep", "The night-serpent, enemy of the barque",
        "chaotic evil", "Trickery, Tempest", "A coiled serpent eating a sun, or a knot that will not untie",
        "greater",
        "A vast dark serpent of starless scale coiled around a dimming sun-disk in a cosmic cavern, no people, no gore, awe and threat.",
        "The thing that tries to stop tomorrow. Not a god you keep. A god you keep off.",
        "Apep is the eclipse with a will. He is not worshipped by anyone the other gods would sit with. Cults that feed him want the world still.\n\nThere are almost no true clerics of Apep at a healthy table. There are cultists. If a PC goes this way, they are the campaign's problem, and the sun-cults will notice.",
        "Do not. If you must: a knot, a confession of wanting the dark, and the knowledge that Re's people will come.",
        ["An eclipse is three days long and still going. Someone is feeding a snake in a basement.", "A 'serpent amulet' unknots every rope in a mile. Sailors are already drowning in harbour."],
    ),
    (
        "egyptian", "bast", "Bast", "Of the cat, the joy, the sudden claw",
        "chaotic good", "War, Trickery, Life", "A cat, a sistrum, or an aegis with a lioness face",
        "greater",
        "A graceful woman with a black cat's head, gold earrings, white-and-red linen dress, sistrum in hand, temple cats at her feet. Fully clothed, elegant, not sexualized.",
        "Pleasure, protection, and the reminder that a house-cat is also a lion.",
        "Bast is music in the afternoon and a lioness at the gate. She is the god of people who keep cats because mice eat grain and because loneliness is a plague too.\n\nHer clerics dance, keep watch, and do not explain the claw. A party that hurts a temple cat has started a war with an entire neighbourhood.",
        "Perfume, a song, a bowl of milk. Do not kick a cat even as a joke in her town.",
        ["All the cats left a city in one night. The rats are already in the granary.", "A temple dancer was arrested for 'riot.' Bast wants her back before the festival, or there will be one."],
    ),
    (
        "egyptian", "bes", "Bes", "Dwarf-lion of the household, scarer of nightmares",
        "chaotic good", "Life, Trickery, War", "A grinning dwarf-lion face, or a tambourine",
        "lesser",
        "A short, lion-maned household god in a plumed headdress and kilt, grinning, tambourine in hand, standing in a doorway as a protector. Comic and fierce, clothed.",
        "The ugly little god who stands in the bedroom door so worse things do not.",
        "Bes is not handsome and does not care. He is carved on headboards and sword-pommels. He frightens nightmares and assists births. He is the most popular god in any street that has children.\n\nClerics of Bes are midwives, bouncers, and the person who sleeps across your threshold when you are fevered. Protection from evil is his whole personality.",
        "A laugh at a real fear. A carved face on a door. Do not mock a short guardian.",
        ["Nightmares in a barracks have a shape. Bes wants his image put back on the headboards someone scraped off.", "A noble banned 'ugly gods' from the quarter. Infant sleep ended the same week."],
    ),
    (
        "egyptian", "hathor", "Hathor", "Of the sycamore, the sistrum, the sky as a cow of gold",
        "neutral good", "Life, Light", "A cow's horns with a sun disk, or a sistrum",
        "greater",
        "A woman in a tripartite wig with cow horns and sun disk, gold-and-turquoise linen, sistrum raised, a sycamore behind her. Fully clothed, warm, queenly.",
        "Joy, music, and the sky that nurses the world. When she is angry, the joy becomes a lion.",
        "Hathor is the good day. She is also, in the old story, the eye of Re that almost ended people when they forgot to be kind. Her clerics keep that story as a warning, not a threat they enjoy.\n\nMusic, beer, and mercy. A feast in her name can stop a massacre if it is sincere. A fake feast makes her send the lioness aspect, and no one wants that at a table by accident.",
        "Beer, a song, a green branch. Mean joy is not an offering.",
        ["A festival was cancelled to fund a wall. The wall is already cracking in the shape of a smile.", "A sistrum in a tomb will not stop rattling. Hathor wants a dance in the street it was stolen from."],
    ),
    (
        "egyptian", "imhotep", "Imhotep", "The mortal who became a god of plans and medicine",
        "lawful good", "Knowledge, Life", "A papyrus scroll and a builder's cubit, or a step pyramid",
        "lesser",
        "A clean-shaven man in a simple white kilt and scribe's kit, holding a cubit rod and a scroll, a stepped pyramid rising behind him in clean desert light. Human, clothed, brilliant.",
        "Architecture and medicine as the same piety: measure twice, save once.",
        "Imhotep was a man. Then people would not stop praying to the man who designed the stone that did not fall and the treatment that did not kill. He is the patron of competent work.\n\nClerics of Imhotep are architects and physicians. They hate sloppy magic the way he hated sloppy stone. A collapsing dungeon is a theological problem.",
        "A true measurement. A prescription that matches the disease. Do not sign a plan you did not read.",
        ["A step-pyramid is walking, one course a night, toward a city. Imhotep wants the original plan found.", "A plague is being treated with a fake Imhotep seal. The real work is in a sealed library."],
    ),
    (
        "egyptian", "isis", "Isis", "Of the throne, the knot, the word that puts a house back together",
        "neutral good", "Life, Knowledge, Trickery", "A throne-hieroglyph, a tyet knot, or a kite-hawk",
        "greater",
        "A woman in a throne-shaped crown and layered linen, tyet amulet, wings of a kite suggested in the cloak, reassembling a scattered household in gold light. Fully clothed, sovereign.",
        "Magic as motherhood and statecraft. She hid a child, learned a secret name, and put a broken king back into a story that could rule.",
        "Isis is the reason a dynasty survives a murder. She is cunning, not cruel. She collected a dismembered house and made it a kingdom again. That is the religion.\n\nHer clerics are restorers: of people, of names, of laws. Greater restoration is her handshake. A party that erases a name from a wall has picked a fight with her filing system.",
        "A knot tied with intent. A true name spoken to heal, not to bind without cause.",
        ["A king's name was chiselled off every monument. The land is forgetting how to have a king. Isis wants the chips.", "A child in hiding is the last of a house. Two cults want them. She wants a third option: the party."],
    ),
    (
        "egyptian", "nephthys", "Nephthys", "Of the edge of the house, the kite at the funeral",
        "chaotic good", "Death, Trickery, Knowledge", "A house-and-basket hieroglyph, or a kite on a tomb",
        "lesser",
        "A woman in a close-fitting dark linen dress and a headdress of house-and-basket, standing at the foot of a tomb as a protector, a kite overhead. Clothed, night-blue, not morbid-gore.",
        "The sister at the funeral. She is the night-watch of the dead and the helper of hidden children.",
        "Nephthys stands where the house ends and the desert starts. She helped Isis, she mourns well, and she keeps secrets that would smash a court if said at noon.\n\nHer clerics are the ones who sit with the body until morning. They are also excellent at smuggling people out of palaces. Pass without trace is a kindness.",
        "A night-watch kept without sleeping on duty. Water poured at the desert edge of a grave.",
        ["A funeral was left unwatched. Something wore the linen out of the tomb. Nephthys wants a vigil finished.", "A hidden heir is in a kite-priest's house. Three factions know the street, not the door."],
    ),
    (
        "egyptian", "osiris", "Osiris", "Of the green, the throne below, the second life of grain",
        "lawful good", "Life, Nature, Knowledge", "A crook and flail, or a djed pillar",
        "greater",
        "A green-skinned king in white mummy-wrappings as royal dress (not a rotting corpse), white crown with plumes, crook and flail, seated in a calm underworld court. Dignified, no gore.",
        "Death that became agriculture. He is the judge of the dead and the reason seed comes back.",
        "Osiris was murdered and still became the reason the flood makes grain. He judges the dead because he has been one. His court is fair and slow.\n\nClerics of Osiris farm and bury. Revivify is a civic duty, not a party trick. A land that forgets the flood calendar has forgotten him.",
        "Grain in a tomb and a true account of a life. Do not mock a mummy as a monster if it was a person.",
        ["The flood did not come. A piece of Osiris — a story, a relic — is in a locked granary.", "A judge of the dead is taking bribes in his name. The feather will not balance until that stops."],
    ),
    (
        "egyptian", "ptah", "Ptah", "Of the word that is a thing, the craftsman's first sentence",
        "lawful good", "Knowledge, Life", "A sceptre combining was, ankh, and djed, or a craftsman's block",
        "greater",
        "A shaven man in a tight white robe and a skullcap, holding a combined was-ankh-djed sceptre, a workshop of perfect tools behind him. Contained, clothed, creative.",
        "Creation by speaking the true name of a thing. He is the patron of people who make the world on purpose.",
        "Ptah does not swing a hammer as much as he says the hammer correctly. Memphis kept him as the mind of making. A poorly named magic item offends him more than a broken one.\n\nClerics of Ptah are crafters and linguists. Fabricate is theology. A party that uses a true name as a joke will find the joke has load-bearing walls.",
        "Speak the work before you do it. A well-made tool on the altar beats a jewel.",
        ["A statue of Ptah said a word in the night and a new street existed in the morning. The city map is now a liar.", "Someone is selling 'true names' that almost work. Almost is how you get a cursed river."],
    ),
    (
        "egyptian", "set", "Set", "Of the red land, the storm, the necessary outsider",
        "chaotic evil", "Tempest, Trickery, War", "The set-animal, or a was-sceptre on red sand",
        "greater",
        "A powerful man with the mysterious set-animal head (long snout, squared ears), red-and-white desert armour-linen, was-sceptre, a sandstorm wall behind him. Alien, clothed, not gore.",
        "Desert, storm, and the violence that sometimes holds the barque together. He is a murderer in the old story and a defender in the next chapter.",
        "Set killed Osiris and also stands on the sun-barque to fight Apep. He is the god of foreigners, of necessary force, of the land that will not be farmed. Tables can play him as a villain or as the ugly ally.\n\nClerics of Set are desert guides, storm-callers, and political knives. They are not welcome at every feast. They are welcome at every sandstorm.",
        "Red beer, a storm-prayer, an honest admission of envy. Do not pretend you are Osiris if you are Set.",
        ["A sandstorm has a shape and a grudge. Set will call it off for a service against Apep's cult.", "A foreign company has taken a quarry in his name without asking the desert. The stone is screaming when cut."],
    ),
    (
        "egyptian", "sobek", "Sobek", "Of the crocodile, the river's appetite, the army at the water",
        "lawful evil", "Nature, War, Tempest", "A crocodile, or a plumed crocodile-crown",
        "lesser",
        "A crocodile-headed warrior in scale-linen and a tall plumed crown, standing in a lotus marsh, army banners on the far bank. Powerful, clothed, river-gold light.",
        "The river as a mouth that also waters the fields. He is strength, the army, and a very honest hunger.",
        "Sobek is not subtle. He is the crocodile that is also a king. Fayum kept him because the water that feeds you can also take you, and it is better if that has a priest.\n\nClerics of Sobek are marines and irrigation tyrants. Control water. A party that dumps poison in a river has declared war on a crocodile cult, which is a specific kind of mistake.",
        "Meat in the water, given, not stolen from a trap. Do not boast you 'tamed' a crocodile.",
        ["Crocodiles have left the water and are sitting on a courthouse. Sobek wants a drowned law rewritten.", "A dam is starving his marsh. The army that built it is losing men at night, one at a time, to something patient."],
    ),
    (
        "egyptian", "thoth", "Thoth", "Of the ibis, the moon-count, the word that is a number",
        "neutral", "Knowledge", "An ibis, a baboon, or a scribe's palette",
        "greater",
        "An ibis-headed scribe in star-white linen, palette and reed pen, a moon-disk, scrolls in perfect stacks, night-blue temple. Intellectual, clothed, calm.",
        "Writing, the calendar, and the magic that is just extremely good filing.",
        "Thoth invented letters so the gods could not lie about what they said yesterday. He umpires cosmic disputes. He is why a contract, a spell, and a calendar are cousins.\n\nClerics of Thoth are scribes. Comprehend languages, identify, legend lore. A party that burns a library in his nome will find they can no longer count past seven until they copy a book by hand.",
        "A true copy. Ink on the altar. Do not sign a blank page in his house.",
        ["Every date in a city is wrong by three days. Thoth wants the stolen calendar-stone.", "A spell is misspelled in every book except one. That one is in a crocodile pond. He is not sorry."],
    ),
    # ——— Norse ———
    (
        "norse", "odin", "Odin", "Allfather, one-eyed guest, lord of the hanged and the poem",
        "neutral", "Knowledge, Trickery, War", "A one-eyed face, two ravens, or a spear",
        "greater",
        "An old, one-eyed wanderer in a blue cloak and broad hat, spear in hand, two ravens on his shoulders, two wolves at his feet, winter road. Clothed, terrible and kind.",
        "Wisdom bought expensive. He is king, wizard, and the stranger who tests your hall.",
        "Odin gave an eye for a drink of knowing and still wants more. He walks as a guest to see if you keep the old laws. He takes the slain to a hall that is a training camp, not a rest.\n\nClerics of Odin are poets, spies, and captains. They hate a closed mind and a closed hall. Divination always costs. A party that refuses a wanderer bread has already met him.",
        "Mead, a riddle, a seat for a stranger. Do not ask him to be only kind.",
        ["A one-eyed guest was turned away in a storm. The next three guests have been wolves.", "Two ravens will not leave a PC. Odin wants a word stolen from a well that bites."],
    ),
    (
        "norse", "aegir", "Aegir", "Of the ale-sea, the drowning hall under the wave",
        "neutral evil", "Tempest, Trickery", "A foaming ale-horn over a wave, or a drowning net",
        "lesser",
        "A huge, gold-generous sea-giant in sea-dark robes, brewing in a cauldron the size of a boat, hall-pillars of whalebone, green water-light. Clothed, hospitable, dangerous.",
        "The sea as a host who sometimes keeps the guests.",
        "Aegir brews for the gods and drowns sailors with the same hospitality. His hall is under the water. If you are invited, bring a gift. If you are not, you are the gift.\n\nClerics of Aegir are brewers and wreckers. They bless ships they like. A party that dumps ballast on a sacred skerry has RSVP'd.",
        "The first ale into the sea. A gold ring if you want a calm crossing.",
        ["A ship arrived with no crew and a full cask. Aegir wants the cask delivered, not drunk.", "Fishermen pulled up a hall-pillar. The sea has been knocking on the village palisade since."],
    ),
    (
        "norse", "balder", "Balder", "The bright one, whose death is a season the world has not finished",
        "neutral good", "Life, Light", "A sprig of mistletoe, or a sun on a shield",
        "greater",
        "A luminous, kind young lord in white-and-gold, unarmed, a shield at rest, mistletoe small in the scene, summer hall. Clothed, tragic, not a corpse.",
        "Joy that was so complete the world had to find a loophole. He is beauty, peace, and the coming grief.",
        "Balder was loved so well that everything swore not to hurt him — except the joke plant. The stories do not hide how that ends. At a table he is the peace everyone wants and the vulnerability no one budgeted for.\n\nClerics of Balder are peacemakers who still know a spear. They are the reason a truce holds until mistletoe gets involved.",
        "A kind word that costs you something. Do not make a joke of a sworn peace.",
        ["Mistletoe has started growing on every spear in a keep. Balder wants the joke disarmed.", "A lord who cannot be harmed by anything but 'a child's toy' is about to sit in a hall of children. Someone sent an invitation."],
    ),
    (
        "norse", "forseti", "Forseti", "Of the fair sitting, the god who ends a feud without a grave",
        "lawful good", "Knowledge, Life", "A golden axe at rest, or a set of balanced scales",
        "lesser",
        "A calm, golden-haired judge in a simple rich cloak, seated in a hall of pale wood, an unused axe on the table, two angry chieftains silent. Clothed, still.",
        "Law as a hall you can walk out of alive. He is the best ending a saga did not want to write.",
        "Forseti settles cases so well that even the stubborn leave quiet. His axe is a symbol because it is not being used. That is the miracle.\n\nClerics of Forseti are law-speakers. Zone of truth, calm emotions. A party that solves a murder with a massacre in his district will be asked to sit, for a long time.",
        "Tell the whole story. Leave the weapon on the table, not in it.",
        ["A feud is about to become a burning. Forseti wants one sitting, tonight, with the party as witnesses who cannot leave.", "His golden axe was stolen and used. It will not come out of the beam until a true verdict is spoken."],
    ),
    (
        "norse", "frey", "Frey", "Of the harvest, the boar, the sword he should not have given away",
        "neutral good", "Life, Nature, Light", "A golden boar, a ship that folds, or a sheaf",
        "greater",
        "A handsome harvest-lord in green-gold, a golden-bristled boar at his side, a folded ship like a toy in his hand, fields in good weather. Clothed, generous.",
        "Peace, rain, and the fertility of fields and herds. He once traded his sword for love and the last war will notice.",
        "Frey is the good year. His boar lights the dark. His ship holds an army and folds into a pocket. He gave away the sword he will want at the end of things. That is a campaign hook with a god's name on it.\n\nClerics of Frey keep markets and marriages. Plant growth. A famine in his country is a crime scene.",
        "The first loaf, the first ale, a kind marriage. Do not starve a neighbour to raise a price.",
        ["His folding-ship is in a tax-booth as a 'curiosity.' It is unfolding.", "A drought ends at the border of one farm. That farmer sold Frey's sword last winter."],
    ),
    (
        "norse", "freya", "Freya", "Of the necklace, the falcon-cloak, the slain she chooses first",
        "neutral good", "Life, War, Trickery", "A falcon, a necklace of many fires, or a cat-drawn cart",
        "greater",
        "A commanding woman in a falcon-feather cloak over a rich gown, Brisingamen at her throat, two cats at the cart, a distant battlefield she is choosing from. Fully clothed, regal, not a pin-up.",
        "Love, seiðr, and the first pick of the slain. She is not Odin's assistant. She is the other hall.",
        "Freya taught the gods a magic they still side-eye. She rides to war and takes half the dead. She weeps gold. She is the patron of people who will not be only one thing.\n\nClerics of Freya are seers and captains. They keep cats and secrets. A party that treats her as 'the love goddess' will meet the war goddess on the same day.",
        "Amber, a song, a truth you did not want to say. Do not cage a cat in her town.",
        ["Half a battlefield's dead sat up and walked toward the sea. Freya wants to know who is poaching her share.", "Brisingamen has a fake in a queen's box. The real one is hunting the thief as a necklace-shaped heat."],
    ),
    (
        "norse", "frigga", "Frigga", "Of the keyed hall, the knowing she will not say",
        "neutral good", "Life, Knowledge, Trickery", "A bunch of keys, a spinning-wheel, or a cloud-cloak",
        "greater",
        "A mature queen in a cloud-grey gown and a key-ring at her belt, spinning white wool, a wide window on the worlds. Fully clothed, still, omniscient calm.",
        "Queenship, foresight, and the choice not to spoil the ending. She already knows. She will not always tell.",
        "Frigga sees more than Odin and spends less of it. She is the hall, the marriage, the cloud. She bound the world to spare Balder and the loophole still happened. She is not a failure. She is a god who understands limits.\n\nClerics of Frigga keep households and secrets. They are terrifying at court. A divination in her name may come back as 'you already know.'",
        "A key on the altar. Spin a thread for someone you mean to keep.",
        ["A queen is spinning a thread that is a person's lifespan. Frigga wants the wheel stopped, not the queen killed.", "Every key in a keep opened the wrong door. She wants a promise kept that was made in a kitchen."],
    ),
    (
        "norse", "heimdall", "Heimdall", "White god of the bridge, who hears the grass grow",
        "lawful good", "Light, Knowledge, War", "A horn, a rainbow bridge, or a golden tooth",
        "greater",
        "A pale, keen-eyed watchman in white-and-gold mail, Gjallarhorn at his hip, standing on a rainbow bridge over mist, seeing past the viewer. Clothed, alert.",
        "The watch that does not blink. He will blow the horn when the end starts, and not before.",
        "Heimdall can hear wool grow on a sheep three worlds away. He sleeps less than a bird. He is the reason a sneak attack on the gods' road is a bad career.\n\nClerics of Heimdall are sentries. They hate surprise for its own sake. Alarm and see invisibility. A party that tries to 'just sneak in' to a holy bridge has a new enemy with a horn.",
        "A watch kept until relieved. A horn-call only for a true emergency.",
        ["The rainbow bridge has a crack that only the deaf can see. Heimdall wants a mason who is also a listener.", "Someone stole a note of his horn. Every alarm in a city now sounds like the end of the world, once a day."],
    ),
    (
        "norse", "hel", "Hel", "Of the rain-dark hall, keeper of those who did not die in song",
        "neutral evil", "Knowledge, Trickery, Life", "A half-dark face, or a down-facing hall",
        "greater",
        "A composed woman, one side living and fair, one side shadowed like stone, seated on a low throne in a vast quiet hall, living attendants, no corpses, no gore, sovereign.",
        "The dead who did not go to a war-hall still have a queen. She is not a devil. She is a host with a long guest-list.",
        "Hel keeps those who died of sickbed and winter. Her hall is not a torture-show unless a table makes it one. She is due respect because everyone visits.\n\nClerics of Hel are undertakers and the people who speak for the unheroic dead. They hate a funeral that pretends a farmer was a king, and they hate a king who dumps the poor in a ditch.",
        "A bowl of food at a funeral for the one who cannot eat it. Do not mock a quiet death.",
        ["The sick of a town are dying in their sleep with no disease. Hel wants a stolen name-list back.", "A war-priest declared that plague-dead 'do not count.' Their graves have opened as doors, not as monsters — yet."],
    ),
    (
        "norse", "hermod", "Hermod", "The bold rider, messenger down the long road",
        "chaotic good", "Trickery, War", "A rider on a eight-legged shadow, or a sealed letter",
        "lesser",
        "A young, grim rider in a travel-cloak, on a great horse, a sealed message in hand, a dark road toward a distant hall. Clothed, in motion.",
        "The errand into death and back. He is the patron of messages that should have been impossible.",
        "Hermod rode to Hel to bargain for Balder and almost made it work. He is the god of the last try. Couriers, envoys, and people who volunteer for the stupid brave job keep him.\n\nClerics of Hermod deliver. Expeditious retreat, sending. A party that opens a sealed letter in his name finds the words have left the page and gone ahead.",
        "A letter delivered unopened. A horse watered before the rider drinks.",
        ["A message to Hel was never sent. The living addressee is aging a year a day.", "Hermod wants a rider for a road that only exists at dusk. Pay is a true name and a way back."],
    ),
    (
        "norse", "loki", "Loki", "The sly, the change-skin, the problem that is also a tool",
        "chaotic evil", "Trickery", "A knot of flame, a fishing-net, or a two-faced smile",
        "greater",
        "A lean, handsome troublemaker in a green-and-gold travel kit, firelight, a net and a grin, shapeshifting hinted in a fox-shadow. Clothed, charming, dangerous.",
        "The lie that gets the gods out of a hole and into a worse one. He is wit, spite, and the bill coming due.",
        "Loki is why the walls got built and why the builder almost took the sun. He is not 'random chaos.' He is a person who cannot stand being outdone or boxed. At a table he is an ally until he is the plot.\n\nClerics of Loki are spies and saboteurs. They must be more clever than cruel or the other cults will end them. Disguise self is a lifestyle.",
        "A clever gift that is also a joke. Do not swear a straight oath in his hearing unless you mean the loophole.",
        ["A wall was built in three nights by something that was not supposed to finish. Loki wants the loophole found before the sun is claimed.", "Every lie a PC tells comes true for an hour. He thinks this is educational."],
    ),
    (
        "norse", "njord", "Njord", "Of the wind that brings ships, the wealth that smells of tar",
        "neutral good", "Nature, Tempest", "A ship's prow, a gold coin with a fish, or a seagull",
        "greater",
        "A weathered, generous sea-father in a salt-stained rich cloak, a harbour full of masts behind him, gold in a net, good wind. Clothed, prosperous.",
        "Fair winds, fishing, and money that came over water. He is the calm that sailors actually want.",
        "Njord is the sea when it is a living. He married into the mountains and was miserable, which is a useful story about people who pray for wealth and get a different country.\n\nClerics of Njord bless launches and ledgers. Gust of wind, water breathing. A wrecker-cult in his harbour is a personal insult.",
        "The first coin of a voyage into the water. Do not cheat a crew of their share.",
        ["The wind in a harbour blows only toward the rocks. Njord wants a drowned ledger raised.", "A marriage-treaty between a sea-town and a mountain-hold is failing in the same way his did. He would like it not to."],
    ),
    (
        "norse", "odur", "Odur", "The wanderer-husband, summer on a long road",
        "chaotic good", "Light, Trickery", "A sun-cloak on a staff, or an empty chair beside a queen",
        "lesser",
        "A sun-browned wanderer in a faded gold cloak, staff, looking back at a hall he is leaving, summer road. Human, clothed, restless.",
        "The bright husband who cannot stay. He is travel, summer, and the ache in a house that waits.",
        "Odur is Freya's wandering other. Where he walks, summer follows for a while. Where he does not, she weeps gold. He is the patron of people who love a place and still leave it.\n\nClerics of Odur are travellers. They bless departures. Longstrider. A party that stays in an inn for a month in his name will find the inn moving.",
        "A step taken at dawn. Do not promise to stay if you mean to go.",
        ["Summer is following a cart. The cart is Odur's cloak, stolen. Fields behind it are going to autumn early.", "A queen's tears are gold in the street. She will stop when someone finds her husband or a true reason he left."],
    ),
    (
        "norse", "sif", "Sif", "Of the golden hair, the harvest that is a marriage",
        "chaotic good", "Life, War", "A sheaf of gold hair, or a sword laid in grain",
        "lesser",
        "A composed woman with impossibly gold hair, in a green gown, a field of ripe grain, a sword at rest. Fully clothed, northern, warm.",
        "The field and the household of thunder. She is plenty, and the reminder that a cruel joke can still be paid for in gold.",
        "Sif's hair was cut as a prank and replaced with gold that grows. She is the harvest you can see from the hall. She is also Thor's match, which means her clerics are not fragile.\n\nA blight on wheat in her country is a crime. Plant growth, hero's feast. A barber-joke in a temple will be expensive.",
        "A braid of the first ripe grain. Do not cut what you cannot replace.",
        ["A whole village woke shorn. Their grain is dying in the same pattern as the missing hair.", "Gold hair in a river is tangling mill-wheels. Sif wants the prankster, not a funeral."],
    ),
    (
        "norse", "skadi", "Skadi", "Of the ski, the bow, the mountain that married the sea and went home",
        "neutral", "Nature, War", "A ski and a bow, or a wolf on a peak",
        "lesser",
        "A tall huntress on skis, fur-lined coat and trousers, bow, a high white mountain, a distant unhappy harbour far below. Fully clothed, winter, independent.",
        "Winter hunting and the right to leave a marriage that was the wrong country.",
        "Skadi came out of the mountains to demand weregild with her boots on. She married the sea and missed the wolves. She went home. That is a complete theology of knowing where you can live.\n\nClerics of Skadi are hunters and divorce-lawyers of the ice. Pass without trace in snow. A forced marriage in her hearing is a combat encounter.",
        "A clean hunt in the high snow. Do not make someone live where they cannot breathe.",
        ["A sea-lord is keeping a mountain bride in a harbour house. The wolves are in the street.", "An avalanche opened a hall of skis and bows. Skadi wants them used, not sold."],
    ),
    (
        "norse", "surtur", "Surtur", "Of the fire that waits at the south end of the story",
        "lawful evil", "War, Light", "A flaming sword taller than a man, or a black fire-crown",
        "greater",
        "A gigantic fire-giant king in black-and-gold armour, a sword of fire, a gate of heat behind him, no burning people, apocalyptic forge-light. Clothed in armour, monumental.",
        "The fire at the end of the world, currently employed as a king of Muspelheim. He is patient. He is not kind.",
        "Surtur is the scheduled fire. Cults that hurry him are fools; cults that ignore him are also fools. He is a lawful end, not a riot.\n\nTrue clerics of Surtur are rare and alarming. Fireball is not a personality. A table that wants a slow apocalypse antagonist can give him a priest who thinks they are doing maintenance.",
        "A flame that has never cooked a meal. Do not start a fire you cannot name the purpose of.",
        ["A sword in a glacier is steaming. Surtur wants it left until the story says otherwise. Someone is digging.", "A fire-cult is trying to skip to the last chapter. The giants are embarrassed, which is worse than angry."],
    ),
    (
        "norse", "thor", "Thor", "Of the hammer, the storm, the hall-friend of ordinary people",
        "chaotic good", "Tempest, War", "Mjolnir, a goat, or a thunder-wheel",
        "greater",
        "A red-bearded, broad warrior in a simple rich tunic and belt, hammer raised, goats in the storm-light, protecting a farmstead-sized world. Clothed, heroic, not a caricature.",
        "Thunder that is on your side if you are small and being kicked. He is the most popular god for a reason.",
        "Thor kills giants and drinks with farmers. He is not subtle and he is not cruel. His hammer comes back. His goats come back. The point is that ordinary life is allowed to continue.\n\nClerics of Thor are the reason a village militia holds. Thunderwave, call lightning. A party that preys on farmers in his country will hear wheels in the sky.",
        "Ale, a goat if you can spare it, a boast you can back. Do not bully a hall.",
        ["Giants are moving a millstone that is actually a hammer-head. Thor wants it thrown, not studied.", "A taxman is taking goats 'for the jarl' and the storms have started answering doors."],
    ),
    (
        "norse", "thrym", "Thrym", "King of the rime-giants, thief of hammers",
        "chaotic evil", "War, Tempest", "A hoar-frost crown, or a stolen hammer-silhouette",
        "lesser",
        "A massive frost-giant king in rime-crusted mail and furs, a empty hammer-stand beside his throne, aurora over a frozen hall. Clothed, cold, greedy.",
        "The ice that wants the thunder's tool. He is a bride-price joke that almost worked.",
        "Thrym stole Mjolnir and asked for Freya as the price. The gods sent Thor in a dress. The stories are allowed to be funny and still end in a pile of giants.\n\nClerics of Thrym are rare outside Jotun cults. They want winter to last and tools to change owners. A stolen magic weapon in a cold dungeon may be a tithe.",
        "A stolen tool laid on ice. Do not pretend to be a bride if you cannot finish the joke.",
        ["A frost-giant wedding is tomorrow. The bride is a problem. The dowry is a legendary weapon.", "Every hammer in a town has frozen to the anvil. Thrym wants a conversation about a loan."],
    ),
    (
        "norse", "tyr", "Tyr", "One-handed keeper of the oath, who paid in advance",
        "lawful good", "War, Knowledge", "A sword, a missing right hand, or a bound wolf's shadow",
        "greater",
        "A grave, one-handed war-god in simple mail, right wrist ending cleanly, sword in the left, a great wolf bound in the distance, hall-law light. Clothed, honourable, no gore.",
        "The oath that costs a hand. He is courage, law, and the bill you knew you would pay.",
        "Tyr put his hand in the wolf's mouth so the binding would hold. He is the god of people who sign knowing the price. Cowards do not keep him long.\n\nClerics of Tyr are officers and judges. They hate a clever oath that was always a lie. Zone of truth, crusader's mantle. A party that breaks parole in his name will find their own right hands unreliable.",
        "A vow with a witness. Do not swear what you will not pay.",
        ["A bound monster is chewing through a contract. Tyr wants a new witness, living.", "A captain lost a hand in a false truce. He wants the truce-maker, and Tyr is already walking with him."],
    ),
    (
        "norse", "uller", "Uller", "Of the yew-bow, the bone-skate, the duel in the snow",
        "chaotic neutral", "Nature, War", "A longbow of yew, or a bone skate",
        "lesser",
        "A lone hunter on bone skates, yew bow, fur hood, a frozen lake and pine edge, winter dusk. Fully clothed, spare, sharp.",
        "Archery, duels, and the winter road that is a weapon.",
        "Uller keeps the winter when even Thor is elsewhere. He is the bow, the skate, the single combat on a lake. Oaths sworn on his ring are mean and binding.\n\nClerics of Uller are archers and duel-seconds. Hail of thorns, hunter's mark. A party that refuses a fair duel in the snow may still have to skate it.",
        "A ring-oath in winter. The first arrow of a hunt left in a tree.",
        ["A frozen lake is a courtroom. Uller wants a champion to skate a lie down.", "Every bowstring in a fort has gone slack except one yew. It will only serve a just shot."],
    ),
]


def main() -> None:
    out = []
    for pan, gid, name, aka, align, domains, symbol, rank, look, blurb, text, worship, hooks in GODS:
        out.append(
            {
                "id": gid,
                "name": name,
                "aka": aka,
                "kind": pan,
                "pantheon": pan,
                "align": align,
                "domains": domains,
                "symbol": symbol,
                "rank": rank,
                "look": look,
                "blurb": blurb,
                "text": text,
                "worship": worship,
                "hooks": hooks,
            }
        )
    out.sort(key=lambda r: r["name"].lower())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(len(out), "gods ->", OUT)


if __name__ == "__main__":
    main()
